// Auto-generated by tools/sink_user_repository.ps1 from UserRepository.h
#include "UserRepository.h"

#include <algorithm>
#include <array>
#include <cctype>
#include <chrono>
#include <cstdint>
#include <random>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#include <drogon/HttpTypes.h>
#include <drogon/utils/Utilities.h>
#include <openssl/crypto.h>
#include <openssl/evp.h>
#include <openssl/rand.h>

#include "JsonIo.h"
#include "common/AppException.h"
#include "common/IdGenerator.h"
#include "common/TimeUtils.h"

namespace infrastructure::storage
{
namespace
{
constexpr std::uint64_t kScryptN = 16384;
constexpr std::uint64_t kScryptR = 8;
constexpr std::uint64_t kScryptP = 1;
constexpr std::size_t kScryptSaltBytes = 16;
constexpr std::size_t kScryptHashBytes = 32;
constexpr std::uint64_t kScryptMaxMemory = 64ULL * 1024ULL * 1024ULL;

std::string toHex(const unsigned char *data, std::size_t size)
{
    static constexpr char digits[] = "0123456789abcdef";
    std::string out(size * 2, '0');
    for (std::size_t index = 0; index < size; ++index)
    {
        out[index * 2] = digits[(data[index] >> 4U) & 0x0FU];
        out[index * 2 + 1] = digits[data[index] & 0x0FU];
    }
    return out;
}

bool fromHex(const std::string &hex, std::vector<unsigned char> &out)
{
    if (hex.size() % 2 != 0)
    {
        return false;
    }
    const auto nibble = [](char value) -> int {
        if (value >= '0' && value <= '9') return value - '0';
        if (value >= 'a' && value <= 'f') return value - 'a' + 10;
        if (value >= 'A' && value <= 'F') return value - 'A' + 10;
        return -1;
    };
    out.resize(hex.size() / 2);
    for (std::size_t index = 0; index < out.size(); ++index)
    {
        const auto high = nibble(hex[index * 2]);
        const auto low = nibble(hex[index * 2 + 1]);
        if (high < 0 || low < 0)
        {
            out.clear();
            return false;
        }
        out[index] = static_cast<unsigned char>((high << 4) | low);
    }
    return true;
}

std::vector<std::string> splitHash(const std::string &encoded)
{
    std::vector<std::string> parts;
    std::istringstream input(encoded);
    std::string part;
    while (std::getline(input, part, '$'))
    {
        parts.push_back(part);
    }
    return parts;
}
}  // namespace

UserRepository::UserRepository(std::filesystem::path userRootDir)
    : userRootDir_(std::move(userRootDir)),
      usersFile_(userRootDir_ / "users.json"),
      rolesFile_(userRootDir_ / "roles.json"),
      sqliteStore_(userRootDir_ / "core.sqlite3"),
      wal_(userRootDir_ / "_users.wal.log", userRootDir_ / "_users.wal.snapshot.json")
{
    std::filesystem::create_directories(userRootDir_);
    recoveredEvents_ = wal_.recover().size();
    ensureBaseline();
}

void UserRepository::ensureBaseline()
{
    std::unique_lock lock(mutex_);
    if (sqliteStore_.count("users") == 0)
    {
        Json::Value users = std::filesystem::exists(usersFile_) ? readJsonFile(usersFile_) : Json::Value(Json::objectValue);
        if (!users.isObject()) users = Json::Value(Json::objectValue);
        if (users.empty())
        {
        users["guest"]["id"] = "guest";
        users["guest"]["user_id"] = "guest";
        users["guest"]["username"] = "guest";
        users["guest"]["password_hash"] = hashPassword("guest");
        users["guest"]["password_algo"] = "scrypt";
        users["guest"]["status"] = "active";
        users["guest"]["email"] = "";
        users["guest"]["email_verified"] = false;
        users["guest"]["phone"] = "";
        users["guest"]["phone_verified"] = false;
        users["guest"]["member_no"] = "";
        users["guest"]["scope_type"] = "personal";
        users["guest"]["scope_id"] = "guest";
        users["guest"]["organization_type"] = "";
        users["guest"]["roles"] = Json::arrayValue;
        users["guest"]["roles"].append("guest");
        users["guest"]["created_at"] = common::nowIso8601();
        }
        writeUsersUnlocked(users);
    }

    if (!std::filesystem::exists(rolesFile_))
    {
        writeJsonFileAtomic(rolesFile_, defaultRolesMap());
        return;
    }

    auto roles = readJsonFile(rolesFile_);
    Json::Value normalized = defaultRolesMap();
    if (roles.isMember("roles") && roles["roles"].isArray())
    {
        for (const auto &role : roles["roles"])
        {
            const auto id = normalizeRoleId(role.get("id", "").asString());
            if (id.empty())
            {
                continue;
            }
            normalized[id] = mergeRoleDefinition(normalized[id], role, id);
        }
    }
    else if (roles.isObject())
    {
        for (const auto &id : roles.getMemberNames())
        {
            const auto normalizedId = normalizeRoleId(id);
            if (normalizedId.empty())
            {
                continue;
            }
            normalized[normalizedId] = mergeRoleDefinition(normalized[normalizedId], roles[id], normalizedId);
        }
    }

    wal_.append("roles_normalized", normalized);
    writeJsonFileAtomic(rolesFile_, normalized);
}

Json::Value UserRepository::readUsersUnlocked() const
{
    if (usersCacheLoaded_) return usersCache_;
    Json::Value users(Json::objectValue);
    for (const auto &entry : sqliteStore_.list("users"))
    {
        const auto user = normalizeUser(entry);
        const auto id = user.get("id", user.get("user_id", "")).asString();
        if (!id.empty()) users[id] = user;
    }
    usersCache_ = users;
    usersCacheLoaded_ = true;
    return usersCache_;
}

void UserRepository::writeUsersUnlocked(const Json::Value &users)
{
    Json::Value items(Json::arrayValue);
    forEachUserValue(users, [&items](const Json::Value &entry) {
        const auto user = normalizeUser(entry);
        if (!user.get("id", user.get("user_id", "")).asString().empty()) items.append(user);
    });
    sqliteStore_.replace("users", items, "id");
    usersCache_ = users;
    usersCacheLoaded_ = true;
}

Json::Value UserRepository::users() const
{
    std::shared_lock lock(mutex_);
    auto rawUsers = readUsersUnlocked();
    Json::Value normalized(Json::objectValue);
    forEachUserValue(rawUsers, [&normalized](const Json::Value &entry) {
        const auto user = normalizeUser(entry);
        const auto key = user.get("id", user.get("user_id", "")).asString();
        if (!key.empty())
        {
            normalized[key] = user;
        }
    });
    return normalized;
}

Json::Value UserRepository::roles() const
{
    std::shared_lock lock(mutex_);
    auto rolesJson = readJsonFile(rolesFile_);
    Json::Value normalized = defaultRolesMap();
    for (const auto &id : rolesJson.getMemberNames())
    {
        const auto normalizedId = normalizeRoleId(id);
        if (normalizedId.empty())
        {
            continue;
        }
        normalized[normalizedId] = mergeRoleDefinition(normalized[normalizedId], rolesJson[id], normalizedId);
    }
    return normalized;
}

Json::Value UserRepository::findUserByUsername(const std::string &username) const
{
    std::shared_lock lock(mutex_);
    auto usersJson = readUsersUnlocked();
    Json::Value result(Json::nullValue);
    forEachUserValue(usersJson, [&result, &username](const Json::Value &entry) {
        if (!result.isNull())
        {
            return;
        }
        const auto user = normalizeUser(entry);
        if (user.get("username", "").asString() == username)
        {
            result = user;
        }
    });
    return result;
}

Json::Value UserRepository::findUserByEmail(const std::string &email) const
{
    std::shared_lock lock(mutex_);
    auto usersJson = readUsersUnlocked();
    Json::Value result(Json::nullValue);
    forEachUserValue(usersJson, [&result, &email](const Json::Value &entry) {
        if (!result.isNull())
        {
            return;
        }
        const auto user = normalizeUser(entry);
        if (user.get("email", "").asString() == email)
        {
            result = user;
        }
    });
    return result;
}

Json::Value UserRepository::findUserByLoginId(const std::string &loginId) const
{
    std::shared_lock lock(mutex_);
    auto usersJson = readUsersUnlocked();
    Json::Value result(Json::nullValue);
    forEachUserValue(usersJson, [&result, &loginId](const Json::Value &entry) {
        if (!result.isNull())
        {
            return;
        }
        const auto user = normalizeUser(entry);
        if (matchesLoginId(user, loginId))
        {
            result = user;
        }
    });
    return result;
}

Json::Value UserRepository::findUserById(const std::string &userId) const
{
    std::shared_lock lock(mutex_);
    auto usersJson = readUsersUnlocked();
    Json::Value result(Json::nullValue);
    forEachUserValue(usersJson, [&result, &userId](const Json::Value &entry) {
        if (!result.isNull())
        {
            return;
        }
        const auto user = normalizeUser(entry);
        if (user.get("id", "").asString() == userId)
        {
            result = user;
        }
    });
    return result;
}

Json::Value UserRepository::usersByRole(const std::string &roleId) const
{
    const auto normalizedRole = normalizeRoleId(roleId);
    std::shared_lock lock(mutex_);
    auto usersJson = readUsersUnlocked();
    Json::Value result(Json::arrayValue);
    forEachUserValue(usersJson, [&result, &normalizedRole](const Json::Value &entry) {
        const auto user = normalizeUser(entry);
        bool matched = false;
        for (const auto &role : user["roles"])
        {
            if (normalizeRoleId(role.asString()) == normalizedRole)
            {
                matched = true;
                break;
            }
        }
        if (normalizedRole == "guest" && user["roles"].empty())
        {
            matched = true;
        }
        if (matched)
        {
            result.append(user);
        }
    });
    return result;
}

Json::Value UserRepository::createUser(const std::string &username,
                       const std::string &password,
                       const std::string &email,
                       const std::string &referralCode)
{
    std::unique_lock lock(mutex_);
    auto usersJson = readUsersUnlocked();
    if (containsUsername(usersJson, username))
    {
        throw common::AppException("USER_EXISTS", "Username already exists", drogon::k400BadRequest);
    }

    Json::Value referrer(Json::nullValue);
    const auto normalizedReferralCode = normalizeReferralCode(referralCode);
    if (!normalizedReferralCode.empty())
    {
        referrer = findUserByReferralCodeUnlocked(usersJson, normalizedReferralCode);
        if (referrer.isNull())
        {
            throw common::AppException("REFERRAL_CODE_INVALID", "Referral code is invalid", drogon::k422UnprocessableEntity);
        }
    }

    const auto userId = generateUserId();
    const auto key = userId;
    usersJson[key]["id"] = userId;
    usersJson[key]["user_id"] = userId;
    usersJson[key]["username"] = username;
    usersJson[key]["member_no"] = nextPersonalMemberNo(usersJson);
    usersJson[key]["password_hash"] = hashPassword(password);
    usersJson[key]["password_algo"] = "scrypt";
    usersJson[key]["email"] = email;
    usersJson[key]["email_verified"] = false;
    usersJson[key]["phone"] = "";
    usersJson[key]["phone_verified"] = false;
    usersJson[key]["status"] = "active";
    usersJson[key]["scope_type"] = "personal";
    usersJson[key]["scope_id"] = userId;
    usersJson[key]["organization_type"] = "";
    usersJson[key]["roles"] = Json::arrayValue;
    usersJson[key]["roles"].append("student");
    usersJson[key]["created_at"] = common::nowIso8601();
    usersJson[key]["referral_code"] = generateReferralCode(usersJson, username);
    usersJson[key]["referred_by_user_id"] = referrer.isNull() ? "" : referrer.get("id", referrer.get("user_id", "")).asString();
    usersJson[key]["referred_by_code"] = referrer.isNull() ? "" : normalizedReferralCode;
    usersJson[key]["referral_bound_at"] = referrer.isNull() ? "" : common::nowIso8601();
    usersJson[key]["referral_reward_status"] = referrer.isNull() ? "none" : "pending";

    wal_.append("user_created", usersJson[key]);
    writeUsersUnlocked(usersJson);
    return normalizeUser(usersJson[key]);
}

Json::Value UserRepository::createDevelopmentUser(const std::string &loginId)
{
    std::unique_lock lock(mutex_);
    auto usersJson = readUsersUnlocked();
    Json::Value existing(Json::nullValue);
    forEachUserValue(usersJson, [&existing, &loginId](const Json::Value &entry) {
        if (!existing.isNull())
        {
            return;
        }
        const auto user = normalizeUser(entry);
        if (matchesLoginId(user, loginId))
        {
            existing = user;
        }
    });
    if (!existing.isNull())
    {
        return existing;
    }

    const auto userId = generateUserId();
    const auto key = userId;
    const auto loginKey = sanitizeIdentifier(loginId);
    const auto username = uniqueUsernameForBase(usersJson, loginId.empty() ? ("wxdev_" + loginKey) : loginId);

    usersJson[key]["id"] = userId;
    usersJson[key]["user_id"] = userId;
    usersJson[key]["username"] = username;
    usersJson[key]["member_no"] = nextPersonalMemberNo(usersJson);
    usersJson[key]["password_hash"] = "";
    usersJson[key]["password_algo"] = "dev-empty";
    usersJson[key]["email"] = "";
    usersJson[key]["email_verified"] = false;
    usersJson[key]["phone"] = "";
    usersJson[key]["phone_verified"] = false;
    usersJson[key]["wechat_openid"] = "stub_openid_" + loginKey;
    usersJson[key]["wechat_nickname"] = username;
    usersJson[key]["dev_login_id"] = loginId;
    usersJson[key]["status"] = "active";
    usersJson[key]["scope_type"] = "personal";
    usersJson[key]["scope_id"] = userId;
    usersJson[key]["organization_type"] = "";
    usersJson[key]["roles"] = developmentRolesForLoginId(loginId);
    usersJson[key]["created_at"] = common::nowIso8601();

    wal_.append("development_user_created", usersJson[key]);
    writeUsersUnlocked(usersJson);
    return normalizeUser(usersJson[key]);
}

std::string UserRepository::hashPassword(const std::string &password)
{
    std::array<unsigned char, kScryptSaltBytes> salt{};
    std::array<unsigned char, kScryptHashBytes> derived{};
    if (RAND_bytes(salt.data(), static_cast<int>(salt.size())) != 1 ||
        EVP_PBE_scrypt(
            password.data(),
            password.size(),
            salt.data(),
            salt.size(),
            kScryptN,
            kScryptR,
            kScryptP,
            kScryptMaxMemory,
            derived.data(),
            derived.size()) != 1)
    {
        throw std::runtime_error("Unable to derive secure password hash");
    }
    return "scrypt$" + std::to_string(kScryptN) + "$" + std::to_string(kScryptR) + "$" +
           std::to_string(kScryptP) + "$" + toHex(salt.data(), salt.size()) + "$" +
           toHex(derived.data(), derived.size());
}

bool UserRepository::verifyScryptPassword(const std::string &encodedHash, const std::string &password)
{
    const auto parts = splitHash(encodedHash);
    if (parts.size() != 6 || parts[0] != "scrypt")
    {
        return false;
    }
    try
    {
        const auto n = std::stoull(parts[1]);
        const auto r = std::stoull(parts[2]);
        const auto p = std::stoull(parts[3]);
        if (n < 2 || n > (1ULL << 20U) || r < 1 || r > 64 || p < 1 || p > 16)
        {
            return false;
        }
        std::vector<unsigned char> salt;
        std::vector<unsigned char> expected;
        if (!fromHex(parts[4], salt) || !fromHex(parts[5], expected) ||
            salt.size() < 16 || expected.size() != kScryptHashBytes)
        {
            return false;
        }
        std::array<unsigned char, kScryptHashBytes> actual{};
        if (EVP_PBE_scrypt(
                password.data(),
                password.size(),
                salt.data(),
                salt.size(),
                n,
                r,
                p,
                kScryptMaxMemory,
                actual.data(),
                actual.size()) != 1)
        {
            return false;
        }
        return CRYPTO_memcmp(actual.data(), expected.data(), actual.size()) == 0;
    }
    catch (...)
    {
        return false;
    }
}

bool UserRepository::verifyPassword(const Json::Value &user, const std::string &password)
{
    const auto algo = user.get("password_algo", "sha256").asString();
    const auto storedHash = user.get("password_hash", "").asString();
    if (algo == "scrypt")
    {
        return verifyScryptPassword(storedHash, password);
    }
    if (algo == "sha256")
    {
        const auto candidate = drogon::utils::getSha256(password);
        const bool verified =
            storedHash.size() == candidate.size() &&
            CRYPTO_memcmp(storedHash.data(), candidate.data(), storedHash.size()) == 0;
        if (verified)
        {
            upgradeLegacyPasswordHash(
                user.get("id", user.get("user_id", "")).asString(),
                password,
                storedHash,
                algo);
        }
        return verified;
    }
    if (algo == "plain")
    {
        const auto legacyPassword = user.get("password", "").asString();
        const bool verified =
            legacyPassword.size() == password.size() &&
            CRYPTO_memcmp(legacyPassword.data(), password.data(), password.size()) == 0;
        if (verified)
        {
            upgradeLegacyPasswordHash(
                user.get("id", user.get("user_id", "")).asString(),
                password,
                legacyPassword,
                algo);
        }
        return verified;
    }
    return false;
}

void UserRepository::upgradeLegacyPasswordHash(const std::string &userId,
                                               const std::string &password,
                                               const std::string &expectedLegacyHash,
                                               const std::string &expectedLegacyAlgo)
{
    if (userId.empty())
    {
        return;
    }
    const auto upgradedHash = hashPassword(password);
    std::unique_lock lock(mutex_);
    auto usersJson = readUsersUnlocked();
    bool upgraded = false;
    Json::Value upgradedUser(Json::nullValue);
    forEachUserValue(usersJson, [&](Json::Value &entry) {
        if (upgraded || entry.get("id", entry.get("user_id", "")).asString() != userId)
        {
            return;
        }
        const auto currentAlgo = entry.get("password_algo", "sha256").asString();
        const auto currentSecret = currentAlgo == "plain"
            ? entry.get("password", "").asString()
            : entry.get("password_hash", "").asString();
        if (currentAlgo != expectedLegacyAlgo || currentSecret != expectedLegacyHash)
        {
            return;
        }
        entry["password_hash"] = upgradedHash;
        entry["password_algo"] = "scrypt";
        entry.removeMember("password");
        entry["password_migrated_at"] = common::nowIso8601();
        upgradedUser = normalizeUser(entry);
        upgraded = true;
    });
    if (upgraded)
    {
        wal_.append("password_hash_migrated", upgradedUser);
        writeUsersUnlocked(usersJson);
    }
}

Json::Value UserRepository::updateRoleTemplate(const std::string &roleId, const Json::Value &payload)
{
    const auto normalizedId = normalizeRoleId(roleId);
    if (normalizedId.empty() || normalizedId == "guest")
        throw common::AppException("ROLE_TEMPLATE_INVALID", "Role template cannot be modified", drogon::k422UnprocessableEntity);
    std::unique_lock lock(mutex_);
    auto rolesJson = readJsonFile(rolesFile_);
    if (!rolesJson.isObject() || !rolesJson.isMember(normalizedId))
        throw common::AppException("ROLE_NOT_FOUND", "Role template not found", drogon::k404NotFound);
    auto role = mergeRoleDefinition(defaultRolesMap()[normalizedId], rolesJson[normalizedId], normalizedId);
    if (payload.isMember("name")) role["name"] = payload.get("name", role.get("name", normalizedId)).asString();
    if (payload.isMember("description")) role["description"] = payload.get("description", role.get("description", "")).asString();
    if (payload.isMember("permissions"))
    {
        Json::Value permissions(Json::arrayValue);
        appendUniqueStrings(permissions, payload["permissions"]);
        if (normalizedId == "superAdmin")
        {
            permissions = Json::arrayValue;
            permissions.append("*");
        }
        role["permissions"] = permissions;
    }
    role["allow_organization_override"] = payload.get("allow_organization_override", role.get("allow_organization_override", normalizedId != "superAdmin")).asBool();
    role["updated_at"] = common::nowIso8601();
    rolesJson[normalizedId] = role;
    wal_.append("role_template_updated", role);
    writeJsonFileAtomic(rolesFile_, rolesJson);
    return role;
}

Json::Value UserRepository::updatePlatformAccess(const std::string &userId, const Json::Value &payload)
{
    std::unique_lock lock(mutex_);
    auto usersJson = readUsersUnlocked();
    Json::Value updated(Json::nullValue);
    forEachUserValue(usersJson, [&](Json::Value &entry) {
        if (!updated.isNull() || entry.get("id", entry.get("user_id", "")).asString() != userId) return;
        if (payload.isMember("roles")) entry["roles"] = normalizeRolesArray(payload["roles"]);
        if (payload.isMember("temporary_grants") && payload["temporary_grants"].isArray())
        {
            Json::Value grants(Json::arrayValue);
            for (const auto &source : payload["temporary_grants"])
            {
                if (!source.isObject()) continue;
                Json::Value grant(Json::objectValue);
                grant["id"] = source.get("id", common::generateOpaqueId("grant_")).asString();
                grant["role_id"] = normalizeRoleId(source.get("role_id", "").asString());
                grant["effect"] = source.get("effect", "allow").asString() == "deny" ? "deny" : "allow";
                grant["expires_at"] = source.get("expires_at", "").asString();
                grant["permissions"] = Json::arrayValue;
                appendUniqueStrings(grant["permissions"], source.get("permissions", Json::Value(Json::arrayValue)));
                if (!grant["role_id"].asString().empty() || !grant["permissions"].empty()) grants.append(grant);
            }
            entry["temporary_grants"] = grants;
        }
        entry["access_updated_at"] = common::nowIso8601();
        updated = normalizeUser(entry);
    });
    if (updated.isNull()) throw common::AppException("USER_NOT_FOUND", "User not found", drogon::k404NotFound);
    wal_.append("platform_access_updated", updated);
    writeUsersUnlocked(usersJson);
    return updated;
}

Json::Value UserRepository::platformAccess(const std::string &userId) const
{
    const auto user = findUserById(userId);
    if (user.isNull()) throw common::AppException("USER_NOT_FOUND", "User not found", drogon::k404NotFound);
    Json::Value out(Json::objectValue);
    out["user_id"] = userId;
    out["roles"] = user.get("roles", Json::Value(Json::arrayValue));
    out["temporary_grants"] = user.get("temporary_grants", Json::Value(Json::arrayValue));
    out["updated_at"] = user.get("access_updated_at", "");
    return out;
}

Json::Value UserRepository::effectivePlatformRoles(const std::string &userId) const
{
    const auto access = platformAccess(userId);
    Json::Value result = access["roles"];
    const auto now = common::nowIso8601();
    for (const auto &grant : access["temporary_grants"])
    {
        const auto expiresAt = grant.get("expires_at", "").asString();
        if (!expiresAt.empty() && expiresAt <= now) continue;
        const auto roleId = normalizeRoleId(grant.get("role_id", "").asString());
        if (!roleId.empty()) appendUniqueRole(result, roleId);
    }
    return result;
}

std::size_t UserRepository::countUsersWithRole(const std::string &roleId) const
{
    const auto usersJson = users();
    std::size_t count = 0;
    forEachUserValue(usersJson, [&](const Json::Value &entry) {
        for (const auto &role : entry.get("roles", Json::Value(Json::arrayValue)))
            if (role.asString() == roleId) { ++count; break; }
    });
    return count;
}

Json::Value UserRepository::updatePassword(const std::string &userId, const std::string &password)
{
    std::unique_lock lock(mutex_);
    auto usersJson = readUsersUnlocked();
    Json::Value result(Json::nullValue);
    forEachUserValue(usersJson, [&result, &userId, &password](Json::Value &entry) {
        if (!result.isNull())
        {
            return;
        }
        const auto user = normalizeUser(entry);
        if (user.get("id", "").asString() == userId)
        {
            entry["password_hash"] = hashPassword(password);
            entry["password_algo"] = "scrypt";
            entry["password_updated_at"] = common::nowIso8601();
            result = normalizeUser(entry);
        }
    });
    if (!result.isNull())
    {
        wal_.append("password_updated", result);
        writeUsersUnlocked(usersJson);
        return result;
    }
    throw common::AppException("USER_NOT_FOUND", "User not found: " + userId, drogon::k404NotFound);
}

    // Bind (or update) a verified phone number to a user.
Json::Value UserRepository::bindPhone(const std::string &userId, const std::string &phone)
{
    std::unique_lock lock(mutex_);
    auto usersJson = readUsersUnlocked();
    forEachUserValue(usersJson, [&phone, &userId](Json::Value &entry) {
        const auto user = normalizeUser(entry);
        if (user.get("phone", "").asString() == phone && user.get("id", "").asString() != userId)
        {
            throw common::AppException("PHONE_IN_USE", "Phone number is already bound to another user", drogon::k409Conflict);
        }
    });
    Json::Value result(Json::nullValue);
    forEachUserValue(usersJson, [&result, &userId, &phone](Json::Value &entry) {
        if (!result.isNull())
        {
            return;
        }
        const auto user = normalizeUser(entry);
        if (user.get("id", "").asString() == userId)
        {
            entry["phone"] = phone;
            entry["phone_verified"] = true;
            result = normalizeUser(entry);
        }
    });
    if (!result.isNull())
    {
        wal_.append("phone_bound", result);
        writeUsersUnlocked(usersJson);
        return result;
    }
    throw common::AppException("USER_NOT_FOUND", "User not found: " + userId, drogon::k404NotFound);
}

Json::Value UserRepository::bindEmail(const std::string &userId, const std::string &email)
{
    std::unique_lock lock(mutex_);
    auto usersJson = readUsersUnlocked();
    forEachUserValue(usersJson, [&email, &userId](Json::Value &entry) {
        const auto user = normalizeUser(entry);
        if (user.get("email", "").asString() == email && user.get("id", "").asString() != userId)
        {
            throw common::AppException("EMAIL_IN_USE", "Email is already bound to another user", drogon::k409Conflict);
        }
    });
    Json::Value result(Json::nullValue);
    forEachUserValue(usersJson, [&result, &userId, &email](Json::Value &entry) {
        if (!result.isNull())
        {
            return;
        }
        const auto user = normalizeUser(entry);
        if (user.get("id", "").asString() == userId)
        {
            entry["email"] = email;
            entry["email_verified"] = true;
            result = normalizeUser(entry);
        }
    });
    if (!result.isNull())
    {
        wal_.append("email_bound", result);
        writeUsersUnlocked(usersJson);
        return result;
    }
    throw common::AppException("USER_NOT_FOUND", "User not found: " + userId, drogon::k404NotFound);
}

Json::Value UserRepository::bindWechat(const std::string &userId,
                       const std::string &openid,
                       const std::string &nickname,
                       const std::string &avatarUrl,
                       const std::string &loginIdHint)
{
    if (openid.empty())
    {
        throw common::AppException("WECHAT_OPENID_REQUIRED", "WeChat openid is required", drogon::k422UnprocessableEntity);
    }

    std::unique_lock lock(mutex_);
    auto usersJson = readUsersUnlocked();
    forEachUserValue(usersJson, [&openid, &userId](Json::Value &entry) {
        const auto user = normalizeUser(entry);
        if (user.get("wechat_openid", "").asString() == openid && user.get("id", "").asString() != userId)
        {
            throw common::AppException("WECHAT_ALREADY_BOUND", "This WeChat account is already bound to another user", drogon::k409Conflict);
        }
    });

    Json::Value result(Json::nullValue);
    forEachUserValue(usersJson, [&result, &userId, &openid, &nickname, &avatarUrl, &loginIdHint](Json::Value &entry) {
        if (!result.isNull())
        {
            return;
        }
        const auto user = normalizeUser(entry);
        if (user.get("id", "").asString() == userId)
        {
            entry["wechat_openid"] = openid;
            entry["wechat_bound_at"] = common::nowIso8601();
            if (!nickname.empty())
            {
                entry["wechat_nickname"] = nickname;
            }
            if (!avatarUrl.empty())
            {
                entry["wechat_avatar"] = avatarUrl;
            }
            if (!loginIdHint.empty())
            {
                entry["dev_login_id"] = loginIdHint;
            }
            result = normalizeUser(entry);
        }
    });
    if (!result.isNull())
    {
        wal_.append("wechat_bound", result);
        writeUsersUnlocked(usersJson);
        return result;
    }
    throw common::AppException("USER_NOT_FOUND", "User not found: " + userId, drogon::k404NotFound);
}

Json::Value UserRepository::bindWechatFromUserToPhoneOwner(const std::string &sourceUserId, const std::string &phone)
{
    std::unique_lock lock(mutex_);
    auto usersJson = readUsersUnlocked();

    Json::Value source(Json::nullValue);
    Json::Value target(Json::nullValue);
    forEachUserValue(usersJson, [&source, &target, &sourceUserId, &phone](const Json::Value &entry) {
        const auto user = normalizeUser(entry);
        if (user.get("id", "").asString() == sourceUserId)
        {
            source = user;
        }
        if (user.get("phone", "").asString() == phone)
        {
            target = user;
        }
    });

    if (source.isNull())
    {
        throw common::AppException("USER_NOT_FOUND", "User not found: " + sourceUserId, drogon::k404NotFound);
    }
    if (target.isNull())
    {
        throw common::AppException("PHONE_NOT_FOUND", "Phone owner not found", drogon::k404NotFound);
    }
    if (target.get("id", "").asString() == sourceUserId)
    {
        return target;
    }

    const auto openid = source.get("wechat_openid", "").asString();
    if (openid.empty())
    {
        throw common::AppException("WECHAT_NOT_BOUND", "Source user has no WeChat identity", drogon::k409Conflict);
    }
    const auto targetOpenid = target.get("wechat_openid", "").asString();
    if (!targetOpenid.empty() && targetOpenid != openid)
    {
        throw common::AppException("WECHAT_ALREADY_BOUND", "The phone owner already has another WeChat account", drogon::k409Conflict);
    }

    Json::Value result(Json::nullValue);
    forEachUserValue(usersJson, [&result, &source, &target, &sourceUserId, &phone, &openid](Json::Value &entry) {
        const auto user = normalizeUser(entry);
        if (user.get("id", "").asString() == target.get("id", "").asString())
        {
            entry["wechat_openid"] = openid;
            entry["wechat_bound_at"] = common::nowIso8601();
            entry["wechat_nickname"] = source.get("wechat_nickname", "").asString();
            entry["wechat_avatar"] = source.get("wechat_avatar", "").asString();
            const auto loginIdHint = source.get("dev_login_id", "").asString();
            if (!loginIdHint.empty() && entry.get("dev_login_id", "").asString().empty())
            {
                entry["dev_login_id"] = loginIdHint;
            }
            result = normalizeUser(entry);
        }
        else if (user.get("id", "").asString() == sourceUserId)
        {
            entry["wechat_openid"] = "";
            entry["wechat_bound_at"] = "";
            entry["wechat_nickname"] = "";
            entry["wechat_avatar"] = "";
            entry["status"] = "merged";
            entry["merged_into_user_id"] = target.get("id", "").asString();
            entry["merged_reason"] = "wechat_phone_owner";
            entry["merged_phone"] = phone;
            entry["merged_at"] = common::nowIso8601();
        }
    });

    if (!result.isNull())
    {
        wal_.append("wechat_merged_to_phone_owner", result);
        writeUsersUnlocked(usersJson);
        return result;
    }
    throw common::AppException("USER_NOT_FOUND", "Phone owner not found", drogon::k404NotFound);
}

Json::Value UserRepository::deactivateUser(const std::string &userId, const std::string &reason)
{
    std::unique_lock lock(mutex_);
    auto usersJson = readUsersUnlocked();
    Json::Value result(Json::nullValue);
    forEachUserValue(usersJson, [&result, &userId, &reason](Json::Value &entry) {
        if (!result.isNull())
        {
            return;
        }
        const auto user = normalizeUser(entry);
        if (user.get("id", "").asString() == userId)
        {
            entry["status"] = "disabled";
            entry["deactivated_at"] = common::nowIso8601();
            entry["deactivation_reason"] = reason.empty() ? "user_requested" : reason;
            result = normalizeUser(entry);
        }
    });
    if (!result.isNull())
    {
        wal_.append("user_deactivated", result);
        writeUsersUnlocked(usersJson);
        return result;
    }
    throw common::AppException("USER_NOT_FOUND", "User not found: " + userId, drogon::k404NotFound);
}

Json::Value UserRepository::findUserByPhone(const std::string &phone) const
{
    std::shared_lock lock(mutex_);
    auto usersJson = readUsersUnlocked();
    Json::Value result(Json::nullValue);
    forEachUserValue(usersJson, [&result, &phone](const Json::Value &entry) {
        if (!result.isNull())
        {
            return;
        }
        const auto user = normalizeUser(entry);
        if (user.get("phone", "").asString() == phone)
        {
            result = user;
        }
    });
    return result;
}

Json::Value UserRepository::createPhoneUser(const std::string &phone, const std::string &referralCode)
{
    std::unique_lock lock(mutex_);
    auto usersJson = readUsersUnlocked();
    Json::Value existing(Json::nullValue);
    forEachUserValue(usersJson, [&existing, &phone](const Json::Value &entry) {
        if (!existing.isNull())
        {
            return;
        }
        const auto user = normalizeUser(entry);
        if (user.get("phone", "").asString() == phone)
        {
            existing = user;
        }
    });
    if (!existing.isNull())
    {
        return existing;
    }

    Json::Value referrer(Json::nullValue);
    const auto normalizedReferralCode = normalizeReferralCode(referralCode);
    if (!normalizedReferralCode.empty())
    {
        referrer = findUserByReferralCodeUnlocked(usersJson, normalizedReferralCode);
        if (referrer.isNull())
        {
            throw common::AppException("REFERRAL_CODE_INVALID", "Referral code is invalid", drogon::k422UnprocessableEntity);
        }
    }

    const auto usernameBase = "phone_" + sanitizePhone(phone);
    const auto username = uniqueUsernameForBase(usersJson, usernameBase);
    const auto userId = generateUserId();
    const auto key = userId;
    usersJson[key]["id"] = userId;
    usersJson[key]["user_id"] = userId;
    usersJson[key]["username"] = username;
    usersJson[key]["member_no"] = nextPersonalMemberNo(usersJson);
    usersJson[key]["password_hash"] = "";
    usersJson[key]["password_algo"] = "phone";
    usersJson[key]["email"] = "";
    usersJson[key]["email_verified"] = false;
    usersJson[key]["phone"] = phone;
    usersJson[key]["phone_verified"] = true;
    usersJson[key]["status"] = "active";
    usersJson[key]["scope_type"] = "personal";
    usersJson[key]["scope_id"] = userId;
    usersJson[key]["organization_type"] = "";
    usersJson[key]["roles"] = Json::arrayValue;
    usersJson[key]["roles"].append("student");
    usersJson[key]["created_at"] = common::nowIso8601();
    usersJson[key]["referral_code"] = generateReferralCode(usersJson, username);
    usersJson[key]["referred_by_user_id"] = referrer.isNull() ? "" : referrer.get("id", referrer.get("user_id", "")).asString();
    usersJson[key]["referred_by_code"] = referrer.isNull() ? "" : normalizedReferralCode;
    usersJson[key]["referral_bound_at"] = referrer.isNull() ? "" : common::nowIso8601();
    usersJson[key]["referral_reward_status"] = referrer.isNull() ? "none" : "pending";

    wal_.append("phone_user_created", usersJson[key]);
    writeUsersUnlocked(usersJson);
    return normalizeUser(usersJson[key]);
}

Json::Value UserRepository::findUserByReferralCode(const std::string &referralCode) const
{
    const auto normalizedCode = normalizeReferralCode(referralCode);
    if (normalizedCode.empty())
    {
        return Json::Value(Json::nullValue);
    }

    std::shared_lock lock(mutex_);
    return findUserByReferralCodeUnlocked(readUsersUnlocked(), normalizedCode);
}

Json::Value UserRepository::claimReferral(const std::string &userId, const std::string &referralCode)
{
    const auto normalizedCode = normalizeReferralCode(referralCode);
    if (normalizedCode.empty())
    {
        throw common::AppException("REFERRAL_CODE_REQUIRED", "Referral code is required", drogon::k422UnprocessableEntity);
    }

    std::unique_lock lock(mutex_);
    auto usersJson = readUsersUnlocked();
    const auto referrer = findUserByReferralCodeUnlocked(usersJson, normalizedCode);
    if (referrer.isNull())
    {
        throw common::AppException("REFERRAL_CODE_INVALID", "Referral code is invalid", drogon::k422UnprocessableEntity);
    }

    const auto referrerUserId = referrer.get("id", referrer.get("user_id", "")).asString();
    Json::Value updated(Json::nullValue);
    forEachUserValue(usersJson, [&updated, &userId, &normalizedCode, &referrerUserId](Json::Value &entry) {
        if (!updated.isNull())
        {
            return;
        }
        const auto user = normalizeUser(entry);
        if (user.get("id", "").asString() != userId)
        {
            return;
        }
        if (!user.get("referred_by_user_id", "").asString().empty())
        {
            throw common::AppException("REFERRAL_ALREADY_CLAIMED", "Referral is already bound for this account", drogon::k409Conflict);
        }
        if (user.get("referral_code", "").asString() == normalizedCode || userId == referrerUserId)
        {
            throw common::AppException("REFERRAL_SELF_NOT_ALLOWED", "You cannot use your own referral code", drogon::k409Conflict);
        }
        entry["referred_by_user_id"] = referrerUserId;
        entry["referred_by_code"] = normalizedCode;
        entry["referral_bound_at"] = common::nowIso8601();
        entry["referral_reward_status"] = "pending";
        updated = normalizeUser(entry);
    });

    if (updated.isNull())
    {
        throw common::AppException("USER_NOT_FOUND", "User not found", drogon::k404NotFound);
    }

    wal_.append("referral_claimed", updated);
    writeUsersUnlocked(usersJson);
    return updated;
}

bool UserRepository::grantReferralRewardIfPending(const std::string &userId,
                                  const std::string &trigger,
                                  int rewardCredits,
                                  const std::string &rewardRecipientUserId)
{
    std::unique_lock lock(mutex_);
    auto usersJson = readUsersUnlocked();
    Json::Value updated(Json::nullValue);
    bool changed = false;
    forEachUserValue(usersJson, [&updated, &userId, &trigger, &rewardCredits, &rewardRecipientUserId, &changed](Json::Value &entry) {
        if (!updated.isNull())
        {
            return;
        }
        const auto user = normalizeUser(entry);
        if (user.get("id", "").asString() != userId)
        {
            return;
        }

        updated = user;
        if (user.get("referred_by_user_id", "").asString().empty() ||
            user.get("referral_reward_status", "none").asString() != "pending")
        {
            return;
        }

        entry["referral_reward_status"] = "granted";
        entry["referral_reward_granted_at"] = common::nowIso8601();
        entry["referral_reward_trigger"] = trigger;
        entry["referral_reward_credit_amount"] = rewardCredits;
        entry["referral_reward_credit_recipient_user_id"] = rewardRecipientUserId;
        updated = normalizeUser(entry);
        changed = true;
    });

    if (updated.isNull())
    {
        throw common::AppException("USER_NOT_FOUND", "User not found", drogon::k404NotFound);
    }

    if (!changed)
    {
        return false;
    }

    wal_.append("referral_reward_granted", updated);
    writeUsersUnlocked(usersJson);
    return true;
}

    // Find user by WeChat openid (returns null if not found).
Json::Value UserRepository::findUserByOpenid(const std::string &openid) const
{
    std::shared_lock lock(mutex_);
    auto usersJson = readUsersUnlocked();
    Json::Value result(Json::nullValue);
    forEachUserValue(usersJson, [&result, &openid](const Json::Value &entry) {
        if (!result.isNull())
        {
            return;
        }
        const auto user = normalizeUser(entry);
        if (user.get("wechat_openid", "").asString() == openid)
        {
            result = user;
        }
    });
    return result;
}

    // Create or update a user by WeChat openid.
Json::Value UserRepository::upsertWechatUser(const std::string &openid,
                            const std::string &nickname,
                            const std::string &avatarUrl,
                            const std::string &loginIdHint)
{
    std::unique_lock lock(mutex_);
    auto usersJson = readUsersUnlocked();

    // Search for existing user with this openid
    Json::Value updated(Json::nullValue);
    forEachUserValue(usersJson, [&updated, &openid, &nickname, &avatarUrl, &loginIdHint, this, &usersJson](Json::Value &entry) {
        if (!updated.isNull())
        {
            return;
        }
        const auto user = normalizeUser(entry);
        if (user.get("wechat_openid", "").asString() != openid)
        {
            return;
        }
        if (!nickname.empty())
        {
            entry["wechat_nickname"] = nickname;
        }
        if (!avatarUrl.empty())
        {
            entry["wechat_avatar"] = avatarUrl;
        }
        if (!loginIdHint.empty())
        {
            entry["dev_login_id"] = loginIdHint;
            entry["roles"] = developmentRolesForLoginId(loginIdHint);
        }
        else if (entry["roles"].empty())
        {
            entry["roles"] = Json::arrayValue;
            entry["roles"].append("student");
        }
        entry["status"] = normalizeStatus(user.get("status", "active").asString());
        if (normalizeUser(entry).get("member_no", "").asString().empty())
        {
            entry["member_no"] = nextPersonalMemberNo(usersJson);
        }
        updated = normalizeUser(entry);
    });
    if (!updated.isNull())
    {
        wal_.append("wechat_user_updated", updated);
        writeUsersUnlocked(usersJson);
        return updated;
    }

    // Create new user
    const auto userId = generateUserId();
    const auto usernameBase = loginIdHint.empty() ? ("wx_" + openid.substr(0, std::min(openid.size(), static_cast<size_t>(10)))) : loginIdHint;
    const auto username = uniqueUsernameForBase(usersJson, usernameBase);
    const auto key = userId;
    usersJson[key]["id"] = userId;
    usersJson[key]["user_id"] = userId;
    usersJson[key]["username"] = username;
    usersJson[key]["member_no"] = nextPersonalMemberNo(usersJson);
    usersJson[key]["password_hash"] = "";
    usersJson[key]["password_algo"] = "wechat";
    usersJson[key]["email"] = "";
    usersJson[key]["email_verified"] = false;
    usersJson[key]["phone"] = "";
    usersJson[key]["phone_verified"] = false;
    usersJson[key]["wechat_openid"] = openid;
    usersJson[key]["wechat_nickname"] = nickname;
    usersJson[key]["wechat_avatar"] = avatarUrl;
    usersJson[key]["dev_login_id"] = loginIdHint;
    usersJson[key]["status"] = "active";
    usersJson[key]["scope_type"] = "personal";
    usersJson[key]["scope_id"] = userId;
    usersJson[key]["organization_type"] = "";
    usersJson[key]["roles"] = loginIdHint.empty() ? normalizeRolesArray(Json::Value(Json::arrayValue)) : developmentRolesForLoginId(loginIdHint);
    usersJson[key]["created_at"] = common::nowIso8601();

    wal_.append("wechat_user_created", usersJson[key]);
    writeUsersUnlocked(usersJson);
    return normalizeUser(usersJson[key]);
}

Json::Value UserRepository::defaultRolesMap()
{
    Json::Value roles(Json::objectValue);
    roles["guest"]["id"] = "guest";
    roles["guest"]["name"] = "访客";
    roles["guest"]["description"] = "未登录状态，可浏览公开内容和进入登录注册。";
    roles["guest"]["permissions"] = Json::arrayValue;
    roles["guest"]["permissions"].append("exam.public.view");

    roles["student"]["id"] = "student";
    roles["student"]["name"] = "学员";
    roles["student"]["description"] = "个人用户或机构学员，可做题、提交作业、查看自己的学习报告。";
    roles["student"]["permissions"] = Json::arrayValue;
    roles["student"]["permissions"].append("exam.practice");
    roles["student"]["permissions"].append("answer.submit");
    roles["student"]["permissions"].append("analysis.view");
    roles["student"]["permissions"].append("assignment.submit");
    roles["student"]["permissions"].append("report.view.self");
    roles["student"]["permissions"].append("learning_record.view.self");

    roles["assistant"]["id"] = "assistant";
    roles["assistant"]["name"] = "教学运营";
    roles["assistant"]["description"] = "助教、班主任、教务或课程顾问的基础角色，通过权限模板区分职责。";
    roles["assistant"]["permissions"] = Json::arrayValue;
    roles["assistant"]["permissions"].append("assignment.review");
    roles["assistant"]["permissions"].append("assignment.remind");
    roles["assistant"]["permissions"].append("student.profile.view");
    roles["assistant"]["permissions"].append("student.profile.edit");
    roles["assistant"]["permissions"].append("student.followup.edit");
    roles["assistant"]["permissions"].append("learning_record.comment");
    roles["assistant"]["permissions"].append("course_package.view");

    roles["teacher"]["id"] = "teacher";
    roles["teacher"]["name"] = "老师";
    roles["teacher"]["description"] = "负责学习组教学、作业、批改、课后反馈和备课。";
    roles["teacher"]["permissions"] = Json::arrayValue;
    roles["teacher"]["permissions"].append("assignment.create");
    roles["teacher"]["permissions"].append("assignment.review");
    roles["teacher"]["permissions"].append("assignment.remind");
    roles["teacher"]["permissions"].append("gradebook.view");
    roles["teacher"]["permissions"].append("student.profile.view");
    roles["teacher"]["permissions"].append("student.profile.edit");
    roles["teacher"]["permissions"].append("lesson_prep.create");
    roles["teacher"]["permissions"].append("lesson_prep.export");
    roles["teacher"]["permissions"].append("learning_record.feedback.edit");

    roles["orgAdmin"]["id"] = "orgAdmin";
    roles["orgAdmin"]["name"] = "机构管理员";
    roles["orgAdmin"]["description"] = "管理机构成员、学习组、课程包、套餐席位、机构看板和审计。";
    roles["orgAdmin"]["permissions"] = Json::arrayValue;
    roles["orgAdmin"]["permissions"].append("organization.member.manage");
    roles["orgAdmin"]["permissions"].append("learning_group.manage");
    roles["orgAdmin"]["permissions"].append("course_package.manage");
    roles["orgAdmin"]["permissions"].append("lesson.booking.manage");
    roles["orgAdmin"]["permissions"].append("organization.dashboard.view");
    roles["orgAdmin"]["permissions"].append("organization.billing.manage");
    roles["orgAdmin"]["permissions"].append("audit.view");

    roles["contentAdmin"]["id"] = "contentAdmin";
    roles["contentAdmin"]["name"] = "内容管理员";
    roles["contentAdmin"]["description"] = "维护平台试卷、音频、图片、答案、解析和发布质量。";
    roles["contentAdmin"]["permissions"] = Json::arrayValue;
    roles["contentAdmin"]["permissions"].append("content.exam.edit");
    roles["contentAdmin"]["permissions"].append("content.audio.manage");
    roles["contentAdmin"]["permissions"].append("content.image.manage");
    roles["contentAdmin"]["permissions"].append("content.answer.edit");
    roles["contentAdmin"]["permissions"].append("content.analysis.edit");
    roles["contentAdmin"]["permissions"].append("content.publish");
    roles["contentAdmin"]["permissions"].append("content.audit.view");

    roles["superAdmin"]["id"] = "superAdmin";
    roles["superAdmin"]["name"] = "平台超级管理员";
    roles["superAdmin"]["description"] = "平台最高权限，仅用于平台运营和技术管理。";
    roles["superAdmin"]["permissions"] = Json::arrayValue;
    roles["superAdmin"]["permissions"].append("*");
    return roles;
}

Json::Value UserRepository::normalizeUser(const Json::Value &input)
{
    Json::Value user = input.isObject() ? input : Json::Value(Json::objectValue);
    const auto userId = user.get("id", user.get("user_id", "")).asString();
    user["id"] = userId;
    user["user_id"] = userId;
    user["username"] = user.get("username", userId).asString();
    user["display_name"] = user.get("display_name", user.get("displayName", "")).asString();
    user["member_no"] = user.get("member_no", user.get("student_no", "")).asString();
    user["memberNo"] = user["member_no"].asString();
    user["student_no"] = user.get("student_no", "").asString();
    user["studentNo"] = user["student_no"].asString();
    user["employee_no"] = user.get("employee_no", "").asString();
    user["employeeNo"] = user["employee_no"].asString();
    user["dev_login_id"] = user.get("dev_login_id", "").asString();
    user["email"] = user.get("email", "").asString();
    user["email_verified"] = user.get("email_verified", false).asBool();
    user["avatar"] = user.get("avatar", user.get("avatar_url", "")).asString();
    user["avatar_url"] = user.get("avatar_url", user["avatar"].asString()).asString();
    user["password_hash"] = user.get("password_hash", user.get("passwordHash", "")).asString();
    user["password_algo"] = user.get("password_algo", user["password_hash"].asString().empty() ? "sha256" : "sha256").asString();
    const auto passwordAlgo = user["password_algo"].asString();
    user["has_password"] =
        (passwordAlgo == "scrypt" || passwordAlgo == "sha256" || passwordAlgo == "plain") &&
        (!user["password_hash"].asString().empty() || !user.get("password", "").asString().empty());
    user["hasPassword"] = user["has_password"].asBool();
    user["phone"] = user.get("phone", "").asString();
    user["phone_verified"] = user.get("phone_verified", false).asBool();
    user["wechat_openid"] = user.get("wechat_openid", "").asString();
    user["wechat_bound"] = !user["wechat_openid"].asString().empty();
    user["wechatBound"] = user["wechat_bound"].asBool();
    user["wechat_nickname"] = user.get("wechat_nickname", "").asString();
    user["wechat_avatar"] = user.get("wechat_avatar", "").asString();
    user["wechat_bound_at"] = user.get("wechat_bound_at", "").asString();
    user["status"] = normalizeStatus(user.get("status", "active").asString());
    user["scope_type"] = normalizeScopeType(user.get("scope_type", "personal").asString());
    user["scope_id"] = user.get("scope_id", userId).asString();
    user["organization_type"] = normalizeOrganizationType(
        user.get("organization_type", user["scope_type"].asString() == "organization" ? "business" : "").asString(),
        user["scope_type"].asString());
    user["created_at"] = user.get("created_at", user.get("createdAt", common::nowIso8601())).asString();
    user["referral_code"] = normalizeReferralCode(user.get("referral_code", user.get("referralCode", "")).asString());
    user["referralCode"] = user["referral_code"].asString();
    user["referred_by_user_id"] = user.get("referred_by_user_id", user.get("referredByUserId", "")).asString();
    user["referredByUserId"] = user["referred_by_user_id"].asString();
    user["referred_by_code"] = normalizeReferralCode(user.get("referred_by_code", user.get("referredByCode", "")).asString());
    user["referredByCode"] = user["referred_by_code"].asString();
    user["referral_bound_at"] = user.get("referral_bound_at", user.get("referralBoundAt", "")).asString();
    user["referralBoundAt"] = user["referral_bound_at"].asString();
    user["referral_reward_status"] = normalizeReferralRewardStatus(user.get("referral_reward_status", user.get("referralRewardStatus", user["referred_by_user_id"].asString().empty() ? "none" : "pending")).asString());
    user["referralRewardStatus"] = user["referral_reward_status"].asString();
    user["referral_reward_granted_at"] = user.get("referral_reward_granted_at", user.get("referralRewardGrantedAt", "")).asString();
    user["referralRewardGrantedAt"] = user["referral_reward_granted_at"].asString();
    user["referral_reward_trigger"] = user.get("referral_reward_trigger", user.get("referralRewardTrigger", "")).asString();
    user["referralRewardTrigger"] = user["referral_reward_trigger"].asString();
    user["referral_reward_credit_amount"] = user.get("referral_reward_credit_amount", user.get("referralRewardCreditAmount", 0)).asInt();
    user["referralRewardCreditAmount"] = user["referral_reward_credit_amount"].asInt();
    user["referral_reward_credit_recipient_user_id"] = user.get("referral_reward_credit_recipient_user_id", user.get("referralRewardCreditRecipientUserId", "")).asString();
    user["referralRewardCreditRecipientUserId"] = user["referral_reward_credit_recipient_user_id"].asString();
    if (user["referral_code"].asString().empty())
    {
        user["referral_code"] = legacyReferralCode(userId, user.get("username", "").asString());
        user["referralCode"] = user["referral_code"].asString();
    }
    user["roles"] = normalizeRolesArray(user.isMember("roles") ? user["roles"] : user["roleIds"]);
    return user;
}

std::string UserRepository::normalizeReferralCode(std::string referralCode)
{
    std::string normalized;
    normalized.reserve(referralCode.size());
    for (const auto ch : referralCode)
    {
        if (std::isalnum(static_cast<unsigned char>(ch)))
        {
            normalized.push_back(static_cast<char>(std::toupper(static_cast<unsigned char>(ch))));
        }
    }
    return normalized;
}

std::string UserRepository::normalizeReferralRewardStatus(const std::string &status)
{
    if (status == "none" || status == "pending" || status == "granted" || status == "rejected")
    {
        return status;
    }
    return "none";
}

Json::Value UserRepository::findUserByReferralCodeUnlocked(const Json::Value &usersJson, const std::string &referralCode)
{
    Json::Value result(Json::nullValue);
    forEachUserValue(usersJson, [&result, &referralCode](const Json::Value &entry) {
        if (!result.isNull())
        {
            return;
        }
        const auto user = normalizeUser(entry);
        if (user.get("referral_code", "").asString() == referralCode)
        {
            result = user;
        }
    });
    return result;
}

std::string UserRepository::generateReferralCode(const Json::Value &usersJson, const std::string &seed)
{
    const auto prefix = buildReferralPrefix(seed);
    std::random_device rd;
    std::mt19937 generator(rd());
    std::uniform_int_distribution<int> distribution(0, 35);
    constexpr char alphabet[] = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    for (int attempt = 0; attempt < 32; ++attempt)
    {
        std::string code = prefix;
        while (code.size() < 10)
        {
            code.push_back(alphabet[distribution(generator)]);
        }
        if (findUserByReferralCodeUnlocked(usersJson, code).isNull())
        {
            return code;
        }
    }
    return "REF" + common::generateOpaqueId("").substr(0, 8);
}

std::string UserRepository::buildReferralPrefix(const std::string &seed)
{
    auto normalizedSeed = normalizeReferralCode(seed);
    if (normalizedSeed.size() > 6)
    {
        normalizedSeed = normalizedSeed.substr(0, 6);
    }
    if (normalizedSeed.size() < 3)
    {
        normalizedSeed = "REF";
    }
    return normalizedSeed;
}

std::string UserRepository::legacyReferralCode(const std::string &userId, const std::string &username)
{
    auto prefix = buildReferralPrefix(username);
    auto suffix = normalizeReferralCode(userId);
    if (suffix.size() > 10 - prefix.size())
    {
        suffix = suffix.substr(suffix.size() - (10 - prefix.size()));
    }
    while (suffix.size() < 10 - prefix.size())
    {
        suffix.insert(suffix.begin(), '0');
    }
    return prefix + suffix;
}

Json::Value UserRepository::mergeRoleDefinition(const Json::Value &baseline, const Json::Value &incoming, const std::string &roleId)
{
    Json::Value merged = baseline.isObject() ? baseline : Json::Value(Json::objectValue);
    merged["id"] = roleId;
    merged["name"] = incoming.get("name", merged.get("name", roleId).asString()).asString();
    merged["description"] = incoming.get("description", merged.get("description", "").asString()).asString();

    Json::Value permissions(Json::arrayValue);
    appendUniqueStrings(permissions, merged["permissions"]);
    appendUniqueStrings(permissions, incoming["permissions"]);
    appendUniqueStrings(permissions, incoming["privileges"]);
    merged["permissions"] = permissions;
    return merged;
}

Json::Value UserRepository::normalizeRolesArray(const Json::Value &roles)
{
    Json::Value normalized(Json::arrayValue);

    if (roles.isString())
    {
        appendUniqueRole(normalized, normalizeRoleId(roles.asString()));
    }
    else if (roles.isArray())
    {
        for (const auto &role : roles)
        {
            appendUniqueRole(normalized, normalizeRoleId(role.asString()));
        }
    }

    if (normalized.empty())
    {
        normalized.append("student");
    }
    return normalized;
}

void UserRepository::appendUniqueStrings(Json::Value &target, const Json::Value &values)
{
    if (!values.isArray())
    {
        return;
    }
    for (const auto &value : values)
    {
        const auto item = value.asString();
        if (item.empty())
        {
            continue;
        }
        bool exists = false;
        for (const auto &current : target)
        {
            if (current.asString() == item)
            {
                exists = true;
                break;
            }
        }
        if (!exists)
        {
            target.append(item);
        }
    }
}

void UserRepository::appendUniqueRole(Json::Value &target, const std::string &role)
{
    if (role.empty())
    {
        return;
    }
    for (const auto &item : target)
    {
        if (item.asString() == role)
        {
            return;
        }
    }
    target.append(role);
}

std::string UserRepository::normalizeRoleId(const std::string &roleId)
{
    if (roleId == "user")
    {
        return "student";
    }
    if (roleId == "admin")
    {
        return "orgAdmin";
    }
    if (roleId == "guest" || roleId == "student" || roleId == "assistant" || roleId == "teacher" ||
        roleId == "orgAdmin" || roleId == "contentAdmin" || roleId == "superAdmin")
    {
        return roleId;
    }
    return "";
}

std::string UserRepository::normalizeStatus(const std::string &status)
{
    if (status == "active" || status == "disabled" || status == "pending")
    {
        return status;
    }
    return "active";
}

std::string UserRepository::normalizeScopeType(const std::string &scopeType)
{
    return scopeType == "organization" ? "organization" : "personal";
}

std::string UserRepository::normalizeOrganizationType(const std::string &organizationType, const std::string &scopeType)
{
    if (scopeType != "organization")
    {
        return "";
    }
    if (organizationType == "business" || organizationType == "school")
    {
        return organizationType;
    }
    return "business";
}

bool UserRepository::containsUsername(const Json::Value &usersJson, const std::string &username)
{
    bool found = false;
    forEachUserValue(usersJson, [&found, &username](const Json::Value &entry) {
        if (found)
        {
            return;
        }
        if (normalizeUser(entry).get("username", "").asString() == username)
        {
            found = true;
        }
    });
    return found;
}

bool UserRepository::matchesLoginId(const Json::Value &user, const std::string &loginId)
{
    return user.get("username", "").asString() == loginId ||
           user.get("id", "").asString() == loginId ||
           user.get("user_id", "").asString() == loginId ||
         user.get("member_no", "").asString() == loginId ||
           user.get("student_no", "").asString() == loginId ||
         user.get("employee_no", "").asString() == loginId ||
           user.get("phone", "").asString() == loginId ||
           user.get("dev_login_id", "").asString() == loginId;
}

std::string UserRepository::uniqueStorageKey(const Json::Value &usersJson, const std::string &base)
{
    std::string key = base;
    int suffix = 1;
    while (usersJson.isMember(key))
    {
        key = base + "_" + std::to_string(suffix++);
    }
    return key;
}

std::string UserRepository::uniqueUsernameForBase(const Json::Value &usersJson, const std::string &base)
{
    std::string username = base;
    int suffix = 1;
    while (containsUsername(usersJson, username))
    {
        username = base + "_" + std::to_string(suffix++);
    }
    return username;
}

std::string UserRepository::nextPersonalMemberNo(const Json::Value &usersJson)
{
    int maxSerial = 0;
    forEachUserValue(usersJson, [&maxSerial](const Json::Value &entry) {
        maxSerial = (std::max)(maxSerial, extractPrefixedSerial(normalizeUser(entry).get("member_no", "").asString(), "MEM-"));
    });
    return "MEM-" + padSerial(maxSerial + 1, 6);
}

Json::Value UserRepository::developmentRolesForLoginId(const std::string &loginId)
{
    Json::Value roles(Json::arrayValue);
    if (loginId.rfind("superadmin_", 0) == 0 || loginId.rfind("super_", 0) == 0)
    {
        roles.append("superAdmin");
        return roles;
    }
    if (loginId.rfind("contentadmin_", 0) == 0 || loginId.rfind("content_", 0) == 0)
    {
        roles.append("contentAdmin");
        return roles;
    }
    if (loginId.rfind("orgadmin_", 0) == 0 || loginId.rfind("org_admin_", 0) == 0 || loginId.rfind("admin_", 0) == 0)
    {
        roles.append("orgAdmin");
        return roles;
    }
    if (loginId.rfind("teacher_", 0) == 0)
    {
        roles.append("teacher");
        return roles;
    }
    if (loginId.rfind("assistant_", 0) == 0 || loginId.rfind("academic_", 0) == 0 || loginId.rfind("consultant_", 0) == 0)
    {
        roles.append("assistant");
        return roles;
    }
    roles.append("student");
    return roles;
}

std::string UserRepository::padSerial(int value, int width)
{
    auto text = std::to_string(value);
    if (static_cast<int>(text.size()) >= width)
    {
        return text;
    }
    return std::string(static_cast<size_t>(width - text.size()), '0') + text;
}

std::string UserRepository::sanitizeIdentifier(const std::string &value)
{
    std::string out;
    for (const auto ch : value)
    {
        if ((ch >= '0' && ch <= '9') ||
            (ch >= 'a' && ch <= 'z') ||
            (ch >= 'A' && ch <= 'Z') ||
            ch == '_' || ch == '-')
        {
            out.push_back(ch);
        }
    }
    return out.empty() ? std::string("test") : out;
}

std::string UserRepository::sanitizePhone(const std::string &phone)
{
    std::string out;
    for (const auto c : phone)
    {
        if (c >= '0' && c <= '9')
        {
            out.push_back(c);
        }
    }
    return out.empty() ? std::string("user") : out;
}

int UserRepository::extractPrefixedSerial(const std::string &value, const std::string &prefix)
{
    if (value.rfind(prefix, 0) != 0)
    {
        return 0;
    }

    const auto serial = value.substr(prefix.size());
    if (serial.empty())
    {
        return 0;
    }
    for (const auto ch : serial)
    {
        if (ch < '0' || ch > '9')
        {
            return 0;
        }
    }
    return std::stoi(serial);
}

std::string UserRepository::generateUserId()
{
    return common::generateOpaqueId("usr_");
}

}  // namespace infrastructure::storage
