// Auto-generated by tools/sink_user_repository.ps1 from UserRepository.h
#include "UserRepository.h"

#include <algorithm>
#include <cctype>
#include <chrono>
#include <random>
#include <string>

#include <drogon/HttpTypes.h>

#include "JsonIo.h"
#include "common/AppException.h"
#include "common/IdGenerator.h"
#include "common/TimeUtils.h"

namespace infrastructure::storage
{

UserRepository::UserRepository(std::filesystem::path userRootDir)
    : userRootDir_(std::move(userRootDir)),
      usersFile_(userRootDir_ / "users.json"),
      rolesFile_(userRootDir_ / "roles.json"),
      wal_(userRootDir_ / "_users.wal.log", userRootDir_ / "_users.wal.snapshot.json")
{
    std::filesystem::create_directories(userRootDir_);
    recoveredEvents_ = wal_.recover().size();
    ensureBaseline();
}

void UserRepository::ensureBaseline()
{
    std::unique_lock lock(mutex_);
    if (!std::filesystem::exists(usersFile_))
    {
        Json::Value users(Json::objectValue);
        users["guest"]["id"] = "guest";
        users["guest"]["user_id"] = "guest";
        users["guest"]["username"] = "guest";
        users["guest"]["password_hash"] = hashPassword("guest");
        users["guest"]["password_algo"] = "sha256";
        users["guest"]["status"] = "active";
        users["guest"]["email"] = "";
        users["guest"]["email_verified"] = false;
        users["guest"]["phone"] = "";
        users["guest"]["phone_verified"] = false;
        users["guest"]["member_no"] = "";
        users["guest"]["scope_type"] = "personal";
        users["guest"]["scope_id"] = "guest";
        users["guest"]["organization_type"] = "";
        users["guest"]["roles"] = Json::arrayValue;
        users["guest"]["roles"].append("guest");
        users["guest"]["created_at"] = common::nowIso8601();
        writeJsonFileAtomic(usersFile_, users);
    }

    if (!std::filesystem::exists(rolesFile_))
    {
        writeJsonFileAtomic(rolesFile_, defaultRolesMap());
        return;
    }

    auto roles = readJsonFile(rolesFile_);
    Json::Value normalized = defaultRolesMap();
    if (roles.isMember("roles") && roles["roles"].isArray())
    {
        for (const auto &role : roles["roles"])
        {
            const auto id = normalizeRoleId(role.get("id", "").asString());
            if (id.empty())
            {
                continue;
            }
            normalized[id] = mergeRoleDefinition(normalized[id], role, id);
        }
    }
    else if (roles.isObject())
    {
        for (const auto &id : roles.getMemberNames())
        {
            const auto normalizedId = normalizeRoleId(id);
            if (normalizedId.empty())
            {
                continue;
            }
            normalized[normalizedId] = mergeRoleDefinition(normalized[normalizedId], roles[id], normalizedId);
        }
    }

    wal_.append("roles_normalized", normalized);
    writeJsonFileAtomic(rolesFile_, normalized);
}

Json::Value UserRepository::users() const
{
    std::shared_lock lock(mutex_);
    auto rawUsers = readJsonFile(usersFile_);
    Json::Value normalized(Json::objectValue);
    forEachUserValue(rawUsers, [&normalized](const Json::Value &entry) {
        const auto user = normalizeUser(entry);
        const auto key = user.get("id", user.get("user_id", "")).asString();
        if (!key.empty())
        {
            normalized[key] = user;
        }
    });
    return normalized;
}

Json::Value UserRepository::roles() const
{
    std::shared_lock lock(mutex_);
    auto rolesJson = readJsonFile(rolesFile_);
    Json::Value normalized = defaultRolesMap();
    for (const auto &id : rolesJson.getMemberNames())
    {
        const auto normalizedId = normalizeRoleId(id);
        if (normalizedId.empty())
        {
            continue;
        }
        normalized[normalizedId] = mergeRoleDefinition(normalized[normalizedId], rolesJson[id], normalizedId);
    }
    return normalized;
}

Json::Value UserRepository::findUserByUsername(const std::string &username) const
{
    std::shared_lock lock(mutex_);
    auto usersJson = readJsonFile(usersFile_);
    Json::Value result(Json::nullValue);
    forEachUserValue(usersJson, [&result, &username](const Json::Value &entry) {
        if (!result.isNull())
        {
            return;
        }
        const auto user = normalizeUser(entry);
        if (user.get("username", "").asString() == username)
        {
            result = user;
        }
    });
    return result;
}

Json::Value UserRepository::findUserByEmail(const std::string &email) const
{
    std::shared_lock lock(mutex_);
    auto usersJson = readJsonFile(usersFile_);
    Json::Value result(Json::nullValue);
    forEachUserValue(usersJson, [&result, &email](const Json::Value &entry) {
        if (!result.isNull())
        {
            return;
        }
        const auto user = normalizeUser(entry);
        if (user.get("email", "").asString() == email)
        {
            result = user;
        }
    });
    return result;
}

Json::Value UserRepository::findUserByLoginId(const std::string &loginId) const
{
    std::shared_lock lock(mutex_);
    auto usersJson = readJsonFile(usersFile_);
    Json::Value result(Json::nullValue);
    forEachUserValue(usersJson, [&result, &loginId](const Json::Value &entry) {
        if (!result.isNull())
        {
            return;
        }
        const auto user = normalizeUser(entry);
        if (matchesLoginId(user, loginId))
        {
            result = user;
        }
    });
    return result;
}

Json::Value UserRepository::findUserById(const std::string &userId) const
{
    std::shared_lock lock(mutex_);
    auto usersJson = readJsonFile(usersFile_);
    Json::Value result(Json::nullValue);
    forEachUserValue(usersJson, [&result, &userId](const Json::Value &entry) {
        if (!result.isNull())
        {
            return;
        }
        const auto user = normalizeUser(entry);
        if (user.get("id", "").asString() == userId)
        {
            result = user;
        }
    });
    return result;
}

Json::Value UserRepository::usersByRole(const std::string &roleId) const
{
    const auto normalizedRole = normalizeRoleId(roleId);
    std::shared_lock lock(mutex_);
    auto usersJson = readJsonFile(usersFile_);
    Json::Value result(Json::arrayValue);
    forEachUserValue(usersJson, [&result, &normalizedRole](const Json::Value &entry) {
        const auto user = normalizeUser(entry);
        bool matched = false;
        for (const auto &role : user["roles"])
        {
            if (normalizeRoleId(role.asString()) == normalizedRole)
            {
                matched = true;
                break;
            }
        }
        if (normalizedRole == "guest" && user["roles"].empty())
        {
            matched = true;
        }
        if (matched)
        {
            result.append(user);
        }
    });
    return result;
}

Json::Value UserRepository::createUser(const std::string &username,
                       const std::string &password,
                       const std::string &email,
                       const std::string &referralCode)
{
    std::unique_lock lock(mutex_);
    auto usersJson = readJsonFile(usersFile_);
    if (containsUsername(usersJson, username))
    {
        throw common::AppException("USER_EXISTS", "Username already exists", drogon::k400BadRequest);
    }

    Json::Value referrer(Json::nullValue);
    const auto normalizedReferralCode = normalizeReferralCode(referralCode);
    if (!normalizedReferralCode.empty())
    {
        referrer = findUserByReferralCodeUnlocked(usersJson, normalizedReferralCode);
        if (referrer.isNull())
        {
            throw common::AppException("REFERRAL_CODE_INVALID", "Referral code is invalid", drogon::k422UnprocessableEntity);
        }
    }

    const auto userId = generateUserId();
    const auto key = userId;
    usersJson[key]["id"] = userId;
    usersJson[key]["user_id"] = userId;
    usersJson[key]["username"] = username;
    usersJson[key]["member_no"] = nextPersonalMemberNo(usersJson);
    usersJson[key]["password_hash"] = hashPassword(password);
    usersJson[key]["password_algo"] = "sha256";
    usersJson[key]["email"] = email;
    usersJson[key]["email_verified"] = false;
    usersJson[key]["phone"] = "";
    usersJson[key]["phone_verified"] = false;
    usersJson[key]["status"] = "active";
    usersJson[key]["scope_type"] = "personal";
    usersJson[key]["scope_id"] = userId;
    usersJson[key]["organization_type"] = "";
    usersJson[key]["roles"] = Json::arrayValue;
    usersJson[key]["roles"].append("student");
    usersJson[key]["created_at"] = common::nowIso8601();
    usersJson[key]["referral_code"] = generateReferralCode(usersJson, username);
    usersJson[key]["referred_by_user_id"] = referrer.isNull() ? "" : referrer.get("id", referrer.get("user_id", "")).asString();
    usersJson[key]["referred_by_code"] = referrer.isNull() ? "" : normalizedReferralCode;
    usersJson[key]["referral_bound_at"] = referrer.isNull() ? "" : common::nowIso8601();
    usersJson[key]["referral_reward_status"] = referrer.isNull() ? "none" : "pending";

    wal_.append("user_created", usersJson[key]);
    writeJsonFileAtomic(usersFile_, usersJson);
    return normalizeUser(usersJson[key]);
}

Json::Value UserRepository::createDevelopmentUser(const std::string &loginId)
{
    std::unique_lock lock(mutex_);
    auto usersJson = readJsonFile(usersFile_);
    Json::Value existing(Json::nullValue);
    forEachUserValue(usersJson, [&existing, &loginId](const Json::Value &entry) {
        if (!existing.isNull())
        {
            return;
        }
        const auto user = normalizeUser(entry);
        if (matchesLoginId(user, loginId))
        {
            existing = user;
        }
    });
    if (!existing.isNull())
    {
        return existing;
    }

    const auto userId = generateUserId();
    const auto key = userId;
    const auto loginKey = sanitizeIdentifier(loginId);
    const auto username = uniqueUsernameForBase(usersJson, loginId.empty() ? ("wxdev_" + loginKey) : loginId);

    usersJson[key]["id"] = userId;
    usersJson[key]["user_id"] = userId;
    usersJson[key]["username"] = username;
    usersJson[key]["member_no"] = nextPersonalMemberNo(usersJson);
    usersJson[key]["password_hash"] = "";
    usersJson[key]["password_algo"] = "dev-empty";
    usersJson[key]["email"] = "";
    usersJson[key]["email_verified"] = false;
    usersJson[key]["phone"] = "";
    usersJson[key]["phone_verified"] = false;
    usersJson[key]["wechat_openid"] = "stub_openid_" + loginKey;
    usersJson[key]["wechat_nickname"] = username;
    usersJson[key]["dev_login_id"] = loginId;
    usersJson[key]["status"] = "active";
    usersJson[key]["scope_type"] = "personal";
    usersJson[key]["scope_id"] = userId;
    usersJson[key]["organization_type"] = "";
    usersJson[key]["roles"] = developmentRolesForLoginId(loginId);
    usersJson[key]["created_at"] = common::nowIso8601();

    wal_.append("development_user_created", usersJson[key]);
    writeJsonFileAtomic(usersFile_, usersJson);
    return normalizeUser(usersJson[key]);
}

bool UserRepository::verifyPassword(const Json::Value &user, const std::string &password) const
{
    const auto algo = user.get("password_algo", "sha256").asString();
    if (algo == "sha256")
    {
        return user.get("password_hash", "").asString() == hashPassword(password);
    }
    if (algo == "plain")
    {
        return user.get("password", "").asString() == password;
    }
    return false;
}

Json::Value UserRepository::updatePassword(const std::string &userId, const std::string &password)
{
    std::unique_lock lock(mutex_);
    auto usersJson = readJsonFile(usersFile_);
    Json::Value result(Json::nullValue);
    forEachUserValue(usersJson, [&result, &userId, &password](Json::Value &entry) {
        if (!result.isNull())
        {
            return;
        }
        const auto user = normalizeUser(entry);
        if (user.get("id", "").asString() == userId)
        {
            entry["password_hash"] = hashPassword(password);
            entry["password_algo"] = "sha256";
            entry["password_updated_at"] = common::nowIso8601();
            result = normalizeUser(entry);
        }
    });
    if (!result.isNull())
    {
        wal_.append("password_updated", result);
        writeJsonFileAtomic(usersFile_, usersJson);
        return result;
    }
    throw common::AppException("USER_NOT_FOUND", "User not found: " + userId, drogon::k404NotFound);
}

    // Bind (or update) a verified phone number to a user.
Json::Value UserRepository::bindPhone(const std::string &userId, const std::string &phone)
{
    std::unique_lock lock(mutex_);
    auto usersJson = readJsonFile(usersFile_);
    forEachUserValue(usersJson, [&phone, &userId](Json::Value &entry) {
        const auto user = normalizeUser(entry);
        if (user.get("phone", "").asString() == phone && user.get("id", "").asString() != userId)
        {
            throw common::AppException("PHONE_IN_USE", "Phone number is already bound to another user", drogon::k409Conflict);
        }
    });
    Json::Value result(Json::nullValue);
    forEachUserValue(usersJson, [&result, &userId, &phone](Json::Value &entry) {
        if (!result.isNull())
        {
            return;
        }
        const auto user = normalizeUser(entry);
        if (user.get("id", "").asString() == userId)
        {
            entry["phone"] = phone;
            entry["phone_verified"] = true;
            result = normalizeUser(entry);
        }
    });
    if (!result.isNull())
    {
        wal_.append("phone_bound", result);
        writeJsonFileAtomic(usersFile_, usersJson);
        return result;
    }
    throw common::AppException("USER_NOT_FOUND", "User not found: " + userId, drogon::k404NotFound);
}

Json::Value UserRepository::bindEmail(const std::string &userId, const std::string &email)
{
    std::unique_lock lock(mutex_);
    auto usersJson = readJsonFile(usersFile_);
    forEachUserValue(usersJson, [&email, &userId](Json::Value &entry) {
        const auto user = normalizeUser(entry);
        if (user.get("email", "").asString() == email && user.get("id", "").asString() != userId)
        {
            throw common::AppException("EMAIL_IN_USE", "Email is already bound to another user", drogon::k409Conflict);
        }
    });
    Json::Value result(Json::nullValue);
    forEachUserValue(usersJson, [&result, &userId, &email](Json::Value &entry) {
        if (!result.isNull())
        {
            return;
        }
        const auto user = normalizeUser(entry);
        if (user.get("id", "").asString() == userId)
        {
            entry["email"] = email;
            entry["email_verified"] = true;
            result = normalizeUser(entry);
        }
    });
    if (!result.isNull())
    {
        wal_.append("email_bound", result);
        writeJsonFileAtomic(usersFile_, usersJson);
        return result;
    }
    throw common::AppException("USER_NOT_FOUND", "User not found: " + userId, drogon::k404NotFound);
}

Json::Value UserRepository::findUserByPhone(const std::string &phone) const
{
    std::shared_lock lock(mutex_);
    auto usersJson = readJsonFile(usersFile_);
    Json::Value result(Json::nullValue);
    forEachUserValue(usersJson, [&result, &phone](const Json::Value &entry) {
        if (!result.isNull())
        {
            return;
        }
        const auto user = normalizeUser(entry);
        if (user.get("phone", "").asString() == phone)
        {
            result = user;
        }
    });
    return result;
}

Json::Value UserRepository::createPhoneUser(const std::string &phone, const std::string &referralCode)
{
    std::unique_lock lock(mutex_);
    auto usersJson = readJsonFile(usersFile_);
    Json::Value existing(Json::nullValue);
    forEachUserValue(usersJson, [&existing, &phone](const Json::Value &entry) {
        if (!existing.isNull())
        {
            return;
        }
        const auto user = normalizeUser(entry);
        if (user.get("phone", "").asString() == phone)
        {
            existing = user;
        }
    });
    if (!existing.isNull())
    {
        return existing;
    }

    Json::Value referrer(Json::nullValue);
    const auto normalizedReferralCode = normalizeReferralCode(referralCode);
    if (!normalizedReferralCode.empty())
    {
        referrer = findUserByReferralCodeUnlocked(usersJson, normalizedReferralCode);
        if (referrer.isNull())
        {
            throw common::AppException("REFERRAL_CODE_INVALID", "Referral code is invalid", drogon::k422UnprocessableEntity);
        }
    }

    const auto usernameBase = "phone_" + sanitizePhone(phone);
    const auto username = uniqueUsernameForBase(usersJson, usernameBase);
    const auto userId = generateUserId();
    const auto key = userId;
    usersJson[key]["id"] = userId;
    usersJson[key]["user_id"] = userId;
    usersJson[key]["username"] = username;
    usersJson[key]["member_no"] = nextPersonalMemberNo(usersJson);
    usersJson[key]["password_hash"] = "";
    usersJson[key]["password_algo"] = "phone";
    usersJson[key]["email"] = "";
    usersJson[key]["email_verified"] = false;
    usersJson[key]["phone"] = phone;
    usersJson[key]["phone_verified"] = true;
    usersJson[key]["status"] = "active";
    usersJson[key]["scope_type"] = "personal";
    usersJson[key]["scope_id"] = userId;
    usersJson[key]["organization_type"] = "";
    usersJson[key]["roles"] = Json::arrayValue;
    usersJson[key]["roles"].append("student");
    usersJson[key]["created_at"] = common::nowIso8601();
    usersJson[key]["referral_code"] = generateReferralCode(usersJson, username);
    usersJson[key]["referred_by_user_id"] = referrer.isNull() ? "" : referrer.get("id", referrer.get("user_id", "")).asString();
    usersJson[key]["referred_by_code"] = referrer.isNull() ? "" : normalizedReferralCode;
    usersJson[key]["referral_bound_at"] = referrer.isNull() ? "" : common::nowIso8601();
    usersJson[key]["referral_reward_status"] = referrer.isNull() ? "none" : "pending";

    wal_.append("phone_user_created", usersJson[key]);
    writeJsonFileAtomic(usersFile_, usersJson);
    return normalizeUser(usersJson[key]);
}

Json::Value UserRepository::findUserByReferralCode(const std::string &referralCode) const
{
    const auto normalizedCode = normalizeReferralCode(referralCode);
    if (normalizedCode.empty())
    {
        return Json::Value(Json::nullValue);
    }

    std::shared_lock lock(mutex_);
    return findUserByReferralCodeUnlocked(readJsonFile(usersFile_), normalizedCode);
}

Json::Value UserRepository::claimReferral(const std::string &userId, const std::string &referralCode)
{
    const auto normalizedCode = normalizeReferralCode(referralCode);
    if (normalizedCode.empty())
    {
        throw common::AppException("REFERRAL_CODE_REQUIRED", "Referral code is required", drogon::k422UnprocessableEntity);
    }

    std::unique_lock lock(mutex_);
    auto usersJson = readJsonFile(usersFile_);
    const auto referrer = findUserByReferralCodeUnlocked(usersJson, normalizedCode);
    if (referrer.isNull())
    {
        throw common::AppException("REFERRAL_CODE_INVALID", "Referral code is invalid", drogon::k422UnprocessableEntity);
    }

    const auto referrerUserId = referrer.get("id", referrer.get("user_id", "")).asString();
    Json::Value updated(Json::nullValue);
    forEachUserValue(usersJson, [&updated, &userId, &normalizedCode, &referrerUserId](Json::Value &entry) {
        if (!updated.isNull())
        {
            return;
        }
        const auto user = normalizeUser(entry);
        if (user.get("id", "").asString() != userId)
        {
            return;
        }
        if (!user.get("referred_by_user_id", "").asString().empty())
        {
            throw common::AppException("REFERRAL_ALREADY_CLAIMED", "Referral is already bound for this account", drogon::k409Conflict);
        }
        if (user.get("referral_code", "").asString() == normalizedCode || userId == referrerUserId)
        {
            throw common::AppException("REFERRAL_SELF_NOT_ALLOWED", "You cannot use your own referral code", drogon::k409Conflict);
        }
        entry["referred_by_user_id"] = referrerUserId;
        entry["referred_by_code"] = normalizedCode;
        entry["referral_bound_at"] = common::nowIso8601();
        entry["referral_reward_status"] = "pending";
        updated = normalizeUser(entry);
    });

    if (updated.isNull())
    {
        throw common::AppException("USER_NOT_FOUND", "User not found", drogon::k404NotFound);
    }

    wal_.append("referral_claimed", updated);
    writeJsonFileAtomic(usersFile_, usersJson);
    return updated;
}

bool UserRepository::grantReferralRewardIfPending(const std::string &userId,
                                  const std::string &trigger,
                                  int rewardCredits,
                                  const std::string &rewardRecipientUserId)
{
    std::unique_lock lock(mutex_);
    auto usersJson = readJsonFile(usersFile_);
    Json::Value updated(Json::nullValue);
    bool changed = false;
    forEachUserValue(usersJson, [&updated, &userId, &trigger, &rewardCredits, &rewardRecipientUserId, &changed](Json::Value &entry) {
        if (!updated.isNull())
        {
            return;
        }
        const auto user = normalizeUser(entry);
        if (user.get("id", "").asString() != userId)
        {
            return;
        }

        updated = user;
        if (user.get("referred_by_user_id", "").asString().empty() ||
            user.get("referral_reward_status", "none").asString() != "pending")
        {
            return;
        }

        entry["referral_reward_status"] = "granted";
        entry["referral_reward_granted_at"] = common::nowIso8601();
        entry["referral_reward_trigger"] = trigger;
        entry["referral_reward_credit_amount"] = rewardCredits;
        entry["referral_reward_credit_recipient_user_id"] = rewardRecipientUserId;
        updated = normalizeUser(entry);
        changed = true;
    });

    if (updated.isNull())
    {
        throw common::AppException("USER_NOT_FOUND", "User not found", drogon::k404NotFound);
    }

    if (!changed)
    {
        return false;
    }

    wal_.append("referral_reward_granted", updated);
    writeJsonFileAtomic(usersFile_, usersJson);
    return true;
}

    // Find user by WeChat openid (returns null if not found).
Json::Value UserRepository::findUserByOpenid(const std::string &openid) const
{
    std::shared_lock lock(mutex_);
    auto usersJson = readJsonFile(usersFile_);
    Json::Value result(Json::nullValue);
    forEachUserValue(usersJson, [&result, &openid](const Json::Value &entry) {
        if (!result.isNull())
        {
            return;
        }
        const auto user = normalizeUser(entry);
        if (user.get("wechat_openid", "").asString() == openid)
        {
            result = user;
        }
    });
    return result;
}

    // Create or update a user by WeChat openid.
Json::Value UserRepository::upsertWechatUser(const std::string &openid,
                            const std::string &nickname,
                            const std::string &avatarUrl,
                            const std::string &loginIdHint)
{
    std::unique_lock lock(mutex_);
    auto usersJson = readJsonFile(usersFile_);

    // Search for existing user with this openid
    Json::Value updated(Json::nullValue);
    forEachUserValue(usersJson, [&updated, &openid, &nickname, &avatarUrl, &loginIdHint, this, &usersJson](Json::Value &entry) {
        if (!updated.isNull())
        {
            return;
        }
        const auto user = normalizeUser(entry);
        if (user.get("wechat_openid", "").asString() != openid)
        {
            return;
        }
        if (!nickname.empty())
        {
            entry["wechat_nickname"] = nickname;
        }
        if (!avatarUrl.empty())
        {
            entry["wechat_avatar"] = avatarUrl;
        }
        if (!loginIdHint.empty())
        {
            entry["dev_login_id"] = loginIdHint;
            entry["roles"] = developmentRolesForLoginId(loginIdHint);
        }
        else if (entry["roles"].empty())
        {
            entry["roles"] = Json::arrayValue;
            entry["roles"].append("student");
        }
        entry["status"] = normalizeStatus(user.get("status", "active").asString());
        if (normalizeUser(entry).get("member_no", "").asString().empty())
        {
            entry["member_no"] = nextPersonalMemberNo(usersJson);
        }
        updated = normalizeUser(entry);
    });
    if (!updated.isNull())
    {
        wal_.append("wechat_user_updated", updated);
        writeJsonFileAtomic(usersFile_, usersJson);
        return updated;
    }

    // Create new user
    const auto userId = generateUserId();
    const auto usernameBase = loginIdHint.empty() ? ("wx_" + openid.substr(0, std::min(openid.size(), static_cast<size_t>(10)))) : loginIdHint;
    const auto username = uniqueUsernameForBase(usersJson, usernameBase);
    const auto key = userId;
    usersJson[key]["id"] = userId;
    usersJson[key]["user_id"] = userId;
    usersJson[key]["username"] = username;
    usersJson[key]["member_no"] = nextPersonalMemberNo(usersJson);
    usersJson[key]["password_hash"] = "";
    usersJson[key]["password_algo"] = "wechat";
    usersJson[key]["email"] = "";
    usersJson[key]["email_verified"] = false;
    usersJson[key]["phone"] = "";
    usersJson[key]["phone_verified"] = false;
    usersJson[key]["wechat_openid"] = openid;
    usersJson[key]["wechat_nickname"] = nickname;
    usersJson[key]["wechat_avatar"] = avatarUrl;
    usersJson[key]["dev_login_id"] = loginIdHint;
    usersJson[key]["status"] = "active";
    usersJson[key]["scope_type"] = "personal";
    usersJson[key]["scope_id"] = userId;
    usersJson[key]["organization_type"] = "";
    usersJson[key]["roles"] = loginIdHint.empty() ? normalizeRolesArray(Json::Value(Json::arrayValue)) : developmentRolesForLoginId(loginIdHint);
    usersJson[key]["created_at"] = common::nowIso8601();

    wal_.append("wechat_user_created", usersJson[key]);
    writeJsonFileAtomic(usersFile_, usersJson);
    return normalizeUser(usersJson[key]);
}

Json::Value UserRepository::defaultRolesMap()
{
    Json::Value roles(Json::objectValue);
    roles["guest"]["id"] = "guest";
    roles["guest"]["name"] = "访客";
    roles["guest"]["description"] = "未登录访客";
    roles["guest"]["permissions"] = Json::arrayValue;
    roles["guest"]["permissions"].append("view_exams");
    roles["guest"]["permissions"].append("submit_answers");

    roles["student"]["id"] = "student";
    roles["student"]["name"] = "学习者";
    roles["student"]["description"] = "默认业务角色";
    roles["student"]["permissions"] = Json::arrayValue;
    roles["student"]["permissions"].append("view_exams");
    roles["student"]["permissions"].append("submit_answers");
    roles["student"]["permissions"].append("save_progress");

    roles["teacher"]["id"] = "teacher";
    roles["teacher"]["name"] = "教师";
    roles["teacher"]["description"] = "题目与教学内容管理";
    roles["teacher"]["permissions"] = Json::arrayValue;
    roles["teacher"]["permissions"].append("question.manage");

    roles["reviewer"]["id"] = "reviewer";
    roles["reviewer"]["name"] = "阅卷员";
    roles["reviewer"]["description"] = "阅卷与审核";
    roles["reviewer"]["permissions"] = Json::arrayValue;
    roles["reviewer"]["permissions"].append("review.manage");

    roles["orgAdmin"]["id"] = "orgAdmin";
    roles["orgAdmin"]["name"] = "组织管理员";
    roles["orgAdmin"]["description"] = "组织成员与空间管理";
    roles["orgAdmin"]["permissions"] = Json::arrayValue;
    roles["orgAdmin"]["permissions"].append("organization.manage");

    roles["systemAdmin"]["id"] = "systemAdmin";
    roles["systemAdmin"]["name"] = "系统管理员";
    roles["systemAdmin"]["description"] = "系统运维管理";
    roles["systemAdmin"]["permissions"] = Json::arrayValue;
    roles["systemAdmin"]["permissions"].append("system.manage");

    roles["superAdmin"]["id"] = "superAdmin";
    roles["superAdmin"]["name"] = "超级管理员";
    roles["superAdmin"]["description"] = "平台全部权限";
    roles["superAdmin"]["permissions"] = Json::arrayValue;
    roles["superAdmin"]["permissions"].append("*");
    return roles;
}

Json::Value UserRepository::normalizeUser(const Json::Value &input)
{
    Json::Value user = input.isObject() ? input : Json::Value(Json::objectValue);
    const auto userId = user.get("id", user.get("user_id", "")).asString();
    user["id"] = userId;
    user["user_id"] = userId;
    user["username"] = user.get("username", userId).asString();
    user["display_name"] = user.get("display_name", user.get("displayName", "")).asString();
    user["member_no"] = user.get("member_no", user.get("student_no", "")).asString();
    user["memberNo"] = user["member_no"].asString();
    user["student_no"] = user.get("student_no", "").asString();
    user["studentNo"] = user["student_no"].asString();
    user["employee_no"] = user.get("employee_no", "").asString();
    user["employeeNo"] = user["employee_no"].asString();
    user["dev_login_id"] = user.get("dev_login_id", "").asString();
    user["email"] = user.get("email", "").asString();
    user["email_verified"] = user.get("email_verified", false).asBool();
    user["avatar"] = user.get("avatar", user.get("avatar_url", "")).asString();
    user["avatar_url"] = user.get("avatar_url", user["avatar"].asString()).asString();
    user["password_hash"] = user.get("password_hash", user.get("passwordHash", "")).asString();
    user["password_algo"] = user.get("password_algo", user["password_hash"].asString().empty() ? "sha256" : "sha256").asString();
    user["phone"] = user.get("phone", "").asString();
    user["phone_verified"] = user.get("phone_verified", false).asBool();
    user["status"] = normalizeStatus(user.get("status", "active").asString());
    user["scope_type"] = normalizeScopeType(user.get("scope_type", "personal").asString());
    user["scope_id"] = user.get("scope_id", userId).asString();
    user["organization_type"] = normalizeOrganizationType(
        user.get("organization_type", user["scope_type"].asString() == "organization" ? "business" : "").asString(),
        user["scope_type"].asString());
    user["created_at"] = user.get("created_at", user.get("createdAt", common::nowIso8601())).asString();
    user["referral_code"] = normalizeReferralCode(user.get("referral_code", user.get("referralCode", "")).asString());
    user["referralCode"] = user["referral_code"].asString();
    user["referred_by_user_id"] = user.get("referred_by_user_id", user.get("referredByUserId", "")).asString();
    user["referredByUserId"] = user["referred_by_user_id"].asString();
    user["referred_by_code"] = normalizeReferralCode(user.get("referred_by_code", user.get("referredByCode", "")).asString());
    user["referredByCode"] = user["referred_by_code"].asString();
    user["referral_bound_at"] = user.get("referral_bound_at", user.get("referralBoundAt", "")).asString();
    user["referralBoundAt"] = user["referral_bound_at"].asString();
    user["referral_reward_status"] = normalizeReferralRewardStatus(user.get("referral_reward_status", user.get("referralRewardStatus", user["referred_by_user_id"].asString().empty() ? "none" : "pending")).asString());
    user["referralRewardStatus"] = user["referral_reward_status"].asString();
    user["referral_reward_granted_at"] = user.get("referral_reward_granted_at", user.get("referralRewardGrantedAt", "")).asString();
    user["referralRewardGrantedAt"] = user["referral_reward_granted_at"].asString();
    user["referral_reward_trigger"] = user.get("referral_reward_trigger", user.get("referralRewardTrigger", "")).asString();
    user["referralRewardTrigger"] = user["referral_reward_trigger"].asString();
    user["referral_reward_credit_amount"] = user.get("referral_reward_credit_amount", user.get("referralRewardCreditAmount", 0)).asInt();
    user["referralRewardCreditAmount"] = user["referral_reward_credit_amount"].asInt();
    user["referral_reward_credit_recipient_user_id"] = user.get("referral_reward_credit_recipient_user_id", user.get("referralRewardCreditRecipientUserId", "")).asString();
    user["referralRewardCreditRecipientUserId"] = user["referral_reward_credit_recipient_user_id"].asString();
    if (user["referral_code"].asString().empty())
    {
        user["referral_code"] = legacyReferralCode(userId, user.get("username", "").asString());
        user["referralCode"] = user["referral_code"].asString();
    }
    user["roles"] = normalizeRolesArray(user.isMember("roles") ? user["roles"] : user["roleIds"]);
    return user;
}

std::string UserRepository::normalizeReferralCode(std::string referralCode)
{
    std::string normalized;
    normalized.reserve(referralCode.size());
    for (const auto ch : referralCode)
    {
        if (std::isalnum(static_cast<unsigned char>(ch)))
        {
            normalized.push_back(static_cast<char>(std::toupper(static_cast<unsigned char>(ch))));
        }
    }
    return normalized;
}

std::string UserRepository::normalizeReferralRewardStatus(const std::string &status)
{
    if (status == "none" || status == "pending" || status == "granted" || status == "rejected")
    {
        return status;
    }
    return "none";
}

Json::Value UserRepository::findUserByReferralCodeUnlocked(const Json::Value &usersJson, const std::string &referralCode)
{
    Json::Value result(Json::nullValue);
    forEachUserValue(usersJson, [&result, &referralCode](const Json::Value &entry) {
        if (!result.isNull())
        {
            return;
        }
        const auto user = normalizeUser(entry);
        if (user.get("referral_code", "").asString() == referralCode)
        {
            result = user;
        }
    });
    return result;
}

std::string UserRepository::generateReferralCode(const Json::Value &usersJson, const std::string &seed)
{
    const auto prefix = buildReferralPrefix(seed);
    std::random_device rd;
    std::mt19937 generator(rd());
    std::uniform_int_distribution<int> distribution(0, 35);
    constexpr char alphabet[] = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    for (int attempt = 0; attempt < 32; ++attempt)
    {
        std::string code = prefix;
        while (code.size() < 10)
        {
            code.push_back(alphabet[distribution(generator)]);
        }
        if (findUserByReferralCodeUnlocked(usersJson, code).isNull())
        {
            return code;
        }
    }
    return "REF" + common::generateOpaqueId("").substr(0, 8);
}

std::string UserRepository::buildReferralPrefix(const std::string &seed)
{
    auto normalizedSeed = normalizeReferralCode(seed);
    if (normalizedSeed.size() > 6)
    {
        normalizedSeed = normalizedSeed.substr(0, 6);
    }
    if (normalizedSeed.size() < 3)
    {
        normalizedSeed = "REF";
    }
    return normalizedSeed;
}

std::string UserRepository::legacyReferralCode(const std::string &userId, const std::string &username)
{
    auto prefix = buildReferralPrefix(username);
    auto suffix = normalizeReferralCode(userId);
    if (suffix.size() > 10 - prefix.size())
    {
        suffix = suffix.substr(suffix.size() - (10 - prefix.size()));
    }
    while (suffix.size() < 10 - prefix.size())
    {
        suffix.insert(suffix.begin(), '0');
    }
    return prefix + suffix;
}

Json::Value UserRepository::mergeRoleDefinition(const Json::Value &baseline, const Json::Value &incoming, const std::string &roleId)
{
    Json::Value merged = baseline.isObject() ? baseline : Json::Value(Json::objectValue);
    merged["id"] = roleId;
    merged["name"] = incoming.get("name", merged.get("name", roleId).asString()).asString();
    merged["description"] = incoming.get("description", merged.get("description", "").asString()).asString();

    Json::Value permissions(Json::arrayValue);
    appendUniqueStrings(permissions, merged["permissions"]);
    appendUniqueStrings(permissions, incoming["permissions"]);
    appendUniqueStrings(permissions, incoming["privileges"]);
    merged["permissions"] = permissions;
    return merged;
}

Json::Value UserRepository::normalizeRolesArray(const Json::Value &roles)
{
    Json::Value normalized(Json::arrayValue);

    if (roles.isString())
    {
        appendUniqueRole(normalized, normalizeRoleId(roles.asString()));
    }
    else if (roles.isArray())
    {
        for (const auto &role : roles)
        {
            appendUniqueRole(normalized, normalizeRoleId(role.asString()));
        }
    }

    if (normalized.empty())
    {
        normalized.append("student");
    }
    return normalized;
}

void UserRepository::appendUniqueStrings(Json::Value &target, const Json::Value &values)
{
    if (!values.isArray())
    {
        return;
    }
    for (const auto &value : values)
    {
        const auto item = value.asString();
        if (item.empty())
        {
            continue;
        }
        bool exists = false;
        for (const auto &current : target)
        {
            if (current.asString() == item)
            {
                exists = true;
                break;
            }
        }
        if (!exists)
        {
            target.append(item);
        }
    }
}

void UserRepository::appendUniqueRole(Json::Value &target, const std::string &role)
{
    if (role.empty())
    {
        return;
    }
    for (const auto &item : target)
    {
        if (item.asString() == role)
        {
            return;
        }
    }
    target.append(role);
}

std::string UserRepository::normalizeRoleId(const std::string &roleId)
{
    if (roleId == "user")
    {
        return "student";
    }
    if (roleId == "admin")
    {
        return "systemAdmin";
    }
    if (roleId == "academicAdmin")
    {
        return "orgAdmin";
    }
    if (roleId == "guest" || roleId == "student" || roleId == "teacher" || roleId == "reviewer" ||
        roleId == "orgAdmin" || roleId == "systemAdmin" || roleId == "superAdmin")
    {
        return roleId;
    }
    return "";
}

std::string UserRepository::normalizeStatus(const std::string &status)
{
    if (status == "active" || status == "disabled" || status == "pending")
    {
        return status;
    }
    return "active";
}

std::string UserRepository::normalizeScopeType(const std::string &scopeType)
{
    return scopeType == "organization" ? "organization" : "personal";
}

std::string UserRepository::normalizeOrganizationType(const std::string &organizationType, const std::string &scopeType)
{
    if (scopeType != "organization")
    {
        return "";
    }
    if (organizationType == "business" || organizationType == "school")
    {
        return organizationType;
    }
    return "business";
}

bool UserRepository::containsUsername(const Json::Value &usersJson, const std::string &username)
{
    bool found = false;
    forEachUserValue(usersJson, [&found, &username](const Json::Value &entry) {
        if (found)
        {
            return;
        }
        if (normalizeUser(entry).get("username", "").asString() == username)
        {
            found = true;
        }
    });
    return found;
}

bool UserRepository::matchesLoginId(const Json::Value &user, const std::string &loginId)
{
    return user.get("username", "").asString() == loginId ||
           user.get("id", "").asString() == loginId ||
           user.get("user_id", "").asString() == loginId ||
         user.get("member_no", "").asString() == loginId ||
           user.get("student_no", "").asString() == loginId ||
         user.get("employee_no", "").asString() == loginId ||
           user.get("dev_login_id", "").asString() == loginId;
}

std::string UserRepository::uniqueStorageKey(const Json::Value &usersJson, const std::string &base)
{
    std::string key = base;
    int suffix = 1;
    while (usersJson.isMember(key))
    {
        key = base + "_" + std::to_string(suffix++);
    }
    return key;
}

std::string UserRepository::uniqueUsernameForBase(const Json::Value &usersJson, const std::string &base)
{
    std::string username = base;
    int suffix = 1;
    while (containsUsername(usersJson, username))
    {
        username = base + "_" + std::to_string(suffix++);
    }
    return username;
}

std::string UserRepository::nextPersonalMemberNo(const Json::Value &usersJson)
{
    int maxSerial = 0;
    forEachUserValue(usersJson, [&maxSerial](const Json::Value &entry) {
        maxSerial = (std::max)(maxSerial, extractPrefixedSerial(normalizeUser(entry).get("member_no", "").asString(), "MEM-"));
    });
    return "MEM-" + padSerial(maxSerial + 1, 6);
}

Json::Value UserRepository::developmentRolesForLoginId(const std::string &loginId)
{
    Json::Value roles(Json::arrayValue);
    if (loginId.rfind("superadmin_", 0) == 0 || loginId.rfind("super_", 0) == 0)
    {
        roles.append("superAdmin");
        return roles;
    }
    if (loginId.rfind("systemadmin_", 0) == 0 || loginId.rfind("sysadmin_", 0) == 0 || loginId.rfind("system_", 0) == 0)
    {
        roles.append("systemAdmin");
        return roles;
    }
    if (loginId.rfind("orgadmin_", 0) == 0 || loginId.rfind("org_admin_", 0) == 0 || loginId.rfind("admin_", 0) == 0)
    {
        roles.append("orgAdmin");
        return roles;
    }
    if (loginId.rfind("teacher_", 0) == 0)
    {
        roles.append("teacher");
        return roles;
    }
    if (loginId.rfind("reviewer_", 0) == 0)
    {
        roles.append("reviewer");
        return roles;
    }
    roles.append("student");
    return roles;
}

std::string UserRepository::padSerial(int value, int width)
{
    auto text = std::to_string(value);
    if (static_cast<int>(text.size()) >= width)
    {
        return text;
    }
    return std::string(static_cast<size_t>(width - text.size()), '0') + text;
}

std::string UserRepository::sanitizeIdentifier(const std::string &value)
{
    std::string out;
    for (const auto ch : value)
    {
        if ((ch >= '0' && ch <= '9') ||
            (ch >= 'a' && ch <= 'z') ||
            (ch >= 'A' && ch <= 'Z') ||
            ch == '_' || ch == '-')
        {
            out.push_back(ch);
        }
    }
    return out.empty() ? std::string("test") : out;
}

std::string UserRepository::sanitizePhone(const std::string &phone)
{
    std::string out;
    for (const auto c : phone)
    {
        if (c >= '0' && c <= '9')
        {
            out.push_back(c);
        }
    }
    return out.empty() ? std::string("user") : out;
}

int UserRepository::extractPrefixedSerial(const std::string &value, const std::string &prefix)
{
    if (value.rfind(prefix, 0) != 0)
    {
        return 0;
    }

    const auto serial = value.substr(prefix.size());
    if (serial.empty())
    {
        return 0;
    }
    for (const auto ch : serial)
    {
        if (ch < '0' || ch > '9')
        {
            return 0;
        }
    }
    return std::stoi(serial);
}

std::string UserRepository::generateUserId()
{
    return common::generateOpaqueId("usr_");
}

}  // namespace infrastructure::storage
