// Auto-generated by tools/sink_class.ps1 from BookmarkService.h
#include "BookmarkService.h"

namespace application::services
{

BookmarkService::BookmarkService(infrastructure::storage::BookmarkRepository &repository) : repository_(repository)
{
}

Json::Value BookmarkService::getBookmarks(const std::string &userId) const
{
    return repository_.loadBookmarks(userId);
}

Json::Value BookmarkService::addExamBookmark(const std::string &userId, const std::string &examId)
{
    repository_.addExamBookmark(userId, examId);
    return repository_.loadBookmarks(userId);
}

Json::Value BookmarkService::removeExamBookmark(const std::string &userId, const std::string &examId)
{
    repository_.removeExamBookmark(userId, examId);
    return repository_.loadBookmarks(userId);
}

}  // namespace application::services
