// Auto-generated by tools/sink_class.ps1 from ProfileService.h
#include "ProfileService.h"

namespace application::services
{

ProfileService::ProfileService(infrastructure::storage::ProfileRepository &repository) : repository_(repository)
{
}

Json::Value ProfileService::getProfile(const std::string &userId) const
{
    return repository_.loadProfile(userId);
}

Json::Value ProfileService::updateProfile(const std::string &userId, const Json::Value &patch)
{
    auto profile = repository_.loadProfile(userId);

    static const std::vector<std::string> allowed = {
        "display_name", "avatar_url", "locale",
        "goal_level", "goal_date", "daily_target",
        "notification_enabled", "scope_type", "scope_id", "organization_type"};

    for (const auto &field : allowed)
    {
        if (patch.isMember(field))
        {
            profile[field] = patch[field];
        }
    }
    repository_.saveProfile(userId, profile);
    return profile;
}

}  // namespace application::services
