// Auto-generated by tools/sink_class.ps1 from ExamRepository.h
#include "ExamRepository.h"

#include <cctype>
#include <set>
#include <unordered_set>

namespace infrastructure::storage
{

namespace
{
std::string readString(const Json::Value &value, std::initializer_list<const char *> keys)
{
    for (const auto *key : keys)
    {
        if (value.isMember(key) && value[key].isString())
        {
            const auto text = value[key].asString();
            if (!text.empty())
            {
                return text;
            }
        }
    }
    return {};
}

std::string lowerCopy(std::string text)
{
    std::transform(text.begin(), text.end(), text.begin(), [](unsigned char c) {
        return static_cast<char>(std::tolower(c));
    });
    return text;
}

std::string safeSegment(std::string text)
{
    std::string out;
    out.reserve(text.size());
    for (const unsigned char c : text)
    {
        if (std::isalnum(c))
        {
            out.push_back(static_cast<char>(std::tolower(c)));
        }
        else if (c == '-' || c == '_')
        {
            out.push_back(static_cast<char>(c));
        }
    }
    return out;
}

std::string deduceYear(const Json::Value &examInfo, const std::vector<std::string> &parts)
{
    const auto explicitYear = readString(examInfo, {"year"});
    if (!explicitYear.empty())
    {
        return explicitYear;
    }
    const auto examDate = readString(examInfo, {"exam_date", "date"});
    if (examDate.size() >= 4 && std::all_of(examDate.begin(), examDate.begin() + 4, ::isdigit))
    {
        return examDate.substr(0, 4);
    }
    for (const auto &part : parts)
    {
        if (part.size() == 4 && std::all_of(part.begin(), part.end(), ::isdigit))
        {
            return part;
        }
    }
    return {};
}

std::string deduceSession(const Json::Value &examInfo, const std::vector<std::string> &parts)
{
    const auto explicitSession = readString(examInfo, {"session", "term"});
    if (!explicitSession.empty())
    {
        return explicitSession;
    }
    const auto examDate = readString(examInfo, {"exam_date", "date"});
    for (size_t i = 0; i + 1 < examDate.size(); ++i)
    {
        if (std::isdigit(static_cast<unsigned char>(examDate[i])) &&
            std::isdigit(static_cast<unsigned char>(examDate[i + 1])) &&
            (i == 0 || !std::isdigit(static_cast<unsigned char>(examDate[i - 1]))) &&
            (i + 2 >= examDate.size() || !std::isdigit(static_cast<unsigned char>(examDate[i + 2]))))
        {
            return examDate.substr(i, 2);
        }
    }
    for (const auto &part : parts)
    {
        if (part.size() == 2 && std::all_of(part.begin(), part.end(), ::isdigit))
        {
            return part;
        }
    }
    return {};
}

std::string deduceFamily(const Json::Value &root, const Json::Value &examInfo, const std::filesystem::path &relativePath)
{
    const auto explicitFamily = readString(root, {"family", "exam_family"});
    if (!explicitFamily.empty())
    {
        return lowerCopy(explicitFamily);
    }
    const auto infoFamily = readString(examInfo, {"family", "exam_family"});
    if (!infoFamily.empty())
    {
        return lowerCopy(infoFamily);
    }
    if (!relativePath.empty())
    {
        const auto first = relativePath.begin();
        if (first != relativePath.end())
        {
            const auto candidate = first->string();
            if (!candidate.empty() && candidate[0] != '.')
            {
                return lowerCopy(candidate);
            }
        }
    }
    return "jlpt";
}

Json::Value inferCapabilities(const Json::Value &examInfo)
{
    Json::Value capabilities(Json::objectValue);
    bool hasAudio = false;
    bool hasImage = false;
    bool hasRuby = false;
    bool hasTranslations = false;

    for (const auto &section : examInfo["sections"])
    {
        if (section.isMember("audio")) hasAudio = true;
        if (section.isMember("script") || section.isMember("scripts")) hasTranslations = true;
        if (section.isMember("furigana") || section.isMember("ruby")) hasRuby = true;

        const auto inspectQuestion = [&](const Json::Value &question) {
            if (question.isMember("audio")) hasAudio = true;
            if (question.isMember("script") || question.isMember("scripts")) hasTranslations = true;
            if (question.isMember("furigana") || question.isMember("ruby")) hasRuby = true;
            if (question.isMember("passage") && question["passage"].isObject())
            {
                const auto &passage = question["passage"];
                if (readString(passage, {"type"}) == "image" || passage.isMember("url"))
                {
                    hasImage = true;
                }
            }
        };

        for (const auto &question : section["questions"])
        {
            inspectQuestion(question);
        }
        for (const auto &passage : section["passages"])
        {
            if (readString(passage, {"type"}) == "image" || passage.isMember("url"))
            {
                hasImage = true;
            }
            if (passage.isMember("audio")) hasAudio = true;
            if (passage.isMember("script") || passage.isMember("scripts")) hasTranslations = true;
            for (const auto &question : passage["questions"])
            {
                inspectQuestion(question);
            }
        }
    }

    capabilities["audio"] = hasAudio;
    capabilities["image"] = hasImage;
    capabilities["ruby"] = hasRuby;
    capabilities["translation"] = hasTranslations;
    return capabilities;
}

std::vector<std::string> collectSkillTags(const Json::Value &root, const Json::Value &examInfo)
{
    std::set<std::string> unique;
    const auto collect = [&](const Json::Value &node) {
        for (const auto &fieldName : {"skill_tags", "skills"})
        {
            const auto &value = node[fieldName];
            if (!value.isArray())
            {
                continue;
            }
            for (const auto &item : value)
            {
                if (item.isString() && !item.asString().empty())
                {
                    unique.insert(item.asString());
                }
            }
        }
    };

    collect(root);
    collect(examInfo);
    for (const auto &section : examInfo["sections"])
    {
        collect(section);
        for (const auto &question : section["questions"])
        {
            collect(question);
        }
        for (const auto &passage : section["passages"])
        {
            collect(passage);
            for (const auto &question : passage["questions"])
            {
                collect(question);
            }
        }
    }

    return {unique.begin(), unique.end()};
}
}  // namespace

ExamRepository::ExamRepository(std::filesystem::path rootDir)
: rootDir_(std::move(rootDir)),
indexFile_(rootDir_ / ".exam_index.json")
{
    rebuildIndex();
}

void ExamRepository::rebuildIndex()
{
    std::unique_lock lock(mutex_);
    exams_.clear();
    fileIndex_.clear();
    examCache_.clear();

    if (!std::filesystem::exists(rootDir_))
    {
        return;
    }

    for (const auto &entry : std::filesystem::recursive_directory_iterator(rootDir_))
    {
        if (!entry.is_regular_file())
        {
            continue;
        }
        const auto fileName = entry.path().filename().string();
        if (entry.path().extension() != ".json" || fileName == ".exam_index.json" || (!fileName.empty() && fileName[0] == '.'))
        {
            continue;
        }

        auto summary = parseSummary(entry.path());
        if (!summary.has_value())
        {
            continue;
        }

        exams_.push_back(summary.value());
        fileIndex_[summary->id] = entry.path();
    }

    Json::Value indexPayload(Json::objectValue);
    indexPayload["updated_at"] = common::nowIso8601();
    indexPayload["count"] = static_cast<int>(exams_.size());
    indexPayload["items"] = Json::arrayValue;
    for (const auto &item : exams_)
    {
        auto row = item.toJson();
        row["path"] = fileIndex_[item.id].string();
        indexPayload["items"].append(row);
    }
    writeJsonFileAtomic(indexFile_, indexPayload);
}

std::vector<domain::ExamSummary> ExamRepository::listExams() const
{
    std::shared_lock lock(mutex_);
    return exams_;
}

Json::Value ExamRepository::getExamById(const std::string &examId)
{
    {
        std::shared_lock lock(mutex_);
        auto itCache = examCache_.find(examId);
        if (itCache != examCache_.end())
        {
            return itCache->second;
        }
    }

    std::filesystem::path path;
    {
        std::shared_lock lock(mutex_);
        auto it = fileIndex_.find(examId);
        if (it == fileIndex_.end())
        {
            throw common::AppException("EXAM_NOT_FOUND", "Exam not found: " + examId, drogon::k404NotFound);
        }
        path = it->second;
    }

    const auto exam = readJsonFile(path);
    {
        std::unique_lock lock(mutex_);
        examCache_[examId] = exam;
    }
    return exam;
}

void ExamRepository::saveExam(const std::string &examId, const Json::Value &payload)
{
    const auto path = buildStoragePath(examId, payload);
    writeJsonFileAtomic(path, payload);
    rebuildIndex();
}

void ExamRepository::deleteExam(const std::string &examId)
{
    std::filesystem::path path;
    {
        std::shared_lock lock(mutex_);
        auto it = fileIndex_.find(examId);
        if (it == fileIndex_.end())
        {
            throw common::AppException("EXAM_NOT_FOUND", "Exam not found: " + examId, drogon::k404NotFound);
        }
        path = it->second;
    }
    std::filesystem::remove(path);
    rebuildIndex();
}

std::filesystem::path ExamRepository::buildStoragePath(const std::string &examId, const Json::Value &payload) const
{
    const auto &examInfo = payload["exam_info"];
    const auto family = safeSegment(readString(payload, {"family", "exam_family"}).empty()
                                        ? readString(examInfo, {"family", "exam_family"})
                                        : readString(payload, {"family", "exam_family"}));
    const auto level = safeSegment(readString(payload, {"level"}).empty()
                                       ? readString(examInfo, {"exam_level", "level"})
                                       : readString(payload, {"level"}));

    std::filesystem::path path = rootDir_;
    path /= family.empty() ? "jlpt" : family;
    if (!level.empty())
    {
        path /= level;
    }
    path /= (examId + ".json");
    return path;
}

std::optional<domain::ExamSummary> ExamRepository::parseSummary(const std::filesystem::path &path) const
{
    try
    {
        const auto json = readJsonFile(path);
        const auto &examInfo = json["exam_info"];
        if (!examInfo.isObject() || !examInfo["sections"].isArray())
        {
            return std::nullopt;
        }

        const auto examId = path.stem().string();
        const auto parts = splitExamId(examId);
        const auto relativePath = std::filesystem::relative(path.parent_path(), rootDir_);

        domain::ExamSummary summary;
        summary.id = examId;
        summary.family = deduceFamily(json, examInfo, relativePath);
        summary.subject = readString(json, {"subject"});
        if (summary.subject.empty())
        {
            summary.subject = readString(examInfo, {"subject"});
        }
        if (summary.subject.empty())
        {
            summary.subject = summary.family == "jlpt" ? "japanese" : "language";
        }
        summary.paperType = readString(json, {"paper_type", "paperType"});
        if (summary.paperType.empty())
        {
            summary.paperType = readString(examInfo, {"paper_type", "paperType", "paper_kind"});
        }
        if (summary.paperType.empty())
        {
            summary.paperType = "mock_exam";
        }
        summary.level = readString(examInfo, {"exam_level", "level"});
        if (summary.level.empty() && !parts.empty())
        {
            summary.level = parts.front();
        }
        summary.year = deduceYear(examInfo, parts);
        summary.session = deduceSession(examInfo, parts);
        summary.display =
            readString(json, {"display"});
        if (summary.display.empty())
        {
            summary.display = readString(examInfo, {"display"});
        }
        if (summary.display.empty() && !summary.year.empty())
        {
            summary.display = summary.year + (summary.session.empty() ? "" : "_" + summary.session);
        }
        if (summary.display.empty())
        {
            summary.display = examId;
        }
        summary.title = examInfo.get("title", examId).asString();
        summary.checked = examInfo.get("checked", false).asBool();
        summary.questionCount = countQuestions(examInfo);
        summary.accessLevel = examInfo.get("access_level", "free").asString();
        summary.skills = collectSkillTags(json, examInfo);
        summary.capabilities = inferCapabilities(examInfo);
        return summary;
    }
    catch (...)
    {
        return std::nullopt;
    }
}

int ExamRepository::countQuestions(const Json::Value &examInfo)
{
    int count = 0;
    for (const auto &section : examInfo["sections"])
    {
        if (section.isMember("questions") && section["questions"].isArray())
        {
            count += static_cast<int>(section["questions"].size());
        }
        for (const auto &passage : section["passages"])
        {
            count += static_cast<int>(passage["questions"].size());
        }
    }
    return count;
}

std::vector<std::string> ExamRepository::splitExamId(const std::string &examId)
{
    std::vector<std::string> result;
    std::string token;
    for (char c : examId)
    {
        if (c == '_')
        {
            if (!token.empty())
            {
                result.push_back(token);
                token.clear();
            }
            continue;
        }
        token.push_back(c);
    }
    if (!token.empty())
    {
        result.push_back(token);
    }
    return result;
}

}  // namespace infrastructure::storage
