// Auto-generated by tools/sink_class.ps1 from AuthService.h
#include "AuthService.h"

#include <algorithm>
#include <cctype>
#include <random>

namespace application::services
{

AuthService::AuthService(infrastructure::storage::UserRepository &repository,
infrastructure::storage::ProfileRepository &profileRepository,
bool developmentMode,
infrastructure::storage::SessionRepository *sessionRepository,
EmailService *emailService,
SmsService *smsService)
: repository_(repository),
  profileRepository_(profileRepository),
  sessionRepository_(sessionRepository),
  emailService_(emailService),
  smsService_(smsService),
  developmentMode_(developmentMode)
{
    if (sessionRepository_)
    {
        sessionRepository_->pruneExpired(toEpochMillis(std::chrono::system_clock::now()));
    }
}

Json::Value AuthService::login(const std::string &username, const std::string &password)
{
    auto user = repository_.findUserByLoginId(username);
    if (user.isNull() && developmentMode_ && password.empty())
    {
        user = repository_.createDevelopmentUser(username);
    }

    if (user.isNull())
    {
        throw common::AppException("INVALID_CREDENTIALS", "Username or password is invalid", drogon::k401Unauthorized);
    }
    if (user.get("status", "active").asString() != "active")
    {
        throw common::AppException("ACCOUNT_DISABLED", "This account is disabled", drogon::k403Forbidden);
    }

    const auto allowEmptyPassword = developmentMode_ && password.empty() && allowsDevelopmentEmptyPassword(user);
    if (!allowEmptyPassword && !repository_.verifyPassword(user, password))
    {
        throw common::AppException("INVALID_CREDENTIALS", "Username or password is invalid", drogon::k401Unauthorized);
    }

    const auto token = createSessionForUser(user);
    auto out = verify(token);
    out["token"] = token;
    return out;
}

Json::Value AuthService::registerUser(const std::string &username,
const std::string &password,
const std::string &email,
const std::string &referralCode)
{
    validatePasswordPolicy(password);
    auto user = repository_.createUser(username, password, email, referralCode);
    const auto token = createSessionForUser(user);
    auto out = verify(token);
    out["token"] = token;
    return out;
}

std::string AuthService::createSessionForUser(const Json::Value &user)
{
    const auto token = common::generateRequestId();
    const auto expiresAt = std::chrono::system_clock::now() + std::chrono::hours(24 * 7);
    {
        std::scoped_lock lock(mutex_);
        sessions_[token] = Session{
            .userId = user.get("id", "").asString(),
            .username = user.get("username", "").asString(),
            .roles = repository_.effectivePlatformRoles(user.get("id", "").asString()),
            .expiresAt = expiresAt,
            .expiresAtIso = toIso8601(expiresAt)};
        if (sessionRepository_)
        {
            sessionRepository_->save(token, sessionToJson(sessions_[token]));
        }
    }
    profileRepository_.updateStreak(user.get("id", "").asString());
    return token;
}

bool AuthService::logout(const std::string &token)
{
    std::scoped_lock lock(mutex_);
    const auto removedMemory = sessions_.erase(token) > 0;
    const auto removedPersisted = sessionRepository_ ? sessionRepository_->remove(token) : false;
    return removedMemory || removedPersisted;
}

Json::Value AuthService::verify(const std::string &token)
{
    std::scoped_lock lock(mutex_);
    auto it = sessions_.find(token);
    if (it == sessions_.end())
    {
        if (!sessionRepository_)
        {
            throw common::AppException("TOKEN_INVALID", "Token is invalid", drogon::k401Unauthorized);
        }
        const auto persisted = sessionRepository_->find(token);
        if (persisted.isNull())
        {
            throw common::AppException("TOKEN_INVALID", "Token is invalid", drogon::k401Unauthorized);
        }
        sessions_[token] = sessionFromJson(persisted);
        it = sessions_.find(token);
    }
    if (std::chrono::system_clock::now() > it->second.expiresAt)
    {
        sessions_.erase(it);
        if (sessionRepository_)
        {
            sessionRepository_->remove(token);
        }
        throw common::AppException("TOKEN_EXPIRED", "Token has expired", drogon::k401Unauthorized);
    }
    if (sessionRepository_)
    {
        sessionRepository_->save(token, sessionToJson(it->second));
    }
    const auto currentUser = repository_.findUserById(it->second.userId);
    if (currentUser.isNull() || currentUser.get("status", "active").asString() != "active")
    {
        sessions_.erase(it);
        if (sessionRepository_)
        {
            sessionRepository_->remove(token);
        }
        throw common::AppException("ACCOUNT_DISABLED", "This account is disabled", drogon::k403Forbidden);
    }
    it->second.roles = repository_.effectivePlatformRoles(it->second.userId);

    Json::Value out(Json::objectValue);
    out["user_id"] = it->second.userId;
    out["username"] = it->second.username;
    out["expires_at"] = it->second.expiresAtIso;
    out["roles"] = it->second.roles;
    return out;
}

void AuthService::requirePasswordReauthentication(const std::string &userId, const std::string &password) const
{
    const auto user = repository_.findUserById(userId);
    if (user.isNull() || user.get("status", "active").asString() != "active")
    {
        throw common::AppException("REAUTH_FAILED", "账号不可用，无法完成二次验证", drogon::k401Unauthorized);
    }
    const bool allowDevelopmentEmpty = developmentMode_ && password.empty() && allowsDevelopmentEmptyPassword(user);
    if (!allowDevelopmentEmpty && !repository_.verifyPassword(user, password))
    {
        throw common::AppException("REAUTH_FAILED", "当前密码验证失败", drogon::k401Unauthorized);
    }
}

int AuthService::revokeSessionsForUser(const std::string &userId, const std::string &keepToken)
{
    int removed = 0;
    {
        std::scoped_lock lock(mutex_);
        for (auto it = sessions_.begin(); it != sessions_.end();)
        {
            if (it->second.userId == userId && it->first != keepToken)
            {
                it = sessions_.erase(it);
                ++removed;
                continue;
            }
            ++it;
        }
    }
    if (sessionRepository_)
    {
        removed = (std::max)(removed, sessionRepository_->removeByUserId(userId, keepToken));
    }
    return removed;
}

Json::Value AuthService::changePassword(const std::string &userId,
const std::string &currentPassword,
const std::string &newPassword)
{
    validatePasswordPolicy(newPassword);
    const auto user = repository_.findUserById(userId);
    if (user.isNull())
    {
        throw common::AppException("USER_NOT_FOUND", "User not found", drogon::k404NotFound);
    }
    const auto algo = user.get("password_algo", "").asString();
    const auto hasPassword = algo == "sha256" || algo == "plain";
    if (hasPassword && !repository_.verifyPassword(user, currentPassword))
    {
        throw common::AppException("INVALID_CREDENTIALS", "Current password is invalid", drogon::k401Unauthorized);
    }
    const auto updated = repository_.updatePassword(userId, newPassword);
    Json::Value out(Json::objectValue);
    out["user_id"] = updated.get("id", "").asString();
    out["password_updated_at"] = updated.get("password_updated_at", common::nowIso8601()).asString();
    return out;
}

Json::Value AuthService::deactivateAccount(const std::string &userId, const std::string &reason)
{
    const auto updated = repository_.deactivateUser(userId, reason);
    const auto revokedSessions = revokeSessionsForUser(userId);
    Json::Value out(Json::objectValue);
    out["user_id"] = updated.get("id", "").asString();
    out["status"] = updated.get("status", "disabled").asString();
    out["deactivated_at"] = updated.get("deactivated_at", common::nowIso8601()).asString();
    out["revoked_sessions"] = revokedSessions;
    return out;
}

Json::Value AuthService::sendPasswordResetCode(const std::string &loginId)
{
    const auto user = repository_.findUserByLoginId(loginId);
    Json::Value out(Json::objectValue);
    out["sent"] = true;
    out["channel"] = "unknown";
    if (user.isNull())
    {
        // Do not reveal whether the account exists.
        return out;
    }

    const auto userId = user.get("id", "").asString();
    const auto email = user.get("email", "").asString();
    const auto phone = user.get("phone", "").asString();
    const auto now = std::chrono::system_clock::now();
    const auto code = generateSixDigitCode();

    {
        std::scoped_lock lock(mutex_);
        auto it = passwordResetCodes_.find(userId);
        if (it != passwordResetCodes_.end())
        {
            const auto elapsed = std::chrono::duration_cast<std::chrono::seconds>(now - it->second.sentAt).count();
            if (elapsed < 60)
            {
                throw common::AppException("RESET_RATE_LIMITED", "Please wait before requesting another code", drogon::k429TooManyRequests);
            }
        }
        passwordResetCodes_[userId] = PasswordResetCode{
            .userId = userId,
            .code = code,
            .sentAt = now,
            .expiresAt = now + std::chrono::minutes(10)};
    }

    if (!email.empty() && emailService_)
    {
        EmailMessage message;
        message.toAddress = email;
        message.subject = "Exam Online 密码重置验证码";
        message.textBody = "你的密码重置验证码是 " + code + "，10 分钟内有效。如果这不是你的操作，请忽略本邮件。";
        message.htmlBody = "<p>你的密码重置验证码是 <strong>" + code + "</strong>，10 分钟内有效。</p><p>如果这不是你的操作，请忽略本邮件。</p>";
        const auto delivery = emailService_->send(message);
        if (!delivery.delivered)
        {
            throw common::AppException("EMAIL_SEND_FAILED", delivery.errorMessage.empty() ? "Failed to send email" : delivery.errorMessage, drogon::k500InternalServerError);
        }
        out["channel"] = "email";
        if (developmentMode_)
        {
            out["debug_code"] = code;
        }
        return out;
    }

    if (!phone.empty() && smsService_)
    {
        SmsMessage message;
        message.to = phone;
        message.body = "【Exam Online】密码重置验证码：" + code + "，10 分钟内有效。";
        const auto delivery = smsService_->send(message);
        if (!delivery.delivered)
        {
            throw common::AppException("SMS_SEND_FAILED", delivery.errorMessage.empty() ? "Failed to send SMS" : delivery.errorMessage, drogon::k500InternalServerError);
        }
        out["channel"] = "phone";
        if (developmentMode_)
        {
            out["debug_code"] = code;
        }
        return out;
    }

    throw common::AppException("RESET_CONTACT_NOT_AVAILABLE", "No verified email or phone is available for password reset", drogon::k409Conflict);
}

Json::Value AuthService::resetPassword(const std::string &loginId,
const std::string &code,
const std::string &newPassword)
{
    validatePasswordPolicy(newPassword);
    const auto user = repository_.findUserByLoginId(loginId);
    if (user.isNull())
    {
        throw common::AppException("RESET_CODE_INVALID", "Reset code is invalid", drogon::k400BadRequest);
    }
    const auto userId = user.get("id", "").asString();
    {
        std::scoped_lock lock(mutex_);
        auto it = passwordResetCodes_.find(userId);
        if (it == passwordResetCodes_.end())
        {
            throw common::AppException("RESET_CODE_NOT_FOUND", "No reset code sent, or it has expired", drogon::k400BadRequest);
        }
        if (std::chrono::system_clock::now() > it->second.expiresAt)
        {
            passwordResetCodes_.erase(it);
            throw common::AppException("RESET_CODE_EXPIRED", "Reset code has expired", drogon::k400BadRequest);
        }
        if (it->second.code != code)
        {
            throw common::AppException("RESET_CODE_INVALID", "Reset code is invalid", drogon::k400BadRequest);
        }
        passwordResetCodes_.erase(it);
    }

    const auto updated = repository_.updatePassword(userId, newPassword);
    const auto token = createSessionForUser(updated);
    auto out = verify(token);
    out["token"] = token;
    return out;
}

bool AuthService::allowsDevelopmentEmptyPassword(const Json::Value &user)
{
            const auto algo = user.get("password_algo", "").asString();
            return algo == "wechat" || algo == "dev-empty" || !user.get("dev_login_id", "").asString().empty();
}

void AuthService::validatePasswordPolicy(const std::string &password)
{
    if (password.size() < 8)
    {
        throw common::AppException("WEAK_PASSWORD", "Password must be at least 8 characters", drogon::k422UnprocessableEntity);
    }
    bool hasLetter = false;
    bool hasDigit = false;
    for (const auto ch : password)
    {
        hasLetter = hasLetter || std::isalpha(static_cast<unsigned char>(ch));
        hasDigit = hasDigit || std::isdigit(static_cast<unsigned char>(ch));
    }
    if (!hasLetter || !hasDigit)
    {
        throw common::AppException("WEAK_PASSWORD", "Password must contain both letters and digits", drogon::k422UnprocessableEntity);
    }
}

std::string AuthService::toIso8601(std::chrono::system_clock::time_point timePoint)
{
    using namespace std::chrono;
    const auto secondsPart = time_point_cast<std::chrono::seconds>(timePoint);
    const auto ms = duration_cast<milliseconds>(timePoint - secondsPart).count();
    const auto timeValue = system_clock::to_time_t(timePoint);

    std::tm tm{};
#ifdef _WIN32
    gmtime_s(&tm, &timeValue);
#else
    gmtime_r(&timeValue, &tm);
#endif

    std::ostringstream oss;
    oss << std::put_time(&tm, "%Y-%m-%dT%H:%M:%S")
        << "." << std::setw(3) << std::setfill('0') << ms
        << "Z";
    return oss.str();
}

std::string AuthService::generateSixDigitCode()
{
    std::random_device rd;
    std::mt19937 gen(rd());
    std::uniform_int_distribution<int> dist(100000, 999999);
    return std::to_string(dist(gen));
}

std::int64_t AuthService::toEpochMillis(std::chrono::system_clock::time_point timePoint)
{
    return std::chrono::duration_cast<std::chrono::milliseconds>(timePoint.time_since_epoch()).count();
}

std::chrono::system_clock::time_point AuthService::fromEpochMillis(std::int64_t epochMillis)
{
    return std::chrono::system_clock::time_point{std::chrono::milliseconds(epochMillis)};
}

Json::Value AuthService::sessionToJson(const Session &session)
{
    Json::Value out(Json::objectValue);
    out["user_id"] = session.userId;
    out["username"] = session.username;
    out["roles"] = session.roles;
    out["expires_at"] = session.expiresAtIso;
    out["expires_at_epoch_ms"] = Json::Int64(toEpochMillis(session.expiresAt));
    out["last_seen_at"] = common::nowIso8601();
    return out;
}

AuthService::Session AuthService::sessionFromJson(const Json::Value &value)
{
    const auto expiresAtEpochMs = value.get("expires_at_epoch_ms", Json::Int64{0}).asInt64();
    const auto expiresAt = fromEpochMillis(expiresAtEpochMs);
    auto roles = value["roles"];
    if (!roles.isArray())
    {
        roles = Json::Value(Json::arrayValue);
    }
    return Session{
        .userId = value.get("user_id", "").asString(),
        .username = value.get("username", "").asString(),
        .roles = roles,
        .expiresAt = expiresAt,
        .expiresAtIso = value.get("expires_at", "").asString()};
}

}  // namespace application::services
