// Auto-generated by tools/sink_class.ps1 from AuthService.h
#include "AuthService.h"

#include <algorithm>
#include <cctype>
#include <random>
#include <vector>

#include <drogon/utils/Utilities.h>

namespace application::services
{
namespace
{
constexpr std::size_t kMaxSessionsPerUser = 10;
}

AuthService::AuthService(infrastructure::storage::UserRepository &repository,
infrastructure::storage::ProfileRepository &profileRepository,
bool developmentMode,
infrastructure::storage::SessionRepository *sessionRepository,
EmailService *emailService,
SmsService *smsService)
: repository_(repository),
  profileRepository_(profileRepository),
  sessionRepository_(sessionRepository),
  emailService_(emailService),
  smsService_(smsService),
  developmentMode_(developmentMode)
{
    if (sessionRepository_)
    {
        sessionRepository_->pruneExpired(toEpochMillis(std::chrono::system_clock::now()));
    }
}

Json::Value AuthService::login(const std::string &username,
                               const std::string &password,
                               const std::string &clientKey,
                               const std::string &userAgent)
{
    const auto accountKey = normalizeThrottleKey(username);
    enforceLoginThrottle(accountKey, clientKey);
    auto user = repository_.findUserByLoginId(username);
    if (user.isNull() && developmentMode_ && password.empty())
    {
        user = repository_.createDevelopmentUser(username);
    }

    if (user.isNull())
    {
        recordLoginFailure(accountKey, clientKey);
        throw common::AppException("INVALID_CREDENTIALS", "Username or password is invalid", drogon::k401Unauthorized);
    }
    if (user.get("status", "active").asString() != "active")
    {
        throw common::AppException("ACCOUNT_DISABLED", "This account is disabled", drogon::k403Forbidden);
    }

    const auto allowEmptyPassword = developmentMode_ && password.empty() && allowsDevelopmentEmptyPassword(user);
    if (!allowEmptyPassword && !repository_.verifyPassword(user, password))
    {
        recordLoginFailure(accountKey, clientKey);
        throw common::AppException("INVALID_CREDENTIALS", "Username or password is invalid", drogon::k401Unauthorized);
    }

    recordLoginSuccess(accountKey);
    const auto token = createSessionForUser(user, clientKey, userAgent);
    auto out = verify(token);
    out["token"] = token;
    return out;
}

Json::Value AuthService::registerUser(const std::string &username,
const std::string &password,
const std::string &email,
const std::string &referralCode,
const std::string &clientKey,
const std::string &userAgent)
{
    validatePasswordPolicy(password);
    auto user = repository_.createUser(username, password, email, referralCode);
    const auto token = createSessionForUser(user, clientKey, userAgent);
    auto out = verify(token);
    out["token"] = token;
    return out;
}

std::string AuthService::createSessionForUser(const Json::Value &user,
                                              const std::string &clientKey,
                                              const std::string &userAgent)
{
    const auto token = common::generateRequestId();
    const auto createdAt = common::nowIso8601();
    const auto expiresAt = std::chrono::system_clock::now() + std::chrono::hours(24 * 7);
    {
        std::scoped_lock lock(mutex_);
        sessions_[token] = Session{
            .userId = user.get("id", "").asString(),
            .username = user.get("username", "").asString(),
            .roles = repository_.effectivePlatformRoles(user.get("id", "").asString()),
            .expiresAt = expiresAt,
            .expiresAtIso = toIso8601(expiresAt),
            .createdAtIso = createdAt,
            .lastSeenAtIso = createdAt,
            .clientIp = clientKey,
            .userAgent = userAgent};
        if (sessionRepository_)
        {
            sessionRepository_->save(token, sessionToJson(sessions_[token]));
            sessionRepository_->trimByUserId(
                user.get("id", "").asString(),
                kMaxSessionsPerUser,
                drogon::utils::getSha256(token));
        }
        std::vector<std::pair<std::string, std::chrono::system_clock::time_point>> userSessions;
        for (const auto &[existingToken, session] : sessions_)
        {
            if (session.userId == user.get("id", "").asString())
            {
                userSessions.emplace_back(existingToken, session.expiresAt);
            }
        }
        std::sort(userSessions.begin(), userSessions.end(), [](const auto &left, const auto &right) {
            return left.second > right.second;
        });
        for (std::size_t index = kMaxSessionsPerUser; index < userSessions.size(); ++index)
        {
            sessions_.erase(userSessions[index].first);
        }
    }
    profileRepository_.updateStreak(user.get("id", "").asString());
    return token;
}

bool AuthService::logout(const std::string &token)
{
    std::scoped_lock lock(mutex_);
    const auto removedMemory = sessions_.erase(token) > 0;
    const auto removedPersisted = sessionRepository_ ? sessionRepository_->remove(token) : false;
    return removedMemory || removedPersisted;
}

Json::Value AuthService::verify(const std::string &token)
{
    std::scoped_lock lock(mutex_);
    auto it = sessions_.find(token);
    if (it == sessions_.end())
    {
        if (!sessionRepository_)
        {
            throw common::AppException("TOKEN_INVALID", "Token is invalid", drogon::k401Unauthorized);
        }
        const auto persisted = sessionRepository_->find(token);
        if (persisted.isNull())
        {
            throw common::AppException("TOKEN_INVALID", "Token is invalid", drogon::k401Unauthorized);
        }
        sessions_[token] = sessionFromJson(persisted);
        it = sessions_.find(token);
    }
    if (std::chrono::system_clock::now() > it->second.expiresAt)
    {
        sessions_.erase(it);
        if (sessionRepository_)
        {
            sessionRepository_->remove(token);
        }
        throw common::AppException("TOKEN_EXPIRED", "Token has expired", drogon::k401Unauthorized);
    }
    const auto currentUser = repository_.findUserById(it->second.userId);
    if (currentUser.isNull() || currentUser.get("status", "active").asString() != "active")
    {
        sessions_.erase(it);
        if (sessionRepository_)
        {
            sessionRepository_->remove(token);
        }
        throw common::AppException("ACCOUNT_DISABLED", "This account is disabled", drogon::k403Forbidden);
    }
    it->second.roles = repository_.effectivePlatformRoles(it->second.userId);
    it->second.lastSeenAtIso = common::nowIso8601();
    if (sessionRepository_)
    {
        sessionRepository_->save(token, sessionToJson(it->second));
    }

    Json::Value out(Json::objectValue);
    out["user_id"] = it->second.userId;
    out["username"] = it->second.username;
    out["expires_at"] = it->second.expiresAtIso;
    out["roles"] = it->second.roles;
    return out;
}

Json::Value AuthService::sessionsForUser(const std::string &userId, const std::string &currentToken)
{
    const auto currentSessionId = drogon::utils::getSha256(currentToken);
    Json::Value sessions(Json::arrayValue);
    if (sessionRepository_)
    {
        sessionRepository_->pruneExpired(toEpochMillis(std::chrono::system_clock::now()));
        sessionRepository_->trimByUserId(
            userId,
            kMaxSessionsPerUser,
            currentSessionId);
        sessions = sessionRepository_->listByUserId(userId);
    }
    else
    {
        std::scoped_lock lock(mutex_);
        for (const auto &[token, session] : sessions_)
        {
            if (session.userId != userId) continue;
            auto entry = sessionToJson(session);
            entry["token_hash"] = drogon::utils::getSha256(token);
            sessions.append(entry);
        }
    }

    Json::Value out(Json::arrayValue);
    for (const auto &entry : sessions)
    {
        const auto sessionId = entry.get("token_hash", "").asString();
        if (sessionId.empty()) continue;
        Json::Value item(Json::objectValue);
        item["session_id"] = sessionId;
        item["current"] = sessionId == currentSessionId;
        item["created_at"] = entry.get("created_at", "").asString();
        item["last_seen_at"] = entry.get("last_seen_at", "").asString();
        item["expires_at"] = entry.get("expires_at", "").asString();
        item["client_ip"] = entry.get("client_ip", "").asString();
        item["user_agent"] = entry.get("user_agent", "").asString();
        out.append(item);
    }
    return out;
}

bool AuthService::revokeSessionForUser(const std::string &userId,
                                       const std::string &sessionId,
                                       const std::string &currentToken)
{
    if (sessionId.empty() || sessionId == drogon::utils::getSha256(currentToken))
    {
        return false;
    }
    bool removed = false;
    {
        std::scoped_lock lock(mutex_);
        for (auto it = sessions_.begin(); it != sessions_.end();)
        {
            if (it->second.userId == userId &&
                drogon::utils::getSha256(it->first) == sessionId)
            {
                it = sessions_.erase(it);
                removed = true;
                continue;
            }
            ++it;
        }
    }
    if (sessionRepository_)
    {
        removed = sessionRepository_->removeById(userId, sessionId) || removed;
    }
    return removed;
}

void AuthService::requirePasswordReauthentication(const std::string &userId, const std::string &password)
{
    const auto throttleKey = "reauth:" + normalizeThrottleKey(userId);
    enforceLoginThrottle(throttleKey, "");
    const auto user = repository_.findUserById(userId);
    if (user.isNull() || user.get("status", "active").asString() != "active")
    {
        throw common::AppException("REAUTH_FAILED", "账号不可用，无法完成二次验证", drogon::k401Unauthorized);
    }
    const bool allowDevelopmentEmpty = developmentMode_ && password.empty() && allowsDevelopmentEmptyPassword(user);
    if (!allowDevelopmentEmpty && !repository_.verifyPassword(user, password))
    {
        recordLoginFailure(throttleKey, "");
        throw common::AppException("REAUTH_FAILED", "当前密码验证失败", drogon::k401Unauthorized);
    }
    recordLoginSuccess(throttleKey);
}

int AuthService::revokeSessionsForUser(const std::string &userId, const std::string &keepToken)
{
    int removed = 0;
    {
        std::scoped_lock lock(mutex_);
        for (auto it = sessions_.begin(); it != sessions_.end();)
        {
            if (it->second.userId == userId && it->first != keepToken)
            {
                it = sessions_.erase(it);
                ++removed;
                continue;
            }
            ++it;
        }
    }
    if (sessionRepository_)
    {
        removed = (std::max)(removed, sessionRepository_->removeByUserId(userId, keepToken));
    }
    return removed;
}

Json::Value AuthService::changePassword(const std::string &userId,
const std::string &currentPassword,
const std::string &newPassword)
{
    validatePasswordPolicy(newPassword);
    const auto user = repository_.findUserById(userId);
    if (user.isNull())
    {
        throw common::AppException("USER_NOT_FOUND", "User not found", drogon::k404NotFound);
    }
    const auto algo = user.get("password_algo", "").asString();
    const auto hasPassword = algo == "scrypt" || algo == "sha256" || algo == "plain";
    if (hasPassword && !repository_.verifyPassword(user, currentPassword))
    {
        throw common::AppException("INVALID_CREDENTIALS", "Current password is invalid", drogon::k401Unauthorized);
    }
    const auto updated = repository_.updatePassword(userId, newPassword);
    Json::Value out(Json::objectValue);
    out["user_id"] = updated.get("id", "").asString();
    out["password_updated_at"] = updated.get("password_updated_at", common::nowIso8601()).asString();
    return out;
}

Json::Value AuthService::deactivateAccount(const std::string &userId, const std::string &reason)
{
    const auto updated = repository_.deactivateUser(userId, reason);
    const auto revokedSessions = revokeSessionsForUser(userId);
    Json::Value out(Json::objectValue);
    out["user_id"] = updated.get("id", "").asString();
    out["status"] = updated.get("status", "disabled").asString();
    out["deactivated_at"] = updated.get("deactivated_at", common::nowIso8601()).asString();
    out["revoked_sessions"] = revokedSessions;
    return out;
}

Json::Value AuthService::sendPasswordResetCode(const std::string &loginId,
                                               const std::string &clientKey)
{
    consumePasswordResetRequest(normalizeThrottleKey(loginId), clientKey);
    const auto user = repository_.findUserByLoginId(loginId);
    Json::Value out(Json::objectValue);
    out["sent"] = true;
    out["channel"] = "unknown";
    if (user.isNull())
    {
        // Do not reveal whether the account exists.
        return out;
    }

    const auto userId = user.get("id", "").asString();
    const auto email = user.get("email", "").asString();
    const auto phone = user.get("phone", "").asString();
    const auto now = std::chrono::system_clock::now();
    const auto code = generateSixDigitCode();

    {
        std::scoped_lock lock(mutex_);
        auto it = passwordResetCodes_.find(userId);
        if (it != passwordResetCodes_.end())
        {
            const auto elapsed = std::chrono::duration_cast<std::chrono::seconds>(now - it->second.sentAt).count();
            if (elapsed < 60)
            {
                throw common::AppException("RESET_RATE_LIMITED", "Please wait before requesting another code", drogon::k429TooManyRequests);
            }
        }
        passwordResetCodes_[userId] = PasswordResetCode{
            .userId = userId,
            .code = code,
            .sentAt = now,
            .expiresAt = now + std::chrono::minutes(10),
            .failedAttempts = 0};
    }

    if (!email.empty() && emailService_)
    {
        EmailMessage message;
        message.toAddress = email;
        message.subject = "Exam Online 密码重置验证码";
        message.textBody = "你的密码重置验证码是 " + code + "，10 分钟内有效。如果这不是你的操作，请忽略本邮件。";
        message.htmlBody = "<p>你的密码重置验证码是 <strong>" + code + "</strong>，10 分钟内有效。</p><p>如果这不是你的操作，请忽略本邮件。</p>";
        const auto delivery = emailService_->send(message);
        if (!delivery.delivered)
        {
            throw common::AppException("EMAIL_SEND_FAILED", delivery.errorMessage.empty() ? "Failed to send email" : delivery.errorMessage, drogon::k500InternalServerError);
        }
        out["channel"] = "email";
        if (developmentMode_)
        {
            out["debug_code"] = code;
        }
        return out;
    }

    if (!phone.empty() && smsService_)
    {
        SmsMessage message;
        message.to = phone;
        message.body = "【Exam Online】密码重置验证码：" + code + "，10 分钟内有效。";
        const auto delivery = smsService_->send(message);
        if (!delivery.delivered)
        {
            throw common::AppException("SMS_SEND_FAILED", delivery.errorMessage.empty() ? "Failed to send SMS" : delivery.errorMessage, drogon::k500InternalServerError);
        }
        out["channel"] = "phone";
        if (developmentMode_)
        {
            out["debug_code"] = code;
        }
        return out;
    }

    throw common::AppException("RESET_CONTACT_NOT_AVAILABLE", "No verified email or phone is available for password reset", drogon::k409Conflict);
}

Json::Value AuthService::resetPassword(const std::string &loginId,
const std::string &code,
const std::string &newPassword)
{
    validatePasswordPolicy(newPassword);
    const auto user = repository_.findUserByLoginId(loginId);
    if (user.isNull())
    {
        throw common::AppException("RESET_CODE_INVALID", "Reset code is invalid", drogon::k400BadRequest);
    }
    const auto userId = user.get("id", "").asString();
    {
        std::scoped_lock lock(mutex_);
        auto it = passwordResetCodes_.find(userId);
        if (it == passwordResetCodes_.end())
        {
            throw common::AppException("RESET_CODE_NOT_FOUND", "No reset code sent, or it has expired", drogon::k400BadRequest);
        }
        if (std::chrono::system_clock::now() > it->second.expiresAt)
        {
            passwordResetCodes_.erase(it);
            throw common::AppException("RESET_CODE_EXPIRED", "Reset code has expired", drogon::k400BadRequest);
        }
        if (it->second.code != code)
        {
            ++it->second.failedAttempts;
            if (it->second.failedAttempts >= 5)
            {
                passwordResetCodes_.erase(it);
                throw common::AppException(
                    "RESET_CODE_ATTEMPTS_EXCEEDED",
                    "Too many invalid reset code attempts; request a new code",
                    drogon::k429TooManyRequests);
            }
            throw common::AppException("RESET_CODE_INVALID", "Reset code is invalid", drogon::k400BadRequest);
        }
        passwordResetCodes_.erase(it);
    }

    const auto updated = repository_.updatePassword(userId, newPassword);
    const auto token = createSessionForUser(updated);
    auto out = verify(token);
    out["token"] = token;
    return out;
}

bool AuthService::allowsDevelopmentEmptyPassword(const Json::Value &user)
{
            const auto algo = user.get("password_algo", "").asString();
            return algo == "wechat" || algo == "dev-empty" || !user.get("dev_login_id", "").asString().empty();
}

std::string AuthService::normalizeThrottleKey(const std::string &value)
{
    std::string normalized;
    normalized.reserve(value.size());
    for (const auto ch : value)
    {
        if (!std::isspace(static_cast<unsigned char>(ch)))
        {
            normalized.push_back(static_cast<char>(std::tolower(static_cast<unsigned char>(ch))));
        }
    }
    return normalized.empty() ? "unknown" : normalized;
}

void AuthService::enforceLoginThrottle(const std::string &accountKey, const std::string &clientKey)
{
    const auto now = std::chrono::system_clock::now();
    std::scoped_lock lock(mutex_);
    const auto enforceOne = [&](const std::string &key) {
        if (key.empty())
        {
            return;
        }
        const auto it = loginFailureWindows_.find(key);
        if (it != loginFailureWindows_.end() && now < it->second.blockedUntil)
        {
            throw common::AppException(
                "AUTH_RATE_LIMITED",
                "Too many authentication attempts; please try again later",
                drogon::k429TooManyRequests);
        }
    };
    enforceOne("account:" + accountKey);
    if (!clientKey.empty())
    {
        enforceOne("client:" + clientKey);
    }
}

void AuthService::recordLoginFailure(const std::string &accountKey, const std::string &clientKey)
{
    const auto now = std::chrono::system_clock::now();
    constexpr auto window = std::chrono::minutes(15);
    constexpr auto blockDuration = std::chrono::minutes(15);
    bool blocked = false;
    std::scoped_lock lock(mutex_);
    const auto recordOne = [&](const std::string &key, int maximumFailures) {
        if (key.empty())
        {
            return;
        }
        auto &state = loginFailureWindows_[key];
        if (state.windowStartedAt.time_since_epoch().count() == 0 ||
            now - state.windowStartedAt >= window)
        {
            state.failures = 0;
            state.windowStartedAt = now;
            state.blockedUntil = {};
        }
        ++state.failures;
        if (state.failures >= maximumFailures)
        {
            state.blockedUntil = now + blockDuration;
            blocked = true;
        }
    };
    recordOne("account:" + accountKey, 5);
    if (!clientKey.empty())
    {
        recordOne("client:" + clientKey, 20);
    }
    if (blocked)
    {
        throw common::AppException(
            "AUTH_RATE_LIMITED",
            "Too many authentication attempts; please try again later",
            drogon::k429TooManyRequests);
    }
}

void AuthService::recordLoginSuccess(const std::string &accountKey)
{
    std::scoped_lock lock(mutex_);
    loginFailureWindows_.erase("account:" + accountKey);
}

void AuthService::consumePasswordResetRequest(const std::string &accountKey,
                                              const std::string &clientKey)
{
    const auto now = std::chrono::system_clock::now();
    constexpr auto window = std::chrono::hours(1);
    std::scoped_lock lock(mutex_);
    const auto consumeOne = [&](const std::string &key, int maximumRequests, bool cooldown) {
        if (key.empty())
        {
            return;
        }
        auto &state = passwordResetRequestWindows_[key];
        if (state.windowStartedAt.time_since_epoch().count() == 0 ||
            now - state.windowStartedAt >= window)
        {
            state.requests = 0;
            state.windowStartedAt = now;
            state.lastRequestAt = {};
        }
        if (cooldown && state.lastRequestAt.time_since_epoch().count() != 0 &&
            now - state.lastRequestAt < std::chrono::minutes(1))
        {
            throw common::AppException(
                "RESET_RATE_LIMITED",
                "Please wait before requesting another code",
                drogon::k429TooManyRequests);
        }
        if (state.requests >= maximumRequests)
        {
            throw common::AppException(
                "RESET_RATE_LIMITED",
                "Too many password reset requests; please try again later",
                drogon::k429TooManyRequests);
        }
        ++state.requests;
        state.lastRequestAt = now;
    };
    consumeOne("reset-account:" + accountKey, 5, true);
    if (!clientKey.empty())
    {
        consumeOne("reset-client:" + clientKey, 20, false);
    }
}

void AuthService::validatePasswordPolicy(const std::string &password)
{
    if (password.size() < 8)
    {
        throw common::AppException("WEAK_PASSWORD", "Password must be at least 8 characters", drogon::k422UnprocessableEntity);
    }
    bool hasLetter = false;
    bool hasDigit = false;
    for (const auto ch : password)
    {
        hasLetter = hasLetter || std::isalpha(static_cast<unsigned char>(ch));
        hasDigit = hasDigit || std::isdigit(static_cast<unsigned char>(ch));
    }
    if (!hasLetter || !hasDigit)
    {
        throw common::AppException("WEAK_PASSWORD", "Password must contain both letters and digits", drogon::k422UnprocessableEntity);
    }
}

std::string AuthService::toIso8601(std::chrono::system_clock::time_point timePoint)
{
    using namespace std::chrono;
    const auto secondsPart = time_point_cast<std::chrono::seconds>(timePoint);
    const auto ms = duration_cast<milliseconds>(timePoint - secondsPart).count();
    const auto timeValue = system_clock::to_time_t(timePoint);

    std::tm tm{};
#ifdef _WIN32
    gmtime_s(&tm, &timeValue);
#else
    gmtime_r(&timeValue, &tm);
#endif

    std::ostringstream oss;
    oss << std::put_time(&tm, "%Y-%m-%dT%H:%M:%S")
        << "." << std::setw(3) << std::setfill('0') << ms
        << "Z";
    return oss.str();
}

std::string AuthService::generateSixDigitCode()
{
    std::random_device rd;
    std::mt19937 gen(rd());
    std::uniform_int_distribution<int> dist(100000, 999999);
    return std::to_string(dist(gen));
}

std::int64_t AuthService::toEpochMillis(std::chrono::system_clock::time_point timePoint)
{
    return std::chrono::duration_cast<std::chrono::milliseconds>(timePoint.time_since_epoch()).count();
}

std::chrono::system_clock::time_point AuthService::fromEpochMillis(std::int64_t epochMillis)
{
    return std::chrono::system_clock::time_point{std::chrono::milliseconds(epochMillis)};
}

Json::Value AuthService::sessionToJson(const Session &session)
{
    Json::Value out(Json::objectValue);
    out["user_id"] = session.userId;
    out["username"] = session.username;
    out["roles"] = session.roles;
    out["expires_at"] = session.expiresAtIso;
    out["expires_at_epoch_ms"] = Json::Int64(toEpochMillis(session.expiresAt));
    out["created_at"] = session.createdAtIso;
    out["last_seen_at"] = session.lastSeenAtIso;
    out["client_ip"] = session.clientIp;
    out["user_agent"] = session.userAgent;
    return out;
}

AuthService::Session AuthService::sessionFromJson(const Json::Value &value)
{
    const auto expiresAtEpochMs = value.get("expires_at_epoch_ms", Json::Int64{0}).asInt64();
    const auto expiresAt = fromEpochMillis(expiresAtEpochMs);
    auto roles = value["roles"];
    if (!roles.isArray())
    {
        roles = Json::Value(Json::arrayValue);
    }
    return Session{
        .userId = value.get("user_id", "").asString(),
        .username = value.get("username", "").asString(),
        .roles = roles,
        .expiresAt = expiresAt,
        .expiresAtIso = value.get("expires_at", "").asString(),
        .createdAtIso = value.get("created_at", value.get("last_seen_at", "")).asString(),
        .lastSeenAtIso = value.get("last_seen_at", "").asString(),
        .clientIp = value.get("client_ip", "").asString(),
        .userAgent = value.get("user_agent", "").asString()};
}

}  // namespace application::services
