// Auto-generated by tools/sink_class.ps1 from OrganizationService.h
#include "OrganizationService.h"

namespace application::services
{

OrganizationService::OrganizationService(infrastructure::storage::OrganizationRepository &organizationRepository,
infrastructure::storage::UserRepository &userRepository,
SubscriptionService &subscriptionService,
SmsService &smsService,
EmailService &emailService,
std::string publicWebBaseUrl)
: organizationRepository_(organizationRepository),
userRepository_(userRepository),
subscriptionService_(subscriptionService),
smsService_(smsService),
emailService_(emailService),
publicWebBaseUrl_(std::move(publicWebBaseUrl))
{
}

Json::Value OrganizationService::listOrganizationsForUser(const std::string &userId, bool includeAll) const
{
    const auto organizations = includeAll ? organizationRepository_.allOrganizationsArray()
                                          : organizationRepository_.listOrganizationsForUser(userId);
    Json::Value out(Json::arrayValue);
    for (const auto &organization : organizations)
    {
        out.append(enrichOrganization(organization));
    }
    return out;
}

Json::Value OrganizationService::getOrganization(const std::string &organizationId) const
{
    return enrichOrganization(requireOrganization(organizationId));
}

Json::Value OrganizationService::createOrganization(const std::string &actorUserId, const Json::Value &payload)
{
    const auto actor = userRepository_.findUserById(actorUserId);
    if (actor.isNull())
    {
        throw common::AppException("USER_NOT_FOUND", "User not found: " + actorUserId, drogon::k404NotFound);
    }

    const auto name = payload.get("name", "").asString();
    if (name.empty())
    {
        throw common::AppException("VALIDATION_ERROR", "Missing field: name", drogon::k422UnprocessableEntity);
    }

    const auto organizationType = normalizeOrganizationType(payload.get("organization_type", "").asString());
    if (organizationType.empty())
    {
        throw common::AppException("VALIDATION_ERROR", "organization_type must be business or school", drogon::k422UnprocessableEntity);
    }

    const auto organizationId = payload.get("organization_id", "").asString().empty()
                                    ? generateOrganizationId()
                                    : payload.get("organization_id", "").asString();

    Json::Value organization(Json::objectValue);
    organization["organization_id"] = organizationId;
    organization["name"] = name;
    organization["organization_type"] = organizationType;
    organization["created_by"] = actorUserId;
    organization["created_at"] = common::nowIso8601();

    Json::Value subscription(Json::objectValue);
    subscription["plan"] = payload.get("plan", "free").asString();
    subscription["status"] = payload.get("status", "active").asString();
    subscription["expires_at"] = payload.get("expires_at", "").asString();
    subscription["seats"] = payload.get("seats", 0).asInt();
    organization["subscription"] = subscription;

    auto savedOrganization = organizationRepository_.upsertOrganization(organization);

    Json::Value membership(Json::objectValue);
    membership["user_id"] = actorUserId;
    membership["scope_type"] = "organization";
    membership["scope_id"] = organizationId;
    membership["organization_type"] = organizationType;
    const auto ownerRoles = normalizeMemberRoles(payload.isMember("owner_roles") ? payload["owner_roles"] : defaultOwnerRoles());
    membership["roles"] = ownerRoles;
    membership["permission_templates"] = normalizePermissionTemplates(payload.get("permission_templates", Json::Value(Json::arrayValue)), ownerRoles);
    membership["permission_overrides"] = normalizePermissionOverrides(payload.get("permission_overrides", Json::Value(Json::arrayValue)));
    membership = assignBusinessNumbers(savedOrganization, membership, Json::Value(Json::nullValue));
    organizationRepository_.upsertMembership(membership);

    savedOrganization = appendAuditEntry(
        savedOrganization,
        createAuditEntry(
            actorUserId,
            "organization.created",
            "创建组织",
            [&] {
                Json::Value details(Json::objectValue);
                details["organization_id"] = organizationId;
                details["organization_type"] = organizationType;
                details["plan"] = savedOrganization["subscription"].get("plan", "free").asString();
                details["seats"] = savedOrganization["subscription"].get("seats", 0).asInt();
                return details;
            }()));
    savedOrganization = organizationRepository_.upsertOrganization(savedOrganization);

    return enrichOrganization(savedOrganization);
}

Json::Value OrganizationService::listMembers(const std::string &organizationId) const
{
    requireOrganization(organizationId);
    Json::Value out(Json::arrayValue);
    const auto members = organizationRepository_.listMembershipsForScope(organizationId);
    for (const auto &member : members)
    {
        out.append(enrichMembership(member));
    }
    return out;
}

Json::Value OrganizationService::createInvitation(const std::string &actorUserId, const std::string &organizationId, const Json::Value &payload)
{
    auto organization = requireOrganization(organizationId);
    const auto contact = extractInvitationContact(payload);
    const auto roles = normalizeMemberRoles(payload.isMember("roles") ? payload["roles"] : defaultMemberRoles());
    const auto permissionTemplates = normalizePermissionTemplates(payload.get("permission_templates", Json::Value(Json::arrayValue)), roles);
    const auto permissionOverrides = normalizePermissionOverrides(payload.get("permission_overrides", Json::Value(Json::arrayValue)));
    const auto targetUser = findUserByInvitationContact(contact);
    const auto targetUserId = targetUser.isNull() ? std::string("") : targetUser.get("id", "").asString();
    if (!targetUserId.empty() && !organizationRepository_.findMembership(targetUserId, organizationId).isNull())
    {
        throw common::AppException("ALREADY_MEMBER", "This contact already belongs to the organization", drogon::k409Conflict);
    }

    const auto normalizedContact = contact.value;
    for (const auto &invitation : organization["invitations"])
    {
        if (invitation.get("status", "pending").asString() != "pending")
        {
            continue;
        }
        if (invitation.get("channel", "").asString() == contact.channel && invitation.get("contact", "").asString() == normalizedContact)
        {
            throw common::AppException("INVITATION_EXISTS", "A pending invitation already exists for this contact", drogon::k409Conflict);
        }
    }

    Json::Value invitation(Json::objectValue);
    invitation["invitation_id"] = common::generateOpaqueId("oinv_");
    invitation["invite_code"] = generateInvitationCode();
    invitation["organization_id"] = organizationId;
    invitation["organization_name"] = organization.get("name", "").asString();
    invitation["channel"] = contact.channel;
    invitation["contact"] = normalizedContact;
    invitation["email"] = contact.channel == "email" ? normalizedContact : "";
    invitation["phone"] = contact.channel == "phone" ? normalizedContact : "";
    invitation["target_user_id"] = targetUserId;
    invitation["status"] = "pending";
    invitation["roles"] = roles;
    invitation["permission_templates"] = permissionTemplates;
    invitation["permission_overrides"] = permissionOverrides;
    invitation["member_no"] = payload.get("member_no", "").asString();
    invitation["student_no"] = payload.get("student_no", "").asString();
    invitation["employee_no"] = payload.get("employee_no", "").asString();
    invitation["message"] = payload.get("message", "").asString();
    invitation["created_by"] = actorUserId;
    invitation["created_at"] = common::nowIso8601();
    invitation["expires_at"] = payload.get("expires_at", defaultInvitationExpiresAt()).asString();
    invitation["delivery_status"] = "pending";
    invitation["delivery_provider"] = "";
    invitation["delivery_message_id"] = "";
    invitation["delivery_error"] = "";
    invitation["delivered_at"] = "";

    organization = prependInvitation(organization, invitation);
    organization = appendAuditEntry(
        organization,
        createAuditEntry(
            actorUserId,
            "invitation.created",
            "创建组织邀请",
            [&] {
                Json::Value details(Json::objectValue);
                details["invitation_id"] = invitation["invitation_id"].asString();
                details["invite_code"] = invitation["invite_code"].asString();
                details["channel"] = contact.channel;
                details["contact"] = normalizedContact;
                details["roles"] = roles;
                details["permission_templates"] = permissionTemplates;
                details["permission_overrides"] = permissionOverrides;
                return details;
            }()));
    organization = organizationRepository_.upsertOrganization(organization);

    const auto delivery = deliverInvitation(organization, invitation);
    invitation = mergeInvitationDelivery(invitation, delivery);
    organization = replaceInvitation(organization, invitation);
    organization = appendAuditEntry(
        organization,
        createAuditEntry(
            actorUserId,
            delivery.delivered ? "invitation.delivered" : "invitation.delivery_failed",
            delivery.delivered ? "发送组织邀请" : "组织邀请发送失败",
            [&] {
                Json::Value details(Json::objectValue);
                details["invitation_id"] = invitation["invitation_id"].asString();
                details["invite_code"] = invitation["invite_code"].asString();
                details["channel"] = contact.channel;
                details["contact"] = normalizedContact;
                details["delivery_status"] = invitation.get("delivery_status", "pending").asString();
                details["delivery_provider"] = invitation.get("delivery_provider", "").asString();
                if (!invitation.get("delivery_error", "").asString().empty())
                {
                    details["delivery_error"] = invitation.get("delivery_error", "").asString();
                }
                return details;
            }()));
    organization = organizationRepository_.upsertOrganization(organization);
    return invitation;
}

void OrganizationService::cancelInvitation(const std::string &actorUserId, const std::string &organizationId, const std::string &invitationId)
{
    auto organization = requireOrganization(organizationId);
    auto invitations = organization.get("invitations", Json::Value(Json::arrayValue));
    bool found = false;
    for (Json::ArrayIndex index = 0; index < invitations.size(); ++index)
    {
        auto &invitation = invitations[index];
        if (invitation.get("invitation_id", "").asString() != invitationId)
        {
            continue;
        }
        found = true;
        if (invitation.get("status", "pending").asString() != "pending")
        {
            throw common::AppException("INVITATION_INVALID", "Only pending invitations can be cancelled", drogon::k409Conflict);
        }
        invitation["status"] = "cancelled";
        invitation["cancelled_at"] = common::nowIso8601();
        invitation["cancelled_by"] = actorUserId;
        organization["invitations"] = invitations;
        organization = appendAuditEntry(
            organization,
            createAuditEntry(
                actorUserId,
                "invitation.cancelled",
                "取消组织邀请",
                [&] {
                    Json::Value details(Json::objectValue);
                    details["invitation_id"] = invitationId;
                    details["invite_code"] = invitation.get("invite_code", "").asString();
                    details["contact"] = invitation.get("contact", "").asString();
                    return details;
                }()));
        organizationRepository_.upsertOrganization(organization);
        return;
    }
    if (!found)
    {
        throw common::AppException("INVITATION_NOT_FOUND", "Invitation not found", drogon::k404NotFound);
    }
}

Json::Value OrganizationService::acceptInvitation(const std::string &actorUserId, const std::string &inviteCode)
{
    const auto actor = userRepository_.findUserById(actorUserId);
    if (actor.isNull())
    {
        throw common::AppException("USER_NOT_FOUND", "User not found: " + actorUserId, drogon::k404NotFound);
    }

    const auto organizations = organizationRepository_.allOrganizationsArray();
    for (const auto &organizationValue : organizations)
    {
        auto organization = requireOrganization(organizationValue.get("organization_id", organizationValue.get("scope_id", "")).asString());
        auto invitations = organization.get("invitations", Json::Value(Json::arrayValue));
        for (Json::ArrayIndex index = 0; index < invitations.size(); ++index)
        {
            auto invitation = invitations[index];
            if (invitation.get("invite_code", "").asString() != inviteCode)
            {
                continue;
            }
            if (invitation.get("status", "pending").asString() != "pending")
            {
                throw common::AppException("INVITATION_INVALID", "Invitation is no longer pending", drogon::k409Conflict);
            }
            if (isExpiredIso8601(invitation.get("expires_at", "").asString()))
            {
                throw common::AppException("INVITATION_EXPIRED", "Invitation has expired", drogon::k409Conflict);
            }
            const auto targetUserId = invitation.get("target_user_id", "").asString();
            if (!targetUserId.empty() && targetUserId != actorUserId)
            {
                throw common::AppException("INVITATION_FORBIDDEN", "Invitation belongs to another account", drogon::k403Forbidden);
            }
            ensureInvitationContactVerified(actor, invitation);
            const auto organizationId = organization.get("organization_id", "").asString();
            if (!organizationRepository_.findMembership(actorUserId, organizationId).isNull())
            {
                throw common::AppException("ALREADY_MEMBER", "You already belong to this organization", drogon::k409Conflict);
            }
            const auto subscription = subscriptionService_.subscriptionForOrganization(organizationId);
            const auto seats = subscription.get("seats", 0).asInt();
            if (seats > 0 && organizationRepository_.memberCount(organizationId) >= seats)
            {
                throw common::AppException("ORGANIZATION_SEATS_FULL", "Organization seat limit reached", drogon::k409Conflict);
            }

            Json::Value membership(Json::objectValue);
            membership["user_id"] = actorUserId;
            membership["scope_type"] = "organization";
            membership["scope_id"] = organizationId;
            membership["organization_type"] = organization.get("organization_type", "business").asString();
            membership["roles"] = normalizeMemberRoles(invitation.get("roles", defaultMemberRoles()));
            membership["permission_templates"] = normalizePermissionTemplates(invitation.get("permission_templates", Json::Value(Json::arrayValue)), membership["roles"]);
            membership["permission_overrides"] = normalizePermissionOverrides(invitation.get("permission_overrides", Json::Value(Json::arrayValue)));
            membership["joined_at"] = common::nowIso8601();
            membership["member_no"] = invitation.get("member_no", "").asString();
            membership["student_no"] = invitation.get("student_no", "").asString();
            membership["employee_no"] = invitation.get("employee_no", "").asString();
            membership = assignBusinessNumbers(organization, membership, Json::Value(Json::nullValue));
            auto savedMembership = organizationRepository_.upsertMembership(membership);

            invitation["status"] = "accepted";
            invitation["accepted_by"] = actorUserId;
            invitation["accepted_at"] = common::nowIso8601();
            invitations[index] = invitation;
            organization["invitations"] = invitations;
            organization = appendAuditEntry(
                organization,
                createAuditEntry(
                    actorUserId,
                    "invitation.accepted",
                    "接受组织邀请",
                    [&] {
                        Json::Value details(Json::objectValue);
                        details["organization_id"] = organizationId;
                        details["invitation_id"] = invitation.get("invitation_id", "").asString();
                        details["invite_code"] = inviteCode;
                        details["membership_id"] = savedMembership.get("membership_id", "").asString();
                        return details;
                    }()));
            organization = organizationRepository_.upsertOrganization(organization);

            Json::Value result(Json::objectValue);
            result["organization"] = enrichOrganization(organization);
            result["membership"] = enrichMembership(savedMembership);
            return result;
        }
    }

    throw common::AppException("INVITATION_NOT_FOUND", "Invitation not found", drogon::k404NotFound);
}

Json::Value OrganizationService::listPendingInvitationsForUser(const std::string &actorUserId) const
{
    const auto actor = userRepository_.findUserById(actorUserId);
    if (actor.isNull())
    {
        throw common::AppException("USER_NOT_FOUND", "User not found: " + actorUserId, drogon::k404NotFound);
    }

    std::vector<Json::Value> visibleInvitations;
    const auto organizations = organizationRepository_.allOrganizationsArray();
    for (const auto &organizationValue : organizations)
    {
        const auto organizationId = organizationValue.get("organization_id", organizationValue.get("scope_id", "")).asString();
        if (organizationId.empty())
        {
            continue;
        }
        const auto organization = requireOrganization(organizationId);
        for (const auto &invitation : organization.get("invitations", Json::Value(Json::arrayValue)))
        {
            const auto invitationView = buildPendingInvitationView(actor, organization, invitation);
            if (!invitationView.isNull())
            {
                visibleInvitations.push_back(invitationView);
            }
        }
    }

    std::sort(visibleInvitations.begin(), visibleInvitations.end(), [](const Json::Value &left, const Json::Value &right) {
        const auto leftCanAccept = left.get("can_accept", false).asBool();
        const auto rightCanAccept = right.get("can_accept", false).asBool();
        if (leftCanAccept != rightCanAccept)
        {
            return leftCanAccept > rightCanAccept;
        }
        return left.get("created_at", "").asString() > right.get("created_at", "").asString();
    });

    Json::Value out(Json::arrayValue);
    for (const auto &entry : visibleInvitations)
    {
        out.append(entry);
    }
    return out;
}

Json::Value OrganizationService::upsertMember(const std::string &actorUserId, const std::string &organizationId, const Json::Value &payload)
{
    const auto organization = requireOrganization(organizationId);
    const auto userId = payload.get("user_id", "").asString();
    if (userId.empty())
    {
        throw common::AppException("VALIDATION_ERROR", "Missing field: user_id", drogon::k422UnprocessableEntity);
    }

    const auto user = userRepository_.findUserById(userId);
    if (user.isNull())
    {
        throw common::AppException("USER_NOT_FOUND", "User not found: " + userId, drogon::k404NotFound);
    }

    const auto existing = organizationRepository_.findMembership(userId, organizationId);
    const auto subscription = subscriptionService_.subscriptionForOrganization(organizationId);
    const auto seats = subscription.get("seats", 0).asInt();
    if (existing.isNull() && seats > 0 && organizationRepository_.memberCount(organizationId) >= seats)
    {
        throw common::AppException("ORGANIZATION_SEATS_FULL", "Organization seat limit reached", drogon::k409Conflict);
    }

    const auto roles = normalizeMemberRoles(payload.isMember("roles") ? payload["roles"] : defaultMemberRoles());
    ensureOrgAdminGuard(organizationId, existing, roles);
    const auto permissionTemplates = payload.isMember("permission_templates")
                                         ? normalizePermissionTemplates(payload["permission_templates"], roles)
                                         : normalizePermissionTemplates(existing.get("permission_templates", Json::Value(Json::arrayValue)), roles);
    const auto permissionOverrides = payload.isMember("permission_overrides")
                                         ? normalizePermissionOverrides(payload["permission_overrides"])
                                         : normalizePermissionOverrides(existing.get("permission_overrides", Json::Value(Json::arrayValue)));

    Json::Value membership(Json::objectValue);
    membership["membership_id"] = existing.isNull() ? Json::Value(Json::nullValue) : existing.get("membership_id", "");
    membership["user_id"] = userId;
    membership["scope_type"] = "organization";
    membership["scope_id"] = organizationId;
    membership["organization_type"] = organization.get("organization_type", "business").asString();
    membership["roles"] = roles;
    membership["permission_templates"] = permissionTemplates;
    membership["permission_overrides"] = permissionOverrides;
    membership["joined_at"] = existing.isNull() ? common::nowIso8601() : existing.get("joined_at", common::nowIso8601()).asString();
    membership["member_no"] = payload.get("member_no", existing.get("member_no", "")).asString();
    membership["student_no"] = payload.get("student_no", existing.get("student_no", "")).asString();
    membership["employee_no"] = payload.get("employee_no", existing.get("employee_no", "")).asString();
    membership = assignBusinessNumbers(organization, membership, existing);

    auto savedMembership = organizationRepository_.upsertMembership(membership);
    auto savedOrganization = requireOrganization(organizationId);
    savedOrganization = appendAuditEntry(
        savedOrganization,
        createAuditEntry(
            actorUserId,
            existing.isNull() ? "member.added" : "member.updated",
            existing.isNull() ? "添加组织成员" : "更新组织成员",
            [&] {
                Json::Value details(Json::objectValue);
                details["user_id"] = userId;
                details["username"] = user.get("username", "").asString();
                details["roles"] = roles;
                details["permission_templates"] = permissionTemplates;
                details["permission_overrides"] = permissionOverrides;
                details["member_no"] = savedMembership.get("member_no", "").asString();
                if (!existing.isNull())
                {
                    details["previous_roles"] = existing["roles"];
                    details["previous_permission_templates"] = existing.get("permission_templates", Json::Value(Json::arrayValue));
                    details["previous_permission_overrides"] = existing.get("permission_overrides", Json::Value(Json::arrayValue));
                    details["previous_member_no"] = existing.get("member_no", "").asString();
                }
                return details;
            }()));
    organizationRepository_.upsertOrganization(savedOrganization);

    return enrichMembership(savedMembership);
}

void OrganizationService::removeMember(const std::string &actorUserId, const std::string &organizationId, const std::string &userId)
{
    auto organization = requireOrganization(organizationId);
    const auto existing = organizationRepository_.findMembership(userId, organizationId);
    if (existing.isNull())
    {
        return;
    }
    ensureOrgAdminGuard(organizationId, existing, Json::Value(Json::nullValue));
    const auto user = userRepository_.findUserById(userId);
    organizationRepository_.removeMembership(userId, organizationId);
    organization = appendAuditEntry(
        organization,
        createAuditEntry(
            actorUserId,
            "member.removed",
            "移除组织成员",
            [&] {
                Json::Value details(Json::objectValue);
                details["user_id"] = userId;
                details["username"] = user.isNull() ? std::string("") : user.get("username", "").asString();
                details["roles"] = existing["roles"];
                details["member_no"] = existing.get("member_no", "").asString();
                return details;
            }()));
    organizationRepository_.upsertOrganization(organization);
}

Json::Value OrganizationService::listOrganizationSummaries(const std::string &userId, bool includeAll,
                                                            const std::string &query, int page, int pageSize) const
{
    const auto organizations = includeAll ? organizationRepository_.allOrganizationsArray()
                                          : organizationRepository_.listOrganizationsForUser(userId);
    const auto counts = organizationRepository_.memberCounts();
    std::vector<Json::Value> matches;
    std::string normalizedQuery = query;
    std::transform(normalizedQuery.begin(), normalizedQuery.end(), normalizedQuery.begin(),
                   [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
    for (const auto &organization : organizations)
    {
        const auto id = organization.get("organization_id", organization.get("scope_id", "")).asString();
        const auto name = organization.get("name", "").asString();
        std::string searchable = id + " " + name;
        std::transform(searchable.begin(), searchable.end(), searchable.begin(),
                       [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
        if (!normalizedQuery.empty() && searchable.find(normalizedQuery) == std::string::npos) continue;
        Json::Value summary(Json::objectValue);
        summary["organization_id"] = id;
        summary["name"] = name;
        summary["organization_type"] = organization.get("organization_type", "business").asString();
        summary["status"] = organization.get("status", "active").asString();
        summary["subscription"] = organization.get("subscription", Json::Value(Json::objectValue));
        summary["member_count"] = counts.contains(id) ? counts.at(id) : 0;
        matches.push_back(std::move(summary));
    }
    std::stable_sort(matches.begin(), matches.end(), [](const Json::Value &a, const Json::Value &b) {
        return a.get("name", "").asString() < b.get("name", "").asString();
    });
    Json::Value out(Json::objectValue);
    out["items"] = Json::arrayValue;
    const int total = static_cast<int>(matches.size());
    const int begin = (page - 1) * pageSize;
    for (int i = begin; i < total && i < begin + pageSize; ++i) out["items"].append(matches[static_cast<std::size_t>(i)]);
    out["total"] = total;
    out["page"] = page;
    out["page_size"] = pageSize;
    out["pages"] = total == 0 ? 0 : (total + pageSize - 1) / pageSize;
    return out;
}

Json::Value OrganizationService::updateRolePermissions(const std::string &actorUserId,
                                                       const std::string &organizationId,
                                                       const std::string &roleId,
                                                       const Json::Value &payload)
{
    auto organization = requireOrganization(organizationId);
    std::unordered_set<std::string> allowedRoles;
    for (const auto &role : allowedRolePermissionRoles())
    {
        allowedRoles.insert(role.asString());
    }
    if (!allowedRoles.contains(roleId))
    {
        throw common::AppException("VALIDATION_ERROR", "Unsupported role for organization permissions", drogon::k422UnprocessableEntity);
    }

    const auto before = normalizeRolePermissions(organization.get("role_permissions", Json::Value(Json::objectValue)));
    Json::Value next = before;
    Json::Value config(Json::objectValue);
    config["allow"] = normalizePermissionIdArray(payload.get("allow", Json::Value(Json::arrayValue)));
    config["deny"] = normalizePermissionIdArray(payload.get("deny", Json::Value(Json::arrayValue)));

    std::unordered_set<std::string> denySet;
    for (const auto &permission : config["deny"])
    {
        denySet.insert(permission.asString());
    }
    Json::Value cleanAllow(Json::arrayValue);
    for (const auto &permission : config["allow"])
    {
        if (!denySet.contains(permission.asString()))
        {
            cleanAllow.append(permission.asString());
        }
    }
    config["allow"] = cleanAllow;
    next[roleId] = config;

    organization["role_permissions"] = normalizeRolePermissions(next);
    organization = appendAuditEntry(
        organization,
        createAuditEntry(
            actorUserId,
            "role_permissions.updated",
            "更新机构角色权限",
            [&] {
                Json::Value details(Json::objectValue);
                details["role"] = roleId;
                details["allow"] = config["allow"];
                details["deny"] = config["deny"];
                details["previous"] = before.get(roleId, Json::Value(Json::objectValue));
                return details;
            }()));
    return enrichOrganization(organizationRepository_.upsertOrganization(organization));
}

Json::Value OrganizationService::updateSubscription(const std::string &actorUserId, const std::string &organizationId, const Json::Value &patch)
{
    const auto before = subscriptionService_.subscriptionForOrganization(organizationId);
    const auto updated = subscriptionService_.updateOrganizationSubscription(organizationId, patch);
    auto organization = requireOrganization(organizationId);
    organization = appendAuditEntry(
        organization,
        createAuditEntry(
            actorUserId,
            "subscription.updated",
            "更新组织套餐与席位",
            [&] {
                Json::Value details(Json::objectValue);
                details["previous_plan"] = before.get("plan", "free").asString();
                details["plan"] = updated.get("plan", "free").asString();
                details["previous_status"] = before.get("status", "active").asString();
                details["status"] = updated.get("status", "active").asString();
                details["previous_seats"] = before.get("seats", 0).asInt();
                details["seats"] = updated.get("seats", 0).asInt();
                details["previous_expires_at"] = before.get("expires_at", "").asString();
                details["expires_at"] = updated.get("expires_at", "").asString();
                return details;
            }()));
    organizationRepository_.upsertOrganization(organization);
    return updated;
}

Json::Value OrganizationService::listCampuses(const std::string &organizationId) const
{
    const auto organization = requireOrganization(organizationId);
    return ensureArray(organization.get("campuses", Json::Value(Json::arrayValue)));
}

Json::Value OrganizationService::upsertCampus(const std::string &actorUserId, const std::string &organizationId, const Json::Value &payload)
{
    auto organization = requireOrganization(organizationId);
    const auto campusId = payload.get("campus_id", payload.get("id", "")).asString().empty()
                              ? common::generateOpaqueId("campus_")
                              : payload.get("campus_id", payload.get("id", "")).asString();
    const auto existing = findEntityById(ensureArray(organization.get("campuses", Json::Value(Json::arrayValue))), "campus_id", campusId);
    const auto name = payload.get("name", existing.get("name", "")).asString();
    if (name.empty())
    {
        throw common::AppException("VALIDATION_ERROR", "campus name is required", drogon::k422UnprocessableEntity);
    }

    Json::Value campus(Json::objectValue);
    campus["campus_id"] = campusId;
    campus["id"] = campusId;
    campus["organization_id"] = organizationId;
    campus["name"] = name;
    campus["address"] = payload.get("address", existing.get("address", "")).asString();
    campus["status"] = payload.get("status", existing.get("status", "active")).asString() == "disabled" ? "disabled" : "active";
    if (!existing.isNull())
    {
        campus["created_at"] = existing.get("created_at", "").asString();
        campus["created_by"] = existing.get("created_by", "").asString();
    }
    campus = touchEntity(campus, actorUserId, existing.isNull());

    organization["campuses"] = replaceEntityById(ensureArray(organization.get("campuses", Json::Value(Json::arrayValue))), "campus_id", campusId, campus);
    organization = appendAuditEntry(
        organization,
        createAuditEntry(
            actorUserId,
            existing.isNull() ? "campus.created" : "campus.updated",
            existing.isNull() ? "创建校区" : "更新校区",
            [&] {
                Json::Value details(Json::objectValue);
                details["campus_id"] = campusId;
                details["name"] = name;
                return details;
            }()));
    organizationRepository_.upsertOrganization(organization);
    return campus;
}

Json::Value OrganizationService::listLearningGroups(const std::string &organizationId) const
{
    const auto organization = requireOrganization(organizationId);
    return ensureArray(organization.get("learning_groups", Json::Value(Json::arrayValue)));
}

Json::Value OrganizationService::upsertLearningGroup(const std::string &actorUserId, const std::string &organizationId, const Json::Value &payload)
{
    auto organization = requireOrganization(organizationId);
    const auto groupId = payload.get("learning_group_id", payload.get("group_id", payload.get("id", ""))).asString().empty()
                             ? common::generateOpaqueId("lg_")
                             : payload.get("learning_group_id", payload.get("group_id", payload.get("id", ""))).asString();
    const auto existing = findEntityById(ensureArray(organization.get("learning_groups", Json::Value(Json::arrayValue))), "learning_group_id", groupId);
    const auto name = payload.get("name", existing.get("name", "")).asString();
    if (name.empty())
    {
        throw common::AppException("VALIDATION_ERROR", "learning group name is required", drogon::k422UnprocessableEntity);
    }
    const auto type = normalizeLearningGroupType(payload.get("type", existing.get("type", "class")).asString());
    const auto status = normalizeLearningGroupStatus(payload.get("status", existing.get("status", type == "booking" ? "scheduled" : "active")).asString());
    const auto campusId = payload.get("campus_id", existing.get("campus_id", "")).asString();
    if (!campusId.empty() && findEntityById(ensureArray(organization.get("campuses", Json::Value(Json::arrayValue))), "campus_id", campusId).isNull())
    {
        throw common::AppException("VALIDATION_ERROR", "campus_id does not exist in this organization", drogon::k422UnprocessableEntity);
    }

    Json::Value group(Json::objectValue);
    group["learning_group_id"] = groupId;
    group["group_id"] = groupId;
    group["id"] = groupId;
    group["organization_id"] = organizationId;
    group["campus_id"] = campusId;
    group["type"] = type;
    group["subject"] = payload.get("subject", existing.get("subject", "")).asString();
    group["name"] = name;
    group["starts_at"] = payload.get("starts_at", existing.get("starts_at", "")).asString();
    group["ends_at"] = payload.get("ends_at", existing.get("ends_at", "")).asString();
    group["course_package_id"] = payload.get("course_package_id", existing.get("course_package_id", "")).asString();
    group["status"] = status;
    group["enrollments"] = ensureArray(existing.get("enrollments", Json::Value(Json::arrayValue)));
    if (!existing.isNull())
    {
        group["created_at"] = existing.get("created_at", "").asString();
        group["created_by"] = existing.get("created_by", "").asString();
    }
    group = touchEntity(group, actorUserId, existing.isNull());

    organization["learning_groups"] = replaceEntityById(ensureArray(organization.get("learning_groups", Json::Value(Json::arrayValue))), "learning_group_id", groupId, group);
    organization = appendAuditEntry(
        organization,
        createAuditEntry(
            actorUserId,
            existing.isNull() ? "learning_group.created" : "learning_group.updated",
            existing.isNull() ? "创建学习组" : "更新学习组",
            [&] {
                Json::Value details(Json::objectValue);
                details["learning_group_id"] = groupId;
                details["type"] = type;
                details["name"] = name;
                details["campus_id"] = campusId;
                return details;
            }()));
    organizationRepository_.upsertOrganization(organization);
    return group;
}

Json::Value OrganizationService::completeLearningGroup(const std::string &actorUserId,
                                                       const std::string &organizationId,
                                                       const std::string &learningGroupId,
                                                       const Json::Value &payload)
{
    auto organization = requireOrganization(organizationId);
    auto groups = ensureArray(organization.get("learning_groups", Json::Value(Json::arrayValue)));
    auto group = findEntityById(groups, "learning_group_id", learningGroupId);
    if (group.isNull())
    {
        throw common::AppException("LEARNING_GROUP_NOT_FOUND", "Learning group not found: " + learningGroupId, drogon::k404NotFound);
    }

    const auto previousStatus = group.get("status", "active").asString();
    const auto wasCompleted = previousStatus == "completed";
    const auto packageId = group.get("course_package_id", "").asString();
    auto coursePackages = ensureArray(organization.get("course_packages", Json::Value(Json::arrayValue)));
    Json::Value consumedPackage(Json::nullValue);
    bool deducted = false;

    if (!wasCompleted && group.get("type", "class").asString() == "booking" && !packageId.empty())
    {
        consumedPackage = findEntityById(coursePackages, "course_package_id", packageId);
        if (consumedPackage.isNull())
        {
            throw common::AppException("COURSE_PACKAGE_NOT_FOUND", "Course package not found: " + packageId, drogon::k404NotFound);
        }
        const auto remainingLessons = (std::max)(0, consumedPackage.get("remaining_lessons", 0).asInt());
        if (remainingLessons <= 0)
        {
            throw common::AppException("COURSE_PACKAGE_DEPLETED", "Course package has no remaining lessons", drogon::k422UnprocessableEntity);
        }
        const auto totalLessons = (std::max)(0, consumedPackage.get("total_lessons", 0).asInt());
        const auto usedLessons = (std::max)(0, consumedPackage.get("used_lessons", 0).asInt()) + 1;
        const auto nextRemainingLessons = (std::max)(0, remainingLessons - 1);
        consumedPackage["used_lessons"] = usedLessons;
        consumedPackage["remaining_lessons"] = nextRemainingLessons;
        if (nextRemainingLessons == 0 && totalLessons > 0)
        {
            consumedPackage["status"] = "depleted";
        }
        consumedPackage = touchEntity(consumedPackage, actorUserId, false);
        coursePackages = replaceEntityById(coursePackages, "course_package_id", packageId, consumedPackage);
        organization["course_packages"] = coursePackages;
        group["consumed_course_package_id"] = packageId;
        deducted = true;
    }
    else if (!packageId.empty())
    {
        consumedPackage = findEntityById(coursePackages, "course_package_id", packageId);
    }

    group["status"] = "completed";
    group["completed_at"] = payload.get("completed_at", common::nowIso8601()).asString();
    group["completed_by"] = actorUserId;
    group["completion_note"] = payload.get("note", payload.get("completion_note", group.get("completion_note", ""))).asString();
    group = touchEntity(group, actorUserId, false);
    organization["learning_groups"] = replaceEntityById(groups, "learning_group_id", learningGroupId, group);
    organization = appendAuditEntry(
        organization,
        createAuditEntry(
            actorUserId,
            "learning_group.completed",
            deducted ? "完成约课并扣减课时" : "完成学习组",
            [&] {
                Json::Value details(Json::objectValue);
                details["learning_group_id"] = learningGroupId;
                details["previous_status"] = previousStatus;
                details["course_package_id"] = packageId;
                details["deducted"] = deducted;
                if (!consumedPackage.isNull())
                {
                    details["remaining_lessons"] = consumedPackage.get("remaining_lessons", 0).asInt();
                    details["used_lessons"] = consumedPackage.get("used_lessons", 0).asInt();
                }
                return details;
            }()));
    organizationRepository_.upsertOrganization(organization);

    Json::Value out(Json::objectValue);
    out["learning_group"] = group;
    out["course_package"] = consumedPackage;
    out["deducted"] = deducted;
    return out;
}

Json::Value OrganizationService::listLearningGroupEnrollments(const std::string &organizationId, const std::string &learningGroupId) const
{
    const auto organization = requireOrganization(organizationId);
    const auto group = findEntityById(ensureArray(organization.get("learning_groups", Json::Value(Json::arrayValue))), "learning_group_id", learningGroupId);
    if (group.isNull())
    {
        throw common::AppException("LEARNING_GROUP_NOT_FOUND", "Learning group not found: " + learningGroupId, drogon::k404NotFound);
    }
    return ensureArray(group.get("enrollments", Json::Value(Json::arrayValue)));
}

Json::Value OrganizationService::upsertLearningGroupEnrollment(const std::string &actorUserId,
                                                              const std::string &organizationId,
                                                              const std::string &learningGroupId,
                                                              const Json::Value &payload)
{
    auto organization = requireOrganization(organizationId);
    auto groups = ensureArray(organization.get("learning_groups", Json::Value(Json::arrayValue)));
    auto group = findEntityById(groups, "learning_group_id", learningGroupId);
    if (group.isNull())
    {
        throw common::AppException("LEARNING_GROUP_NOT_FOUND", "Learning group not found: " + learningGroupId, drogon::k404NotFound);
    }

    const auto userId = payload.get("user_id", "").asString();
    if (userId.empty())
    {
        throw common::AppException("VALIDATION_ERROR", "user_id is required", drogon::k422UnprocessableEntity);
    }
    if (userRepository_.findUserById(userId).isNull())
    {
        throw common::AppException("USER_NOT_FOUND", "User not found: " + userId, drogon::k404NotFound);
    }
    const auto role = normalizeEnrollmentRole(payload.get("role", "student").asString());
    auto enrollments = ensureArray(group.get("enrollments", Json::Value(Json::arrayValue)));
    const auto existingEnrollment = findEntityById(enrollments, "user_id", userId);
    Json::Value enrollment(Json::objectValue);
    enrollment["enrollment_id"] = payload.get("enrollment_id", existingEnrollment.get("enrollment_id", common::generateOpaqueId("enr_"))).asString();
    enrollment["organization_id"] = organizationId;
    enrollment["learning_group_id"] = learningGroupId;
    enrollment["group_id"] = learningGroupId;
    enrollment["user_id"] = userId;
    enrollment["role"] = role;
    enrollment["status"] = payload.get("status", existingEnrollment.get("status", "active")).asString() == "inactive" ? "inactive" : "active";
    if (!existingEnrollment.isNull())
    {
        enrollment["created_at"] = existingEnrollment.get("created_at", "").asString();
        enrollment["created_by"] = existingEnrollment.get("created_by", "").asString();
    }
    enrollment = touchEntity(enrollment, actorUserId, existingEnrollment.isNull());
    enrollments = replaceEntityById(enrollments, "user_id", userId, enrollment);
    group["enrollments"] = enrollments;
    group = touchEntity(group, actorUserId, false);
    organization["learning_groups"] = replaceEntityById(groups, "learning_group_id", learningGroupId, group);
    organization = appendAuditEntry(
        organization,
        createAuditEntry(
            actorUserId,
            "learning_group.enrollment_saved",
            "保存学习组成员",
            [&] {
                Json::Value details(Json::objectValue);
                details["learning_group_id"] = learningGroupId;
                details["user_id"] = userId;
                details["role"] = role;
                return details;
            }()));
    organizationRepository_.upsertOrganization(organization);
    return enrollment;
}

Json::Value OrganizationService::listCoursePackages(const std::string &organizationId) const
{
    const auto organization = requireOrganization(organizationId);
    return ensureArray(organization.get("course_packages", Json::Value(Json::arrayValue)));
}

Json::Value OrganizationService::upsertCoursePackage(const std::string &actorUserId, const std::string &organizationId, const Json::Value &payload)
{
    auto organization = requireOrganization(organizationId);
    const auto packageId = payload.get("course_package_id", payload.get("id", "")).asString().empty()
                               ? common::generateOpaqueId("pkg_")
                               : payload.get("course_package_id", payload.get("id", "")).asString();
    const auto existing = findEntityById(ensureArray(organization.get("course_packages", Json::Value(Json::arrayValue))), "course_package_id", packageId);
    const auto studentId = payload.get("student_id", existing.get("student_id", "")).asString();
    if (studentId.empty())
    {
        throw common::AppException("VALIDATION_ERROR", "student_id is required", drogon::k422UnprocessableEntity);
    }
    if (userRepository_.findUserById(studentId).isNull())
    {
        throw common::AppException("USER_NOT_FOUND", "Student not found: " + studentId, drogon::k404NotFound);
    }

    const auto totalLessons = (std::max)(0, payload.get("total_lessons", existing.get("total_lessons", 0)).asInt());
    const auto usedLessons = (std::max)(0, payload.get("used_lessons", existing.get("used_lessons", 0)).asInt());
    const auto remainingLessons = payload.isMember("remaining_lessons")
                                      ? (std::max)(0, payload.get("remaining_lessons", 0).asInt())
                                      : (std::max)(0, totalLessons - usedLessons);
    Json::Value coursePackage(Json::objectValue);
    coursePackage["course_package_id"] = packageId;
    coursePackage["id"] = packageId;
    coursePackage["organization_id"] = organizationId;
    coursePackage["student_id"] = studentId;
    coursePackage["subject"] = payload.get("subject", existing.get("subject", "")).asString();
    coursePackage["title"] = payload.get("title", existing.get("title", "")).asString();
    coursePackage["total_lessons"] = totalLessons;
    coursePackage["remaining_lessons"] = remainingLessons;
    coursePackage["used_lessons"] = usedLessons;
    coursePackage["expires_at"] = payload.get("expires_at", existing.get("expires_at", "")).asString();
    coursePackage["status"] = normalizeCoursePackageStatus(payload.get("status", existing.get("status", "active")).asString());
    if (!existing.isNull())
    {
        coursePackage["created_at"] = existing.get("created_at", "").asString();
        coursePackage["created_by"] = existing.get("created_by", "").asString();
    }
    coursePackage = touchEntity(coursePackage, actorUserId, existing.isNull());

    organization["course_packages"] = replaceEntityById(ensureArray(organization.get("course_packages", Json::Value(Json::arrayValue))), "course_package_id", packageId, coursePackage);
    organization = appendAuditEntry(
        organization,
        createAuditEntry(
            actorUserId,
            existing.isNull() ? "course_package.created" : "course_package.updated",
            existing.isNull() ? "创建课程包" : "更新课程包",
            [&] {
                Json::Value details(Json::objectValue);
                details["course_package_id"] = packageId;
                details["student_id"] = studentId;
                details["subject"] = coursePackage.get("subject", "").asString();
                return details;
            }()));
    organizationRepository_.upsertOrganization(organization);
    return coursePackage;
}

bool OrganizationService::canAccessOrganization(const std::string &actorUserId, const Json::Value &actorRoles, const std::string &organizationId) const
{
    if (hasPlatformRole(actorRoles))
    {
        return true;
    }
    return !organizationRepository_.findMembership(actorUserId, organizationId).isNull();
}

bool OrganizationService::canManageOrganization(const std::string &actorUserId, const Json::Value &actorRoles, const std::string &organizationId) const
{
    if (hasPlatformRole(actorRoles))
    {
        return true;
    }

    const auto membership = organizationRepository_.findMembership(actorUserId, organizationId);
    if (membership.isNull())
    {
        return false;
    }

    for (const auto &role : membership["roles"])
    {
        if (role.asString() == "orgAdmin")
        {
            return true;
        }
    }
    return false;
}

Json::Value OrganizationService::requireOrganization(const std::string &organizationId) const
{
    const auto organization = organizationRepository_.findOrganization(organizationId);
    if (organization.isNull())
    {
        throw common::AppException("ORGANIZATION_NOT_FOUND", "Organization not found: " + organizationId, drogon::k404NotFound);
    }
    return organization;
}

Json::Value OrganizationService::enrichOrganization(Json::Value organization) const
{
    const auto organizationId = organization.get("organization_id", organization.get("scope_id", "")).asString();
    organization["member_count"] = organizationRepository_.memberCount(organizationId);
    organization["subscription"] = subscriptionService_.subscriptionForOrganization(organizationId);
    organization["seats"] = organization["subscription"].get("seats", 0).asInt();
    if (!organization.isMember("invitations") || !organization["invitations"].isArray())
    {
        organization["invitations"] = Json::arrayValue;
    }
    if (!organization.isMember("audit_logs") || !organization["audit_logs"].isArray())
    {
        organization["audit_logs"] = Json::arrayValue;
    }
    organization["role_permissions"] = normalizeRolePermissions(organization.get("role_permissions", Json::Value(Json::objectValue)));
    return organization;
}

Json::Value OrganizationService::enrichMembership(Json::Value membership) const
{
    const auto user = userRepository_.findUserById(membership.get("user_id", "").asString());
    if (!user.isNull())
    {
        membership["username"] = user.get("username", "").asString();
        membership["status"] = user.get("status", "active").asString();
    }

    const auto organization = organizationRepository_.findOrganization(membership.get("scope_id", "").asString());
    if (!organization.isNull())
    {
        membership["organization_id"] = organization.get("organization_id", "").asString();
        membership["organization_name"] = organization.get("name", "").asString();
    }
    if (!membership.isMember("permission_overrides") || !membership["permission_overrides"].isArray())
    {
        membership["permission_overrides"] = Json::arrayValue;
    }
    if (!membership.isMember("permission_templates") || !membership["permission_templates"].isArray())
    {
        membership["permission_templates"] = Json::arrayValue;
    }
    return membership;
}

Json::Value OrganizationService::assignBusinessNumbers(const Json::Value &organization, Json::Value membership, const Json::Value &existing) const
{
    const auto organizationId = organization.get("organization_id", "").asString();
    const auto organizationType = organization.get("organization_type", "business").asString();

    auto memberNo = membership.get("member_no", existing.get("member_no", "")).asString();
    auto studentNo = membership.get("student_no", existing.get("student_no", "")).asString();
    auto employeeNo = membership.get("employee_no", existing.get("employee_no", "")).asString();

    if (memberNo.empty())
    {
        memberNo = !studentNo.empty() ? studentNo : employeeNo;
    }
    if (memberNo.empty())
    {
        memberNo = nextOrganizationMemberNo(organizationId, organizationType);
    }

    membership["member_no"] = memberNo;
    if (organizationType == "school")
    {
        membership["student_no"] = studentNo.empty() ? memberNo : studentNo;
        membership["employee_no"] = "";
    }
    else
    {
        membership["employee_no"] = employeeNo.empty() ? memberNo : employeeNo;
        membership["student_no"] = "";
    }
    return membership;
}

std::string OrganizationService::nextOrganizationMemberNo(const std::string &organizationId, const std::string &organizationType) const
{
    const auto memberships = organizationRepository_.listMembershipsForScope(organizationId);
    int maxSerial = 0;
    const auto prefix = organizationType == "school" ? std::string("STU-") : std::string("EMP-");
    for (const auto &membership : memberships)
    {
        maxSerial = (std::max)(maxSerial, extractPrefixedSerial(membership.get("member_no", "").asString(), prefix));
        maxSerial = (std::max)(maxSerial, extractPrefixedSerial(membership.get("student_no", "").asString(), prefix));
        maxSerial = (std::max)(maxSerial, extractPrefixedSerial(membership.get("employee_no", "").asString(), prefix));
    }
    return prefix + padSerial(maxSerial + 1, 6);
}

int OrganizationService::extractPrefixedSerial(const std::string &value, const std::string &prefix)
{
    if (value.rfind(prefix, 0) != 0)
    {
        return 0;
    }
    const auto serial = value.substr(prefix.size());
    if (serial.empty())
    {
        return 0;
    }
    for (const auto ch : serial)
    {
        if (ch < '0' || ch > '9')
        {
            return 0;
        }
    }
    return std::stoi(serial);
}

std::string OrganizationService::padSerial(int value, int width)
{
    auto text = std::to_string(value);
    if (static_cast<int>(text.size()) >= width)
    {
        return text;
    }
    return std::string(static_cast<size_t>(width - text.size()), '0') + text;
}

std::string OrganizationService::normalizeOrganizationType(const std::string &organizationType)
{
    if (organizationType == "business" || organizationType == "school")
    {
        return organizationType;
    }
    return "";
}

std::string OrganizationService::normalizeLearningGroupType(const std::string &type)
{
    if (type == "booking")
    {
        return "booking";
    }
    return "class";
}

std::string OrganizationService::normalizeLearningGroupStatus(const std::string &status)
{
    if (status == "finished")
    {
        return "completed";
    }
    if (status == "canceled")
    {
        return "cancelled";
    }
    if (status == "scheduled" || status == "active" || status == "completed" || status == "cancelled" ||
        status == "rescheduled" || status == "no_show" || status == "archived")
    {
        return status;
    }
    return "active";
}

std::string OrganizationService::normalizeEnrollmentRole(const std::string &role)
{
    if (role == "teacher" || role == "assistant")
    {
        return role;
    }
    return "student";
}

std::string OrganizationService::normalizeCoursePackageStatus(const std::string &status)
{
    if (status == "finished")
    {
        return "depleted";
    }
    if (status == "canceled")
    {
        return "cancelled";
    }
    if (status == "active" || status == "expired" || status == "paused" || status == "depleted" || status == "cancelled")
    {
        return status;
    }
    return "active";
}

Json::Value OrganizationService::defaultOwnerRoles()
{
    Json::Value roles(Json::arrayValue);
    roles.append("orgAdmin");
    return roles;
}

Json::Value OrganizationService::defaultMemberRoles()
{
    Json::Value roles(Json::arrayValue);
    roles.append("student");
    return roles;
}

Json::Value OrganizationService::allowedMembershipRoles()
{
    Json::Value roles(Json::arrayValue);
    roles.append("student");
    roles.append("assistant");
    roles.append("teacher");
    roles.append("orgAdmin");
    return roles;
}

Json::Value OrganizationService::allowedPermissionTemplates()
{
    Json::Value templates(Json::arrayValue);
    templates.append("assistant");
    templates.append("homeroom");
    templates.append("teachingOffice");
    templates.append("consultant");
    templates.append("campusAdmin");
    return templates;
}

Json::Value OrganizationService::allowedRolePermissionRoles()
{
    Json::Value roles(Json::arrayValue);
    roles.append("student");
    roles.append("assistant");
    roles.append("teacher");
    roles.append("orgAdmin");
    roles.append("contentAdmin");
    return roles;
}

bool OrganizationService::hasRole(const Json::Value &roles, const std::string &expected)
{
    for (const auto &role : roles)
    {
        if (role.asString() == expected)
        {
            return true;
        }
    }
    return false;
}

Json::Value OrganizationService::normalizeMemberRoles(const Json::Value &inputRoles)
{
    Json::Value roles(Json::arrayValue);
    std::unordered_set<std::string> seen;
    std::unordered_set<std::string> allowed;
    for (const auto &role : allowedMembershipRoles())
    {
        allowed.insert(role.asString());
    }

    if (inputRoles.isArray())
    {
        for (const auto &role : inputRoles)
        {
            const auto value = role.asString();
            if (value.empty() || !allowed.contains(value) || seen.contains(value))
            {
                continue;
            }
            seen.insert(value);
            roles.append(value);
        }
    }

    if (roles.empty())
    {
        throw common::AppException("VALIDATION_ERROR", "roles must include at least one valid organization role", drogon::k422UnprocessableEntity);
    }
    return roles;
}

Json::Value OrganizationService::normalizePermissionTemplates(const Json::Value &inputTemplates, const Json::Value &roles)
{
    Json::Value templates(Json::arrayValue);
    if (!inputTemplates.isArray())
    {
        return templates;
    }

    const bool canUseAssistantTemplate = hasRole(roles, "assistant");
    const bool canUseCampusAdminTemplate = hasRole(roles, "orgAdmin");
    std::unordered_set<std::string> allowed;
    for (const auto &permissionTemplate : allowedPermissionTemplates())
    {
        allowed.insert(permissionTemplate.asString());
    }

    std::unordered_set<std::string> seen;
    for (const auto &permissionTemplate : inputTemplates)
    {
        const auto value = permissionTemplate.asString();
        if (value.empty() || !allowed.contains(value) || seen.contains(value))
        {
            continue;
        }
        if (value == "campusAdmin" && !canUseCampusAdminTemplate)
        {
            continue;
        }
        if (value != "campusAdmin" && !canUseAssistantTemplate)
        {
            continue;
        }
        seen.insert(value);
        templates.append(value);
    }
    return templates;
}

Json::Value OrganizationService::normalizePermissionOverrides(const Json::Value &inputOverrides)
{
    Json::Value overrides(Json::arrayValue);
    if (!inputOverrides.isArray())
    {
        return overrides;
    }

    std::unordered_set<std::string> seen;
    for (const auto &item : inputOverrides)
    {
        if (!item.isObject())
        {
            continue;
        }
        const auto permission = item.get("permission", "").asString();
        if (!isAllowedPermissionOverride(permission))
        {
            continue;
        }
        const auto effect = normalizePermissionEffect(item.get("effect", "allow").asString());
        const auto scope = normalizePermissionScope(item.get("scope", "organization").asString());
        const auto scopeId = item.get("scope_id", item.get("scopeId", "")).asString();
        const auto expiresAt = item.get("expires_at", item.get("expiresAt", "")).asString();
        const auto key = permission + "|" + effect + "|" + scope + "|" + scopeId + "|" + expiresAt;
        if (seen.contains(key))
        {
            continue;
        }
        seen.insert(key);

        Json::Value normalized(Json::objectValue);
        normalized["permission"] = permission;
        normalized["effect"] = effect;
        normalized["scope"] = scope;
        normalized["scope_id"] = scopeId;
        normalized["expires_at"] = expiresAt;
        overrides.append(normalized);
    }
    return overrides;
}

Json::Value OrganizationService::normalizePermissionIdArray(const Json::Value &inputPermissions)
{
    Json::Value permissions(Json::arrayValue);
    if (!inputPermissions.isArray())
    {
        return permissions;
    }
    std::unordered_set<std::string> seen;
    for (const auto &item : inputPermissions)
    {
        const auto permission = item.asString();
        if (!isAllowedPermissionOverride(permission) || seen.contains(permission))
        {
            continue;
        }
        seen.insert(permission);
        permissions.append(permission);
    }
    return permissions;
}

Json::Value OrganizationService::normalizeRolePermissions(const Json::Value &inputRolePermissions)
{
    Json::Value out(Json::objectValue);
    if (!inputRolePermissions.isObject())
    {
        return out;
    }
    std::unordered_set<std::string> allowedRoles;
    for (const auto &role : allowedRolePermissionRoles())
    {
        allowedRoles.insert(role.asString());
    }
    for (const auto &roleId : inputRolePermissions.getMemberNames())
    {
        if (!allowedRoles.contains(roleId) || !inputRolePermissions[roleId].isObject())
        {
            continue;
        }
        Json::Value config(Json::objectValue);
        config["allow"] = normalizePermissionIdArray(inputRolePermissions[roleId].get("allow", Json::Value(Json::arrayValue)));
        config["deny"] = normalizePermissionIdArray(inputRolePermissions[roleId].get("deny", Json::Value(Json::arrayValue)));
        out[roleId] = config;
    }
    return out;
}

bool OrganizationService::isAllowedPermissionOverride(const std::string &permission)
{
    static const std::unordered_set<std::string> allowed{
        "assignment.create",
        "assignment.review",
        "assignment.remind",
        "gradebook.view",
        "student.profile.view",
        "student.profile.edit",
        "student.followup.edit",
        "student.import",
        "learning_group.manage",
        "lesson.booking.manage",
        "course_package.manage",
        "course_package.view",
        "lesson_prep.create",
        "lesson_prep.export",
        "renewal_risk.view",
        "organization.dashboard.view",
        "organization.member.manage",
        "organization.billing.manage",
        "payment.refund",
        "audit.view",
        "content.paper.maintain",
        "content.analysis.review",
        "content.quality.check"};
    return allowed.contains(permission);
}

std::string OrganizationService::normalizePermissionEffect(const std::string &effect)
{
    return effect == "deny" ? "deny" : "allow";
}

std::string OrganizationService::normalizePermissionScope(const std::string &scope)
{
    if (scope == "personal" || scope == "learningGroup" || scope == "campus" || scope == "organization")
    {
        return scope;
    }
    return "organization";
}

Json::Value OrganizationService::appendAuditEntry(Json::Value organization, const Json::Value &entry) const
{
    Json::Value logs(Json::arrayValue);
    logs.append(entry);
    if (organization["audit_logs"].isArray())
    {
        for (const auto &existing : organization["audit_logs"])
        {
            if (logs.size() >= 80)
            {
                break;
            }
            logs.append(existing);
        }
    }
    organization["audit_logs"] = logs;
    organization["updated_at"] = common::nowIso8601();
    return organization;
}

Json::Value OrganizationService::prependInvitation(Json::Value organization, const Json::Value &entry) const
{
    Json::Value invitations(Json::arrayValue);
    invitations.append(entry);
    if (organization["invitations"].isArray())
    {
        for (const auto &existing : organization["invitations"])
        {
            invitations.append(existing);
        }
    }
    organization["invitations"] = invitations;
    organization["updated_at"] = common::nowIso8601();
    return organization;
}

Json::Value OrganizationService::replaceInvitation(Json::Value organization, const Json::Value &entry) const
{
    auto invitations = organization.get("invitations", Json::Value(Json::arrayValue));
    bool replaced = false;
    for (Json::ArrayIndex index = 0; index < invitations.size(); ++index)
    {
        if (invitations[index].get("invitation_id", "").asString() != entry.get("invitation_id", "").asString())
        {
            continue;
        }
        invitations[index] = entry;
        replaced = true;
        break;
    }
    if (!replaced)
    {
        invitations.append(entry);
    }
    organization["invitations"] = invitations;
    organization["updated_at"] = common::nowIso8601();
    return organization;
}

Json::Value OrganizationService::createAuditEntry(const std::string &actorUserId,
const std::string &action,
const std::string &summary,
const Json::Value &details) const
{
    Json::Value entry(Json::objectValue);
    entry["audit_id"] = common::generateOpaqueId("audit_");
    entry["action"] = action;
    entry["summary"] = summary;
    entry["actor_user_id"] = actorUserId;
    const auto actor = userRepository_.findUserById(actorUserId);
    entry["actor_username"] = actor.isNull() ? actorUserId : actor.get("username", actorUserId).asString();
    entry["created_at"] = common::nowIso8601();
    entry["details"] = details;
    return entry;
}

OrganizationService::InvitationContact OrganizationService::extractInvitationContact(const Json::Value &payload)
{
    const auto email = payload.get("email", "").asString();
    if (looksLikeEmail(email))
    {
        return {"email", email};
    }
    const auto phone = normalizePhone(payload.get("phone", "").asString());
    if (!phone.empty())
    {
        return {"phone", phone};
    }
    throw common::AppException("VALIDATION_ERROR", "Invitation requires a valid email or phone", drogon::k422UnprocessableEntity);
}

Json::Value OrganizationService::findUserByInvitationContact(const OrganizationService::InvitationContact &contact) const
{
    if (contact.channel == "email")
    {
        return userRepository_.findUserByEmail(contact.value);
    }
    if (contact.channel == "phone")
    {
        return userRepository_.findUserByPhone(contact.value);
    }
    return Json::Value(Json::nullValue);
}

Json::Value OrganizationService::buildPendingInvitationView(const Json::Value &actor,
const Json::Value &organization,
const Json::Value &invitation) const
{
    const auto eligibility = evaluateInvitationEligibility(actor, organization, invitation);
    if (!eligibility.visible)
    {
        return Json::Value(Json::nullValue);
    }

    Json::Value view(Json::objectValue);
    view["invitation_id"] = invitation.get("invitation_id", "").asString();
    view["invite_code"] = invitation.get("invite_code", "").asString();
    view["organization_id"] = organization.get("organization_id", "").asString();
    view["organization_name"] = organization.get("name", invitation.get("organization_name", "")).asString();
    view["organization_type"] = organization.get("organization_type", "business").asString();
    view["channel"] = invitation.get("channel", "email").asString();
    view["contact"] = invitation.get("contact", "").asString();
    view["email"] = invitation.get("email", "").asString();
    view["phone"] = invitation.get("phone", "").asString();
    view["target_user_id"] = invitation.get("target_user_id", "").asString();
    view["status"] = invitation.get("status", "pending").asString();
    view["roles"] = invitation.get("roles", Json::Value(Json::arrayValue));
    view["permission_templates"] = invitation.get("permission_templates", Json::Value(Json::arrayValue));
    view["permission_overrides"] = invitation.get("permission_overrides", Json::Value(Json::arrayValue));
    view["member_no"] = invitation.get("member_no", "").asString();
    view["student_no"] = invitation.get("student_no", "").asString();
    view["employee_no"] = invitation.get("employee_no", "").asString();
    view["message"] = invitation.get("message", "").asString();
    view["created_by"] = invitation.get("created_by", "").asString();
    const auto inviter = userRepository_.findUserById(view["created_by"].asString());
    view["created_by_username"] = inviter.isNull() ? view["created_by"].asString() : inviter.get("username", view["created_by"].asString()).asString();
    view["created_at"] = invitation.get("created_at", "").asString();
    view["expires_at"] = invitation.get("expires_at", "").asString();
    view["delivery_status"] = invitation.get("delivery_status", "pending").asString();
    view["delivery_provider"] = invitation.get("delivery_provider", "").asString();
    view["delivery_message_id"] = invitation.get("delivery_message_id", "").asString();
    view["delivery_error"] = invitation.get("delivery_error", "").asString();
    view["delivered_at"] = invitation.get("delivered_at", "").asString();
    view["contact_matches"] = eligibility.contactMatches;
    view["contact_verified"] = eligibility.contactVerified;
    view["can_accept"] = eligibility.canAccept;
    view["is_expired"] = eligibility.expired;
    view["accept_block_code"] = eligibility.blockCode;
    view["accept_block_message"] = eligibility.blockMessage;
    view["accept_url"] = buildInvitationAcceptUrl(invitation.get("invite_code", "").asString());
    return view;
}

OrganizationService::InvitationEligibility OrganizationService::evaluateInvitationEligibility(const Json::Value &actor,
const Json::Value &organization,
const Json::Value &invitation) const
{
    InvitationEligibility eligibility;
    if (invitation.get("status", "pending").asString() != "pending")
    {
        return eligibility;
    }

    const auto actorUserId = actor.get("id", actor.get("user_id", "")).asString();
    const auto organizationId = organization.get("organization_id", "").asString();
    if (!organizationId.empty() && !organizationRepository_.findMembership(actorUserId, organizationId).isNull())
    {
        return eligibility;
    }

    const auto targetUserId = invitation.get("target_user_id", "").asString();
    if (!targetUserId.empty() && targetUserId != actorUserId)
    {
        return eligibility;
    }

    const auto channel = invitation.get("channel", "").asString();
    const auto expectedContact = invitation.get("contact", "").asString();
    const auto matchedByTargetUser = !targetUserId.empty() && targetUserId == actorUserId;
    const auto matchedByContact = invitationContactMatchesActor(actor, channel, expectedContact);
    if (!matchedByTargetUser && !matchedByContact)
    {
        return eligibility;
    }

    eligibility.visible = true;
    eligibility.contactMatches = matchedByContact;
    eligibility.expired = isExpiredIso8601(invitation.get("expires_at", "").asString());
    if (eligibility.expired)
    {
        eligibility.blockCode = "INVITATION_EXPIRED";
        eligibility.blockMessage = "邀请已过期，请联系管理员重新发送。";
        return eligibility;
    }

    const auto subscription = subscriptionService_.subscriptionForOrganization(organizationId);
    const auto seats = subscription.get("seats", 0).asInt();
    if (seats > 0 && organizationRepository_.memberCount(organizationId) >= seats)
    {
        eligibility.blockCode = "ORGANIZATION_SEATS_FULL";
        eligibility.blockMessage = "组织席位已满，请联系管理员扩容后再加入。";
        return eligibility;
    }

    if (channel == "email")
    {
        eligibility.contactVerified = actor.get("email_verified", false).asBool();
        if (!matchedByContact)
        {
            eligibility.blockCode = "INVITATION_CONTACT_BIND_REQUIRED";
            eligibility.blockMessage = "请先绑定并验证受邀邮箱 " + expectedContact;
            return eligibility;
        }
        if (!eligibility.contactVerified)
        {
            eligibility.blockCode = "INVITATION_EMAIL_VERIFICATION_REQUIRED";
            eligibility.blockMessage = "请先验证受邀邮箱 " + expectedContact;
            return eligibility;
        }
        eligibility.canAccept = true;
        return eligibility;
    }

    eligibility.contactVerified = actor.get("phone_verified", false).asBool();
    if (!matchedByContact)
    {
        eligibility.blockCode = "INVITATION_CONTACT_BIND_REQUIRED";
        eligibility.blockMessage = "请先绑定并验证受邀手机号 " + expectedContact;
        return eligibility;
    }
    if (!eligibility.contactVerified)
    {
        eligibility.blockCode = "INVITATION_PHONE_VERIFICATION_REQUIRED";
        eligibility.blockMessage = "请先验证受邀手机号 " + expectedContact;
        return eligibility;
    }
    eligibility.canAccept = true;
    return eligibility;
}

bool OrganizationService::invitationContactMatchesActor(const Json::Value &actor,
const std::string &channel,
const std::string &expectedContact)
{
    if (channel == "email")
    {
        return toLowerCopy(actor.get("email", "").asString()) == toLowerCopy(expectedContact);
    }
    return normalizePhone(actor.get("phone", "").asString()) == normalizePhone(expectedContact);
}

DeliveryResult OrganizationService::deliverInvitation(const Json::Value &organization, const Json::Value &invitation) const
{
    const auto organizationName = organization.get("name", "你的组织").asString();
    const auto inviteCode = invitation.get("invite_code", "").asString();
    const auto acceptUrl = buildInvitationAcceptUrl(inviteCode);
    const auto channel = invitation.get("channel", "email").asString();
    const auto contact = invitation.get("contact", "").asString();

    std::string roleText;
    for (const auto &role : invitation["roles"])
    {
        if (!roleText.empty())
        {
            roleText += " / ";
        }
        roleText += role.asString();
    }

    const auto textBody = "你被 " + organizationName + " 邀请加入组织。角色：" +
                  (roleText.empty() ? std::string("student") : roleText) +
                  "。请先登录并验证与你收到邀请相同的" + (channel == "email" ? std::string("邮箱") : std::string("手机号")) +
                  "（" + contact + "），然后通过以下链接在个人中心完成接受：" + acceptUrl;

    if (channel == "phone")
    {
        SmsMessage message;
        message.to = invitation.get("phone", contact).asString();
        message.body = textBody;
        return smsService_.send(message);
    }

    EmailMessage message;
    message.toAddress = invitation.get("email", contact).asString();
    message.subject = organizationName + " 邀请你加入组织";
    message.textBody = textBody;
    return emailService_.send(message);
}

Json::Value OrganizationService::mergeInvitationDelivery(Json::Value invitation, const DeliveryResult &delivery) const
{
    invitation["delivery_status"] = delivery.delivered ? "sent" : "failed";
    invitation["delivery_provider"] = delivery.provider;
    invitation["delivery_message_id"] = delivery.providerMessageId;
    invitation["delivery_error"] = delivery.errorMessage;
    invitation["delivered_at"] = delivery.delivered ? common::nowIso8601() : "";
    return invitation;
}

void OrganizationService::ensureInvitationContactVerified(const Json::Value &actor, const Json::Value &invitation) const
{
    const auto channel = invitation.get("channel", "").asString();
    const auto expectedContact = invitation.get("contact", "").asString();
    if (channel == "email")
    {
        if (!actor.get("email_verified", false).asBool())
        {
            throw common::AppException("INVITATION_EMAIL_VERIFICATION_REQUIRED", "Verify the invited email before accepting this invitation", drogon::k409Conflict);
        }
        if (toLowerCopy(actor.get("email", "").asString()) != toLowerCopy(expectedContact))
        {
            throw common::AppException("INVITATION_CONTACT_MISMATCH", "This invitation requires the verified email " + expectedContact, drogon::k409Conflict);
        }
        return;
    }
    if (!actor.get("phone_verified", false).asBool())
    {
        throw common::AppException("INVITATION_PHONE_VERIFICATION_REQUIRED", "Verify the invited phone before accepting this invitation", drogon::k409Conflict);
    }
    if (normalizePhone(actor.get("phone", "").asString()) != normalizePhone(expectedContact))
    {
        throw common::AppException("INVITATION_CONTACT_MISMATCH", "This invitation requires the verified phone " + expectedContact, drogon::k409Conflict);
    }
}

bool OrganizationService::looksLikeEmail(const std::string &value)
{
    const auto atPos = value.find('@');
    const auto dotPos = value.rfind('.');
    return !value.empty() && atPos != std::string::npos && dotPos != std::string::npos && dotPos > atPos + 1;
}

std::string OrganizationService::toLowerCopy(std::string value)
{
    for (auto &ch : value)
    {
        ch = static_cast<char>(std::tolower(static_cast<unsigned char>(ch)));
    }
    return value;
}

std::string OrganizationService::normalizePhone(const std::string &value)
{
    std::string digits;
    for (const auto ch : value)
    {
        if (ch >= '0' && ch <= '9')
        {
            digits.push_back(ch);
        }
    }
    return digits;
}

std::string OrganizationService::generateInvitationCode()
{
    return common::generateOpaqueId("invite_");
}

std::string OrganizationService::buildInvitationAcceptUrl(const std::string &inviteCode) const
{
    auto baseUrl = publicWebBaseUrl_.empty() ? std::string("http://127.0.0.1:8000") : publicWebBaseUrl_;
    while (!baseUrl.empty() && baseUrl.back() == '/')
    {
        baseUrl.pop_back();
    }
    return baseUrl + "/?invite_token=" + inviteCode;
}

std::string OrganizationService::defaultInvitationExpiresAt()
{
    using namespace std::chrono;
    const auto inviteTime = system_clock::now() + hours(24 * 7);
    const auto secondsPart = time_point_cast<std::chrono::seconds>(inviteTime);
    const auto ms = duration_cast<milliseconds>(inviteTime - secondsPart).count();
    const auto timeValue = system_clock::to_time_t(inviteTime);

    std::tm tm{};
#ifdef _WIN32
    gmtime_s(&tm, &timeValue);
#else
    gmtime_r(&timeValue, &tm);
#endif

    std::ostringstream oss;
    oss << std::put_time(&tm, "%Y-%m-%dT%H:%M:%S")
        << "." << std::setw(3) << std::setfill('0') << ms
        << "Z";
    return oss.str();
}

bool OrganizationService::isExpiredIso8601(const std::string &value)
{
    return !value.empty() && value < common::nowIso8601();
}

void OrganizationService::ensureOrgAdminGuard(const std::string &organizationId, const Json::Value &existing, const Json::Value &nextRoles) const
{
    if (existing.isNull() || !hasRole(existing["roles"], "orgAdmin"))
    {
        return;
    }

    const auto willRemainOrgAdmin = !nextRoles.isNull() && hasRole(nextRoles, "orgAdmin");
    if (willRemainOrgAdmin)
    {
        return;
    }

    if (organizationAdminCount(organizationId) <= 1)
    {
        throw common::AppException("LAST_ORG_ADMIN", "Organization must retain at least one orgAdmin", drogon::k409Conflict);
    }
}

int OrganizationService::organizationAdminCount(const std::string &organizationId) const
{
    const auto memberships = organizationRepository_.listMembershipsForScope(organizationId);
    int count = 0;
    for (const auto &membership : memberships)
    {
        if (hasRole(membership["roles"], "orgAdmin"))
        {
            ++count;
        }
    }
    return count;
}

std::string OrganizationService::generateOrganizationId()
{
    return common::generateOpaqueId("org_");
}

bool OrganizationService::hasPlatformRole(const Json::Value &roles)
{
    for (const auto &role : roles)
    {
        const auto value = role.asString();
        if (value == "superAdmin")
        {
            return true;
        }
    }
    return false;
}

Json::Value OrganizationService::ensureArray(const Json::Value &value)
{
    return value.isArray() ? value : Json::Value(Json::arrayValue);
}

Json::Value OrganizationService::touchEntity(Json::Value entity, const std::string &actorUserId, bool isNew)
{
    const auto now = common::nowIso8601();
    if (isNew || !entity.isMember("created_at") || entity.get("created_at", "").asString().empty())
    {
        entity["created_at"] = now;
        entity["created_by"] = actorUserId;
    }
    entity["updated_at"] = now;
    entity["updated_by"] = actorUserId;
    return entity;
}

Json::Value OrganizationService::replaceEntityById(Json::Value items,
                                                   const std::string &idField,
                                                   const std::string &id,
                                                   const Json::Value &entity)
{
    if (!items.isArray())
    {
        items = Json::arrayValue;
    }
    for (Json::ArrayIndex index = 0; index < items.size(); ++index)
    {
        if (items[index].get(idField, "").asString() == id)
        {
            items[index] = entity;
            return items;
        }
    }
    items.append(entity);
    return items;
}

Json::Value OrganizationService::findEntityById(const Json::Value &items, const std::string &idField, const std::string &id)
{
    if (!items.isArray() || id.empty())
    {
        return Json::Value(Json::nullValue);
    }
    for (const auto &item : items)
    {
        if (item.get(idField, "").asString() == id || item.get("id", "").asString() == id || item.get("group_id", "").asString() == id)
        {
            return item;
        }
    }
    return Json::Value(Json::nullValue);
}

}  // namespace application::services
