// Auto-generated by tools/sink_class.ps1 from StatisticsService.h
#include "StatisticsService.h"

#include "common/TimeUtils.h"

namespace application::services
{
namespace
{
void appendCertificate(Json::Value &certificates,
                       int &earnedCount,
                       const std::string &id,
                       const std::string &title,
                       const std::string &description,
                       double current,
                       double target,
                       bool earned)
{
    Json::Value certificate(Json::objectValue);
    certificate["id"] = id;
    certificate["title"] = title;
    certificate["description"] = description;
    certificate["current"] = current;
    certificate["target"] = target;
    certificate["earned"] = earned;
    certificate["progress"] = target > 0.0 ? (std::min)(100.0, std::round(current * 10000.0 / target) / 100.0) : 0.0;
    if (earned)
    {
        ++earnedCount;
    }
    certificates.append(certificate);
}
}  // namespace

StatisticsService::StatisticsService(infrastructure::storage::AnswerRepository &repository,
                                     infrastructure::storage::ProfileRepository &profileRepository)
    : repository_(repository), profileRepository_(profileRepository)
{
}

Json::Value StatisticsService::userStatistics(const std::string &userId) const
{
    const auto all = repository_.listUserAnswers(userId);
    Json::Value stats(Json::objectValue);
    stats["user_id"] = userId;
    stats["total_exams"] = static_cast<int>(all.size());
    stats["total_questions"] = 0;
    stats["correct_answers"] = 0;
    stats["wrong_answers"] = 0;
    stats["overall_accuracy"] = 0.0;
    stats["average_score"] = 0.0;
    stats["exams"] = Json::arrayValue;
    const auto profile = profileRepository_.loadProfile(userId);
    const auto now = common::nowIso8601();
    const auto todayDate = now.substr(0, 10);
    const auto study = profile.get("study_stats", Json::Value(Json::objectValue));
    const auto studyDate = study.get("date", "").asString();
    const int todaySeconds = studyDate == todayDate ? study.get("today_seconds", 0).asInt() : 0;
    stats["xp"] = profile.get("xp", 0).asInt();
    stats["today_learning_seconds"] = todaySeconds;
    stats["today_learning_minutes"] = todaySeconds / 60;
    stats["today_xp_awarded"] = studyDate == todayDate ? study.get("today_xp_awarded", 0).asInt() : 0;

    double scoreSum = 0.0;
    int scoredCount = 0;
    for (const auto &item : all)
    {
        const auto entry = item["statistics"];
        stats["total_questions"] = stats["total_questions"].asInt() + entry.get("total_questions", 0).asInt();
        stats["correct_answers"] = stats["correct_answers"].asInt() + entry.get("correct_count", 0).asInt();
        stats["wrong_answers"] = stats["wrong_answers"].asInt() + entry.get("wrong_count", 0).asInt();

        Json::Value examRow(Json::objectValue);
        examRow["exam_id"] = item.get("exam_id", "").asString();
        examRow["score"] = entry.get("score", 0.0).asDouble();
        examRow["accuracy"] = entry.get("accuracy", 0.0).asDouble();
        examRow["completed_at"] = item.get("saved_at", "").asString();
        stats["exams"].append(examRow);
        scoreSum += examRow["score"].asDouble();
        ++scoredCount;
    }

    const auto answered = stats["correct_answers"].asInt() + stats["wrong_answers"].asInt();
    if (answered > 0)
    {
        stats["overall_accuracy"] =
            std::round((static_cast<double>(stats["correct_answers"].asInt()) * 10000.0 / answered)) / 100.0;
    }
    if (scoredCount > 0)
    {
        stats["average_score"] = std::round(scoreSum * 100.0 / scoredCount) / 100.0;
    }

    Json::Value certificates(Json::arrayValue);
    int certificatesCount = 0;
    const auto totalExams = stats["total_exams"].asInt();
    const auto overallAccuracy = stats["overall_accuracy"].asDouble();
    appendCertificate(certificates,
                      certificatesCount,
                      "first_full_paper",
                      "入门学习证书",
                      "完成第一套完整试卷",
                      totalExams,
                      1,
                      totalExams >= 1);
    appendCertificate(certificates,
                      certificatesCount,
                      "ten_full_papers",
                      "专项训练证书",
                      "累计完成 10 套完整试卷",
                      totalExams,
                      10,
                      totalExams >= 10);
    appendCertificate(certificates,
                      certificatesCount,
                      "thirty_full_papers",
                      "长期坚持证书",
                      "累计完成 30 套完整试卷",
                      totalExams,
                      30,
                      totalExams >= 30);
    appendCertificate(certificates,
                      certificatesCount,
                      "accuracy_80",
                      "稳定达标证书",
                      "至少完成 5 套试卷，累计正确率达到 80%",
                      overallAccuracy,
                      80,
                      totalExams >= 5 && overallAccuracy >= 80.0);
    stats["certificates"] = certificates;
    stats["certificates_count"] = certificatesCount;
    stats["certificate_count"] = certificatesCount;
    return stats;
}

Json::Value StatisticsService::weakPoints(const std::string &userId) const
{
    std::map<std::string, std::pair<int, int>> aggregate;
    for (const auto &item : repository_.listUserAnswers(userId))
    {
        const auto results = item["statistics"]["results"];
        for (const auto &questionId : results.getMemberNames())
        {
            const auto &row = results[questionId];
            const auto section = inferSection(questionId);
            aggregate[section].first += 1;
            if (row.get("status", "").asString() == "wrong")
            {
                aggregate[section].second += 1;
            }
        }
    }

    Json::Value out(Json::arrayValue);
    for (const auto &[section, values] : aggregate)
    {
        Json::Value row(Json::objectValue);
        row["section"] = section;
        row["total_questions"] = values.first;
        row["wrong_count"] = values.second;
        row["error_rate"] = values.first > 0
                                ? std::round((static_cast<double>(values.second) * 10000.0 / values.first)) / 100.0
                                : 0.0;
        out.append(row);
    }
    return out;
}

Json::Value StatisticsService::learningCurve(const std::string &userId, int days) const
{
    Json::Value out(Json::arrayValue);
    std::map<std::string, Json::Value> byDay;
    for (const auto &item : repository_.listUserAnswers(userId))
    {
        const auto date = item.get("saved_at", "").asString();
        if (date.size() < 10)
        {
            continue;
        }
        const auto day = date.substr(0, 10);
        auto &row = byDay[day];
        if (row.isNull())
        {
            row = Json::Value(Json::objectValue);
            row["date"] = day;
            row["exams_count"] = 0;
            row["questions_count"] = 0;
            row["correct_count"] = 0;
            row["average_score"] = 0.0;
            row["_sum_score"] = 0.0;
        }
        row["exams_count"] = row["exams_count"].asInt() + 1;
        row["questions_count"] =
            row["questions_count"].asInt() + item["statistics"].get("total_questions", 0).asInt();
        row["correct_count"] =
            row["correct_count"].asInt() + item["statistics"].get("correct_count", 0).asInt();
        row["_sum_score"] = row["_sum_score"].asDouble() + item["statistics"].get("score", 0.0).asDouble();
    }

    int emitted = 0;
    for (auto it = byDay.rbegin(); it != byDay.rend() && emitted < days; ++it, ++emitted)
    {
        auto row = it->second;
        const auto examsCount = row["exams_count"].asInt();
        row["average_score"] = examsCount > 0 ? std::round(row["_sum_score"].asDouble() * 100.0 / examsCount) / 100.0
                                              : 0.0;
        row.removeMember("_sum_score");
        out.append(row);
    }
    return out;
}

std::string StatisticsService::inferSection(const std::string &questionId)
{
    std::string lower = questionId;
    std::transform(lower.begin(), lower.end(), lower.begin(), [](unsigned char c) {
        return static_cast<char>(std::tolower(c));
    });
    if (lower.find("vocab") != std::string::npos)
    {
        return "词汇";
    }
    if (lower.find("grammar") != std::string::npos)
    {
        return "语法";
    }
    if (lower.find("reading") != std::string::npos)
    {
        return "阅读";
    }
    if (lower.find("listen") != std::string::npos)
    {
        return "听力";
    }
    return "未知";
}

}  // namespace application::services
