// Auto-generated by tools/sink_class.ps1 from SubscriptionService.h
#include "SubscriptionService.h"

namespace application::services
{

SubscriptionService::SubscriptionService(infrastructure::storage::ProfileRepository &profileRepository,
infrastructure::storage::OrganizationRepository &organizationRepository,
infrastructure::storage::UserRepository &userRepository,
int referralRewardCredits)
: profileRepository_(profileRepository),
organizationRepository_(organizationRepository),
userRepository_(userRepository),
referralRewardCredits_(referralRewardCredits < 0 ? 0 : referralRewardCredits)
{
}

Json::Value SubscriptionService::currentSubscription(const std::string &userId) const
{
    const auto profile = profileRepository_.loadProfile(userId);
    const auto scopeType = profile.get("scope_type", "personal").asString();
    const auto scopeId = profile.get("scope_id", userId).asString();
    if (scopeType == "organization" && !scopeId.empty() && scopeId != userId)
    {
        const auto membership = organizationRepository_.findMembership(userId, scopeId);
        if (!membership.isNull())
        {
            return subscriptionForOrganization(scopeId);
        }
    }
    return subscriptionForUser(userId);
}

Json::Value SubscriptionService::subscriptionForUser(const std::string &userId) const
{
    const auto profile = profileRepository_.loadProfile(userId);
    return buildSubscription(
        "personal",
        userId,
        "",
        normalizePlan(profile.get("plan", "free").asString()),
        normalizeStatus(profile.get("plan_status", "active").asString()),
        profile.get("plan_expires_at", profile.get("plan_expires", "")).asString(),
        0);
}

Json::Value SubscriptionService::subscriptionForOrganization(const std::string &organizationId) const
{
    const auto organization = organizationRepository_.findOrganization(organizationId);
    if (organization.isNull())
    {
        throw common::AppException("ORGANIZATION_NOT_FOUND", "Organization not found: " + organizationId, drogon::k404NotFound);
    }

    const auto subscription = organization.get("subscription", Json::Value(Json::objectValue));
    const auto plan = normalizePlan(subscription.get("plan", "free").asString());
    return buildSubscription(
        "organization",
        organizationId,
        organization.get("organization_type", "business").asString(),
        plan,
        normalizeStatus(subscription.get("status", "active").asString()),
        subscription.get("expires_at", "").asString(),
        subscription.get("seats", defaultSeatsForPlan(plan)).asInt());
}

Json::Value SubscriptionService::updateUserSubscription(const std::string &userId, const Json::Value &patch)
{
    auto profile = profileRepository_.loadProfile(userId);
    profile["plan"] = normalizePlan(patch.get("plan", profile.get("plan", "free")).asString());
    profile["plan_status"] = normalizeStatus(patch.get("status", profile.get("plan_status", "active")).asString());
    profile["plan_expires_at"] = patch.get("expires_at", profile.get("plan_expires_at", "")).asString();
    profile["plan_expires"] = profile["plan_expires_at"].asString();
    profileRepository_.saveProfile(userId, profile);
    const auto subscription = subscriptionForUser(userId);
    settleReferralReward(userId, subscription);
    return subscription;
}

Json::Value SubscriptionService::updateOrganizationSubscription(const std::string &organizationId, const Json::Value &patch)
{
    auto organization = organizationRepository_.findOrganization(organizationId);
    if (organization.isNull())
    {
        throw common::AppException("ORGANIZATION_NOT_FOUND", "Organization not found: " + organizationId, drogon::k404NotFound);
    }

    auto subscription = organization.get("subscription", Json::Value(Json::objectValue));
    subscription["plan"] = normalizePlan(patch.get("plan", subscription.get("plan", "free")).asString());
    subscription["status"] = normalizeStatus(patch.get("status", subscription.get("status", "active")).asString());
    subscription["expires_at"] = patch.get("expires_at", subscription.get("expires_at", "")).asString();
    subscription["seats"] = patch.get("seats", subscription.get("seats", defaultSeatsForPlan(subscription["plan"].asString()))).asInt();
    organization["subscription"] = subscription;
    organizationRepository_.upsertOrganization(organization);
    return subscriptionForOrganization(organizationId);
}

void SubscriptionService::requireAccess(const std::string &userId, const std::string &examAccessLevel) const
{
    const auto normalizedAccessLevel = examAccessLevel == "premium" ? std::string("pro") : examAccessLevel;
    if (normalizedAccessLevel.empty() || normalizedAccessLevel == "free")
    {
        return;
    }

    const auto subscription = currentSubscription(userId);
    if (!subscription.get("is_active", false).asBool())
    {
        throw common::AppException(
            "EXAM_ACCESS_DENIED",
            "This exam requires an active subscription",
            drogon::k403Forbidden);
    }

    const auto plan = subscription.get("plan", "free").asString();
    if (normalizedAccessLevel == "pro" && (plan == "pro" || plan == "ultra"))
    {
        return;
    }

    if (normalizedAccessLevel == "ultra" && plan == "ultra")
    {
        return;
    }

    if (contains(subscription["accessible_levels"], normalizedAccessLevel) || contains(subscription["entitlements"], normalizedAccessLevel))
    {
        return;
    }

    throw common::AppException(
        "EXAM_ACCESS_DENIED",
        "This exam requires a higher subscription tier",
        drogon::k403Forbidden);
}

bool SubscriptionService::hasEntitlement(const std::string &userId, const std::string &entitlementKey) const
{
    if (entitlementKey.empty())
    {
        return true;
    }
    return contains(currentSubscription(userId)["entitlements"], entitlementKey);
}

void SubscriptionService::requireEntitlement(const std::string &userId,
                                             const std::string &entitlementKey,
                                             const std::string &errorMessage) const
{
    if (hasEntitlement(userId, entitlementKey))
    {
        return;
    }

    const auto requiredPlan = minimumPlanForEntitlement(entitlementKey);
    auto message = errorMessage;
    if (message.empty())
    {
        message = requiredPlan.empty()
                      ? "当前套餐不包含该功能"
                      : "该功能需要升级到 " + requiredPlan + " 套餐";
    }
    throw common::AppException("ENTITLEMENT_REQUIRED", message, drogon::k403Forbidden);
}

bool SubscriptionService::isPremium(const std::string &userId) const
{
    const auto subscription = currentSubscription(userId);
    const auto plan = subscription.get("plan", "free").asString();
    return subscription.get("is_active", false).asBool() && (plan == "pro" || plan == "ultra");
}

void SubscriptionService::grantPremium(const std::string &userId, const std::string &expiresAt)
{
    Json::Value patch(Json::objectValue);
    patch["plan"] = "pro";
    patch["status"] = "active";
    patch["expires_at"] = expiresAt;
    updateUserSubscription(userId, patch);
}

void SubscriptionService::settleReferralReward(const std::string &userId, const Json::Value &subscription)
{
    if (!qualifiesForReferralReward(subscription))
    {
        return;
    }

    const auto referredUser = userRepository_.findUserById(userId);
    if (referredUser.isNull())
    {
        return;
    }

    const auto referrerUserId = referredUser.get("referred_by_user_id", "").asString();
    if (referrerUserId.empty() || referredUser.get("referral_reward_status", "none").asString() != "pending")
    {
        return;
    }

    const auto rewardCredits = referralRewardCredits_;
    const auto rewardKey = std::string("referral:") + userId + ":subscription.activated";
    profileRepository_.grantCreditsIfAbsent(referrerUserId, rewardKey, rewardCredits, "referral.subscription.activated");
    userRepository_.grantReferralRewardIfPending(userId, "subscription.activated", rewardCredits, referrerUserId);
}

Json::Value SubscriptionService::buildSubscription(const std::string &scopeType,
const std::string &scopeId,
const std::string &organizationType,
const std::string &plan,
const std::string &status,
const std::string &expiresAt,
int seats)
{
    Json::Value out(Json::objectValue);
    out["scope_type"] = scopeType;
    out["scope_id"] = scopeId;
    out["organization_type"] = scopeType == "organization" ? organizationType : "";
    out["plan"] = normalizePlan(plan);
    out["status"] = normalizeStatus(status);
    out["expires_at"] = expiresAt;
    out["is_active"] = isActive(out["status"].asString(), expiresAt);
    const auto effectivePlan = out["is_active"].asBool() ? out["plan"].asString() : std::string("free");
    out["effective_plan"] = effectivePlan;
    out["entitlements"] = entitlementsForPlan(effectivePlan, scopeType);
    out["entitlement_access"] = entitlementAccessForPlan(effectivePlan, scopeType);
    out["accessible_levels"] = accessibleLevelsForPlan(effectivePlan);
    if (scopeType == "organization")
    {
        out["seats"] = seats > 0 ? seats : defaultSeatsForPlan(out["plan"].asString());
    }
    return out;
}

Json::Value SubscriptionService::entitlementsForPlan(const std::string &plan, const std::string &scopeType)
{
    Json::Value entitlements(Json::arrayValue);
    entitlements.append("question_bank.basic");
    entitlements.append("answer.basic");
    entitlements.append("history.read");
    entitlements.append("weak_points.read");
    entitlements.append("bookmark.read");
    entitlements.append("analytics.basic");
    entitlements.append("recommendation.daily");
    entitlements.append("training.basic");
    entitlements.append("sync.basic");
    if (plan == "pro" || plan == "ultra")
    {
        entitlements.append("question_bank.full");
        entitlements.append("answer.deep_analysis");
        entitlements.append("weak_points.unlimited");
        entitlements.append("recommendation.personalized");
        entitlements.append("training.specialized");
        entitlements.append("analytics.full");
        entitlements.append("ai.explain");
        entitlements.append("ai.study_plan");
        entitlements.append("export.standard");
        entitlements.append("sync.full");
    }
    if (plan == "ultra")
    {
        entitlements.append("training.smart_compose");
        entitlements.append("analytics.prediction");
        entitlements.append("export.full_report");
        entitlements.append("recommendation.realtime");
        entitlements.append("ai.study_plan.dynamic");
        entitlements.append("service.priority");
    }
    if (scopeType == "organization" && (plan == "pro" || plan == "ultra"))
    {
        entitlements.append("organization.portal");
        entitlements.append("organization.member_manage");
        entitlements.append("organization.bulk_import");
        entitlements.append("organization.campus_manage");
        entitlements.append("organization.group_manage");
        entitlements.append("organization.course_package");
        entitlements.append("organization.assignment");
        entitlements.append("organization.analytics.basic");
        entitlements.append("organization.export.standard");
    }
    if (scopeType == "organization" && plan == "ultra")
    {
        entitlements.append("organization.analytics.advanced");
        entitlements.append("organization.risk_alert");
        entitlements.append("organization.report.automatic");
        entitlements.append("organization.branding");
        entitlements.append("organization.api");
        entitlements.append("organization.sso");
    }
    return entitlements;
}

Json::Value SubscriptionService::entitlementAccessForPlan(const std::string &plan, const std::string &scopeType)
{
    const auto grantedEntitlements = entitlementsForPlan(plan, scopeType);
    Json::Value access(Json::objectValue);
    const auto appendDecision = [&](const std::string &key) {
        Json::Value decision(Json::objectValue);
        decision["granted"] = contains(grantedEntitlements, key);
        decision["required_plan"] = minimumPlanForEntitlement(key);
        access[key] = decision;
    };

    for (const auto *key : {
             "question_bank.full",
             "answer.deep_analysis",
             "weak_points.unlimited",
             "recommendation.personalized",
             "training.specialized",
             "training.smart_compose",
             "analytics.full",
             "analytics.prediction",
             "ai.explain",
             "ai.study_plan",
             "ai.study_plan.dynamic",
             "export.standard",
             "export.full_report",
             "recommendation.realtime",
             "service.priority",
             "sync.full"})
    {
        appendDecision(key);
    }
    if (scopeType == "organization")
    {
        for (const auto *key : {
                 "organization.portal",
                 "organization.member_manage",
                 "organization.bulk_import",
                 "organization.campus_manage",
                 "organization.group_manage",
                 "organization.course_package",
                 "organization.assignment",
                 "organization.analytics.basic",
                 "organization.export.standard",
                 "organization.analytics.advanced",
                 "organization.risk_alert",
                 "organization.report.automatic",
                 "organization.branding",
                 "organization.api",
                 "organization.sso"})
        {
            appendDecision(key);
        }
    }
    return access;
}

Json::Value SubscriptionService::accessibleLevelsForPlan(const std::string &)
{
    Json::Value levels(Json::arrayValue);
    levels.append("N1");
    levels.append("N2");
    levels.append("N3");
    levels.append("N4");
    levels.append("N5");
    return levels;
}

std::string SubscriptionService::minimumPlanForEntitlement(const std::string &entitlementKey)
{
    if (entitlementKey == "training.smart_compose" ||
        entitlementKey == "analytics.prediction" ||
        entitlementKey == "export.full_report" ||
        entitlementKey == "recommendation.realtime" ||
        entitlementKey == "ai.study_plan.dynamic" ||
        entitlementKey == "service.priority" ||
        entitlementKey == "organization.analytics.advanced" ||
        entitlementKey == "organization.risk_alert" ||
        entitlementKey == "organization.report.automatic" ||
        entitlementKey == "organization.branding" ||
        entitlementKey == "organization.api" ||
        entitlementKey == "organization.sso")
    {
        return "ultra";
    }
    return "pro";
}

int SubscriptionService::defaultSeatsForPlan(const std::string &plan)
{
    if (plan == "ultra")
    {
        return 100;
    }
    if (plan == "pro")
    {
        return 25;
    }
    return 5;
}

bool SubscriptionService::contains(const Json::Value &values, const std::string &expected)
{
    if (!values.isArray())
    {
        return false;
    }
    for (const auto &value : values)
    {
        if (value.asString() == expected)
        {
            return true;
        }
    }
    return false;
}

bool SubscriptionService::isActive(const std::string &status, const std::string &expiresAt)
{
    if (status != "active" && status != "trial")
    {
        return false;
    }
    if (expiresAt.empty())
    {
        return true;
    }

    if (expiresAt.size() <= 10)
    {
        return expiresAt >= common::nowIso8601().substr(0, 10);
    }
    return expiresAt >= common::nowIso8601();
}

bool SubscriptionService::qualifiesForReferralReward(const Json::Value &subscription)
{
    const auto plan = normalizePlan(subscription.get("plan", "free").asString());
    return subscription.get("is_active", false).asBool() &&
           subscription.get("status", "active").asString() == "active" &&
           (plan == "pro" || plan == "ultra");
}

std::string SubscriptionService::normalizePlan(const std::string &plan)
{
    if (plan == "premium")
    {
        return "pro";
    }
    if (plan == "free" || plan == "pro" || plan == "ultra")
    {
        return plan;
    }
    return "free";
}

std::string SubscriptionService::normalizeStatus(const std::string &status)
{
    if (status == "active" || status == "trial" || status == "expired" || status == "canceled")
    {
        return status;
    }
    return "active";
}

}  // namespace application::services
