// Auto-generated by tools/sink_class.ps1 from UserService.h
#include "UserService.h"

namespace application::services
{

UserService::UserService(
infrastructure::storage::UserRepository &repository,
infrastructure::storage::ProfileRepository &profileRepository,
infrastructure::storage::OrganizationRepository &organizationRepository,
SubscriptionService &subscriptionService)
: repository_(repository),
profileRepository_(profileRepository),
organizationRepository_(organizationRepository),
subscriptionService_(subscriptionService)
{
}

Json::Value UserService::getUser(const std::string &userId) const
{
    return buildUserView(requireUser(userId));
}

Json::Value UserService::usersByRole(const std::string &roleId) const
{
    Json::Value out(Json::arrayValue);
    const auto users = repository_.usersByRole(roleId);
    for (const auto &user : users)
    {
        out.append(buildUserView(user));
    }
    return out;
}

Json::Value UserService::searchUsers(const std::string &query, std::size_t limit) const
{
    const auto needle = normalizeSearchText(query);
    Json::Value out(Json::arrayValue);
    if (needle.empty())
    {
        return out;
    }

    struct SearchHit
    {
        int score;
        std::string sortKey;
        Json::Value user;
    };

    std::vector<SearchHit> hits;
    const auto users = repository_.users();
    for (const auto &userId : users.getMemberNames())
    {
        const auto &user = users[userId];
        const auto score = scoreUserSearchMatch(user, profileRepository_.loadProfile(userId), needle);
        if (score <= 0)
        {
            continue;
        }
        auto view = buildUserView(user);
        hits.push_back({score, normalizeSearchText(view.get("username", userId).asString()), view});
    }

    std::sort(hits.begin(), hits.end(), [](const SearchHit &left, const SearchHit &right) {
        if (left.score != right.score)
        {
            return left.score > right.score;
        }
        return left.sortKey < right.sortKey;
    });

    const auto cappedLimit = (std::min)(limit, hits.size());
    for (std::size_t index = 0; index < cappedLimit; ++index)
    {
        out.append(hits[index].user);
    }
    return out;
}

Json::Value UserService::allRoles() const
{
    return repository_.roles();
}

Json::Value UserService::permissions(const std::string &userId) const
{
    const auto user = requireUser(userId);
    const auto profile = profileRepository_.loadProfile(userId);
    const auto membership = resolveMembership(userId, user, profile);
    const auto subscription = subscriptionService_.currentSubscription(userId);
    const auto roles = effectiveRoles(user["roles"], membership["roles"]);
    Json::Value out(Json::objectValue);
    out["user_id"] = user.get("id", userId).asString();
    out["roles"] = roles;
    out["subscription"] = subscription;
    out["features"] = visibleFeatures(roles, subscription);
    out["sections"] = visibleSections(roles, subscription);
    return out;
}

Json::Value UserService::context(const std::string &userId) const
{
    const auto user = requireUser(userId);
    const auto profile = profileRepository_.loadProfile(userId);
    const auto membership = resolveMembership(userId, user, profile);
    const auto subscription = subscriptionService_.currentSubscription(userId);

    Json::Value out(Json::objectValue);
    out["user"] = buildUserView(user);
    out["profile"] = buildProfileView(profile, subscription);
    out["membership"] = membership;
    out["subscription"] = subscription;
    out["permissions"] = permissions(userId);
    out["memberships"] = organizationRepository_.listMembershipsForUser(userId);
    out["organizations"] = organizationRepository_.listOrganizationsForUser(userId);
    return out;
}

Json::Value UserService::claimReferral(const std::string &userId, const std::string &referralCode) const
{
    return buildUserView(repository_.claimReferral(userId, referralCode));
}

Json::Value UserService::requireUser(const std::string &userId) const
{
    auto user = repository_.findUserById(userId);
    if (user.isNull())
    {
        throw common::AppException("USER_NOT_FOUND", "User not found: " + userId, drogon::k404NotFound);
    }
    return user;
}

bool UserService::hasAnyRole(const Json::Value &userRoles, const std::vector<std::string> &requiredRoles)
{
    for (const auto &item : userRoles)
    {
        const auto role = item.asString();
        if (std::find(requiredRoles.begin(), requiredRoles.end(), role) != requiredRoles.end())
        {
            return true;
        }
    }
    return false;
}

bool UserService::hasEntitlement(const Json::Value &entitlements, const std::string &required)
{
    for (const auto &item : entitlements)
    {
        if (item.asString() == required)
        {
            return true;
        }
    }
    return false;
}

Json::Value UserService::buildUserView(const Json::Value &user) const
{
    const auto userId = user.get("id", "").asString();
    const auto profile = profileRepository_.loadProfile(userId);
    const auto membership = resolveMembership(userId, user, profile);
    const auto subscription = subscriptionService_.currentSubscription(userId);
    const auto roles = effectiveRoles(user["roles"], membership["roles"]);

    Json::Value out(Json::objectValue);
    out["id"] = userId;
    out["user_id"] = userId;
    out["username"] = user.get("username", "").asString();
    const auto activeMemberNo = membership.get("member_no", user.get("member_no", "")).asString();
    out["member_no"] = activeMemberNo;
    out["memberNo"] = activeMemberNo;
    out["student_no"] = membership.get("student_no", user.get("student_no", "")).asString();
    out["studentNo"] = out["student_no"].asString();
    out["employee_no"] = membership.get("employee_no", user.get("employee_no", "")).asString();
    out["employeeNo"] = out["employee_no"].asString();
    out["dev_login_id"] = user.get("dev_login_id", "").asString();
    out["email"] = user.get("email", "").asString();
    out["email_verified"] = user.get("email_verified", false).asBool();
    out["phone"] = user.get("phone", "").asString();
    out["phone_verified"] = user.get("phone_verified", false).asBool();
    out["status"] = user.get("status", "active").asString();
    out["created_at"] = user.get("created_at", "").asString();
    out["roles"] = roles;
    out["role_ids"] = roles;
    out["roleIds"] = roles;
    out["display_name"] = profile.get("display_name", "").asString();
    out["displayName"] = profile.get("display_name", "").asString();
    out["avatar_url"] = profile.get("avatar_url", "").asString();
    out["avatar"] = profile.get("avatar_url", "").asString();
    out["locale"] = profile.get("locale", "zh-CN").asString();
    out["goal_level"] = profile.get("goal_level", "").asString();
    out["goal_date"] = profile.get("goal_date", "").asString();
    out["daily_target"] = profile.get("daily_target", 20).asInt();
    out["last_active_at"] = profile.get("last_active_at", "").asString();
    out["lastLoginAt"] = profile.get("last_active_at", "").asString();
    out["scope_type"] = membership.get("scope_type", "personal").asString();
    out["scope_id"] = membership.get("scope_id", userId).asString();
    out["organization_type"] = membership.get("organization_type", "").asString();
    out["subscription"] = subscription;
    out["plan"] = subscription.get("plan", "free").asString();
    out["plan_status"] = subscription.get("status", "active").asString();
    out["plan_expires_at"] = subscription.get("expires_at", "").asString();
    out["entitlements"] = subscription["entitlements"];
    out["accessible_levels"] = subscription["accessible_levels"];
    out["accessibleLevels"] = subscription["accessible_levels"];
    out["balance"] = buildBalance(profile);
    out["referral"] = buildReferralView(user);
    return out;
}

Json::Value UserService::buildProfileView(const Json::Value &profile, const Json::Value &subscription)
{
    Json::Value out = profile;
    out["plan"] = subscription.get("plan", "free").asString();
    out["plan_status"] = subscription.get("status", "active").asString();
    out["plan_expires_at"] = subscription.get("expires_at", "").asString();
    return out;
}

Json::Value UserService::buildBalance(const Json::Value &profile)
{
    Json::Value balance(Json::objectValue);
    balance["credits"] = profile.get("credits", 0).asInt();
    balance["updated_at"] = profile.get("credits_updated_at", profile.get("last_active_at", "")).asString();
    balance["updatedAt"] = balance["updated_at"].asString();
    return balance;
}

Json::Value UserService::buildReferralView(const Json::Value &user)
{
    Json::Value referral(Json::objectValue);
    referral["code"] = user.get("referral_code", "").asString();
    referral["referral_code"] = referral["code"].asString();
    referral["referred_by_user_id"] = user.get("referred_by_user_id", "").asString();
    referral["referredByUserId"] = referral["referred_by_user_id"].asString();
    referral["referred_by_code"] = user.get("referred_by_code", "").asString();
    referral["referredByCode"] = referral["referred_by_code"].asString();
    referral["bound_at"] = user.get("referral_bound_at", "").asString();
    referral["boundAt"] = referral["bound_at"].asString();
    referral["reward_status"] = user.get("referral_reward_status", "none").asString();
    referral["rewardStatus"] = referral["reward_status"].asString();
    referral["reward_granted_at"] = user.get("referral_reward_granted_at", "").asString();
    referral["rewardGrantedAt"] = referral["reward_granted_at"].asString();
    referral["reward_trigger"] = user.get("referral_reward_trigger", "").asString();
    referral["rewardTrigger"] = referral["reward_trigger"].asString();
    referral["reward_credit_amount"] = user.get("referral_reward_credit_amount", 0).asInt();
    referral["rewardCreditAmount"] = referral["reward_credit_amount"].asInt();
    referral["reward_credit_recipient_user_id"] = user.get("referral_reward_credit_recipient_user_id", "").asString();
    referral["rewardCreditRecipientUserId"] = referral["reward_credit_recipient_user_id"].asString();
    referral["has_referrer"] = !referral["referred_by_user_id"].asString().empty();
    referral["hasReferrer"] = referral["has_referrer"].asBool();
    return referral;
}

Json::Value UserService::resolveMembership(const std::string &userId, const Json::Value &user, const Json::Value &profile) const
{
    const auto scopeType = profile.get("scope_type", "personal").asString();
    const auto scopeId = profile.get("scope_id", userId).asString();
    if (scopeType == "organization" && !scopeId.empty() && scopeId != userId)
    {
        auto membership = organizationRepository_.findMembership(userId, scopeId);
        if (!membership.isNull())
        {
            return membership;
        }
    }

    Json::Value membership(Json::objectValue);
    membership["membership_id"] = "personal:" + userId;
    membership["user_id"] = userId;
    membership["scope_type"] = "personal";
    membership["scope_id"] = userId;
    membership["organization_type"] = "";
    membership["member_no"] = user.get("member_no", "").asString();
    membership["student_no"] = "";
    membership["employee_no"] = "";
    membership["roles"] = user["roles"];
    return membership;
}

Json::Value UserService::effectiveRoles(const Json::Value &baseRoles, const Json::Value &membershipRoles)
{
    Json::Value out(Json::arrayValue);
    appendUniqueRoles(out, baseRoles);
    appendUniqueRoles(out, membershipRoles);
    return out;
}

void UserService::appendUniqueRoles(Json::Value &target, const Json::Value &source)
{
    if (!source.isArray())
    {
        return;
    }
    for (const auto &role : source)
    {
        const auto value = role.asString();
        bool exists = false;
        for (const auto &current : target)
        {
            if (current.asString() == value)
            {
                exists = true;
                break;
            }
        }
        if (!exists)
        {
            target.append(value);
        }
    }
}

Json::Value UserService::visibleFeatures(const Json::Value &userRoles, const Json::Value &subscription)
{
    Json::Value features(Json::arrayValue);
    const auto &entitlements = subscription["entitlements"];
    auto add = [&](const std::string &id,
                   const std::string &title,
                   const std::string &icon,
                   const std::vector<std::string> &requiredRoles = {},
                   const std::string &requiredEntitlement = "") {
        if (!requiredRoles.empty() && !hasAnyRole(userRoles, requiredRoles))
        {
            return;
        }
        if (!requiredEntitlement.empty() && !hasEntitlement(entitlements, requiredEntitlement))
        {
            return;
        }
        Json::Value item(Json::objectValue);
        item["id"] = id;
        item["title"] = title;
        item["icon"] = icon;
        features.append(item);
    };

    add("profile", "个人信息", "👤");
    add("subscription", "套餐与权益", "⭐");
    add("community", "加入社群", "💬");
    add("bookmarks", "收藏与错题", "📚", {"student", "teacher", "reviewer", "orgAdmin", "systemAdmin", "superAdmin"}, "bookmark");
    add("stats", "学习统计", "📊", {"student", "teacher", "reviewer", "orgAdmin", "systemAdmin", "superAdmin"}, "weak_points");
    add("recommendation", "推荐练习", "🎯", {"student", "teacher", "reviewer", "orgAdmin", "systemAdmin", "superAdmin"}, "recommendation");
    add("training", "专项训练", "🚀", {"student", "teacher", "reviewer", "orgAdmin", "systemAdmin", "superAdmin"}, "training.specialized");
    add("questions", "题目管理", "🗂️", {"teacher", "orgAdmin", "systemAdmin", "superAdmin"});
    add("review", "阅卷审核", "📝", {"reviewer", "systemAdmin", "superAdmin"});
    add("memberAdmin", "成员管理", "👥", {"orgAdmin", "systemAdmin", "superAdmin"});
    add("sysFlags", "系统开关", "⚙️", {"superAdmin"});
    return features;
}

Json::Value UserService::visibleSections(const Json::Value &userRoles, const Json::Value &subscription)
{
    Json::Value sections(Json::arrayValue);
    auto add = [&](const std::string &id,
                   const std::string &title,
                   const std::vector<std::string> &requiredRoles = {},
                   const std::string &requiredEntitlement = "") {
        if (!requiredRoles.empty() && !hasAnyRole(userRoles, requiredRoles))
        {
            return;
        }
        if (!requiredEntitlement.empty() && !hasEntitlement(subscription["entitlements"], requiredEntitlement))
        {
            return;
        }
        Json::Value item(Json::objectValue);
        item["id"] = id;
        item["title"] = title;
        sections.append(item);
    };

    add("dashboard", "概览");
    add("profile", "个人资料");
    add("subscription", "套餐");
    add("roles", "角色权限");
    add("learning", "学习能力", {"student", "teacher", "reviewer", "orgAdmin", "systemAdmin", "superAdmin"});
    add("admin-hub", "管理面板", {"teacher", "reviewer", "orgAdmin", "systemAdmin", "superAdmin"});
    add("logout", "退出登录");
    return sections;
}

std::string UserService::normalizeSearchText(const std::string &value)
{
    std::string out;
    out.reserve(value.size());
    for (const auto ch : value)
    {
        out.push_back(static_cast<char>(std::tolower(static_cast<unsigned char>(ch))));
    }
    return out;
}

int UserService::scoreSearchField(const std::string &field,
const std::string &needle,
const int exactScore,
const int prefixScore,
const int containsScore)
{
    const auto haystack = normalizeSearchText(field);
    if (haystack.empty())
    {
        return 0;
    }
    if (haystack == needle)
    {
        return exactScore;
    }
    if (haystack.rfind(needle, 0) == 0)
    {
        return prefixScore;
    }
    return haystack.find(needle) != std::string::npos ? containsScore : 0;
}

int UserService::scoreUserSearchMatch(const Json::Value &user, const Json::Value &profile, const std::string &needle)
{
    int score = 0;
    score = (std::max)(score, scoreSearchField(user.get("username", "").asString(), needle, 140, 110, 80));
    score = (std::max)(score, scoreSearchField(user.get("dev_login_id", "").asString(), needle, 135, 105, 76));
    score = (std::max)(score, scoreSearchField(user.get("id", user.get("user_id", "")).asString(), needle, 130, 100, 74));
    score = (std::max)(score, scoreSearchField(user.get("member_no", "").asString(), needle, 120, 92, 72));
    score = (std::max)(score, scoreSearchField(user.get("email", "").asString(), needle, 112, 90, 68));
    score = (std::max)(score, scoreSearchField(user.get("phone", "").asString(), needle, 108, 88, 66));
    score = (std::max)(score, scoreSearchField(profile.get("display_name", "").asString(), needle, 118, 94, 70));
    return score;
}

}  // namespace application::services
