// Auto-generated by tools/sink_class.ps1 from WechatService.h
#include "WechatService.h"

#include <sstream>

#include <drogon/HttpClient.h>
#include <drogon/utils/Utilities.h>

namespace application::services
{
namespace
{
Json::Value parseJsonBody(const drogon::HttpResponsePtr &response)
{
    Json::Value root(Json::nullValue);
    if (!response)
    {
        return root;
    }
    Json::CharReaderBuilder builder;
    std::string errors;
    std::istringstream input(std::string(response->getBody()));
    Json::parseFromStream(builder, input, &root, &errors);
    return root;
}

std::string responseText(const drogon::HttpResponsePtr &response)
{
    return response ? std::string(response->getBody()) : std::string();
}

std::string urlEncode(const std::string &value)
{
    return drogon::utils::urlEncode(value);
}
}  // namespace

WechatService::WechatService(infrastructure::storage::UserRepository &userRepository,
AuthService &authService,
WechatService::Config config)
: userRepository_(userRepository), authService_(authService), config_(std::move(config))
{
}

Json::Value WechatService::generateQrcode()
{
    const auto state = common::generateRequestId();

    Json::Value out(Json::objectValue);
    out["state"] = state;
    out["expires_in"] = 300;

    if (config_.appId.empty())
    {
        // Development stub: return a fake QR code URL
        out["qrcode_url"] = "https://stub.wechat.example/qrcode?state=" + state;
        out["stub"] = true;
        Json::Value testIds(Json::arrayValue);
        for (const auto &testId : defaultDevelopmentTestIds())
        {
            testIds.append(testId);
        }
        out["test_ids"] = testIds;
    }
    else
    {
        const auto callbackUrl = config_.callbackBaseUrl + "/api/v1/auth/wechat/callback";
        out["qrcode_url"] = "https://open.weixin.qq.com/connect/qrconnect"
                            "?appid=" + config_.appId +
                            "&redirect_uri=" + urlEncode(callbackUrl) +
                            "&response_type=code"
                            "&scope=snsapi_login"
                            "&state=" + urlEncode(state) + "#wechat_redirect";
    }

    std::unique_lock lock(mutex_);
    pendingStates_[state] = PendingAuth{.state = state};
    return out;
}

std::string WechatService::handleCallback(const std::string &code, const std::string &state)
{
    std::string openid;
    std::string nickname;
    std::string avatarUrl;

    if (config_.appId.empty())
    {
        // Stub: use the code itself as a fake openid
        openid = "stub_openid_" + code;
        nickname = code;
    }
    else
    {
        auto tokenResp = exchangeCodeForToken(code);
        openid = tokenResp.get("openid", "").asString();
        if (openid.empty())
        {
            throw common::AppException("WECHAT_AUTH_FAILED", "Failed to get openid from WeChat", drogon::k502BadGateway);
        }
        nickname = tokenResp.get("nickname", "").asString();
        avatarUrl = tokenResp.get("headimgurl", "").asString();
    }

    const auto user = userRepository_.upsertWechatUser(openid, nickname, avatarUrl, config_.appId.empty() ? code : std::string());
    const auto sessionToken = authService_.createSessionForUser(user);

    std::unique_lock lock(mutex_);
    auto it = pendingStates_.find(state);
    if (it != pendingStates_.end())
    {
        it->second.sessionToken = sessionToken;
        it->second.userId = user.get("id", "").asString();
        it->second.username = user.get("username", "").asString();
        it->second.roles = user["roles"];
        it->second.done = true;
    }
    return sessionToken;
}

Json::Value WechatService::poll(const std::string &state)
{
    std::unique_lock lock(mutex_);
    auto it = pendingStates_.find(state);
    if (it == pendingStates_.end())
    {
        throw common::AppException("WECHAT_STATE_NOT_FOUND", "Invalid or expired state", drogon::k400BadRequest);
    }

    Json::Value out(Json::objectValue);
    out["done"] = it->second.done;
    if (it->second.done)
    {
        out["token"] = it->second.sessionToken;
        out["user_id"] = it->second.userId;
        out["username"] = it->second.username;
        out["roles"] = it->second.roles;
        pendingStates_.erase(it);
    }
    return out;
}

const std::vector<std::string> &WechatService::defaultDevelopmentTestIds()
{
    static const std::vector<std::string> testIds = {
        "wxdev_001",
        "wxdev_002",
        "wxdev_003",
        "admin_001",
        "teacher_001",
        "assistant_001",
        "content_001"};
    return testIds;
}

Json::Value WechatService::exchangeCodeForToken(const std::string &code) const
{
    if (config_.appId.empty() || config_.appSecret.empty() || config_.callbackBaseUrl.empty())
    {
        throw common::AppException(
            "WECHAT_NOT_CONFIGURED",
            "Set WECHAT_APP_ID, WECHAT_APP_SECRET, and WECHAT_CALLBACK_BASE_URL before enabling real WeChat login.",
            drogon::k503ServiceUnavailable);
    }

    auto tokenClient = drogon::HttpClient::newHttpClient("https://api.weixin.qq.com");
    auto tokenRequest = drogon::HttpRequest::newHttpRequest();
    tokenRequest->setMethod(drogon::Get);
    tokenRequest->setPath(
        "/sns/oauth2/access_token?appid=" + urlEncode(config_.appId) +
        "&secret=" + urlEncode(config_.appSecret) +
        "&code=" + urlEncode(code) +
        "&grant_type=authorization_code");
    const auto [tokenResult, tokenResponse] = tokenClient->sendRequest(tokenRequest);
    if (tokenResult != drogon::ReqResult::Ok || !tokenResponse)
    {
        throw common::AppException("WECHAT_AUTH_FAILED", "Failed to request WeChat access_token", drogon::k502BadGateway);
    }
    const auto tokenPayload = parseJsonBody(tokenResponse);
    if (tokenResponse->statusCode() < drogon::k200OK || tokenResponse->statusCode() >= drogon::k300MultipleChoices ||
        tokenPayload.isMember("errcode"))
    {
        const auto message = tokenPayload.get("errmsg", responseText(tokenResponse)).asString();
        throw common::AppException("WECHAT_AUTH_FAILED", "WeChat access_token error: " + message, drogon::k502BadGateway);
    }

    const auto accessToken = tokenPayload.get("access_token", "").asString();
    const auto openid = tokenPayload.get("openid", "").asString();
    if (accessToken.empty() || openid.empty())
    {
        throw common::AppException("WECHAT_AUTH_FAILED", "WeChat response did not include access_token/openid", drogon::k502BadGateway);
    }

    auto userClient = drogon::HttpClient::newHttpClient("https://api.weixin.qq.com");
    auto userRequest = drogon::HttpRequest::newHttpRequest();
    userRequest->setMethod(drogon::Get);
    userRequest->setPath(
        "/sns/userinfo?access_token=" + urlEncode(accessToken) +
        "&openid=" + urlEncode(openid) +
        "&lang=zh_CN");
    const auto [userResult, userResponse] = userClient->sendRequest(userRequest);

    Json::Value out(Json::objectValue);
    out["openid"] = openid;
    out["unionid"] = tokenPayload.get("unionid", "").asString();
    if (userResult == drogon::ReqResult::Ok && userResponse &&
        userResponse->statusCode() >= drogon::k200OK && userResponse->statusCode() < drogon::k300MultipleChoices)
    {
        const auto userPayload = parseJsonBody(userResponse);
        if (!userPayload.isMember("errcode"))
        {
            out["nickname"] = userPayload.get("nickname", "").asString();
            out["headimgurl"] = userPayload.get("headimgurl", "").asString();
            out["unionid"] = userPayload.get("unionid", out["unionid"]).asString();
        }
    }
    return out;
}

}  // namespace application::services
